### ISSUE TITLE
monitoring exception and parsl hang with doc specific monitoring config

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1010]
using a configuration coming from the docs at: https://parsl.readthedocs.io/en/latest/userguide/monitoring.html
```
    monitoring=MonitoringHub(
        hub_address=address_by_hostname(), logging_level=logging.INFO, resource_monitoring_interval=10)
```

workflow startup fails with this error:

```
2019-06-04 04:06:00 parsl.dataflow.dflow:81 [INFO]  Parsl version: 0.8.0a0
2019-06-04 04:06:00 parsl.dataflow.usage_tracking.usage:126 [DEBUG]  Tracking status: False
2019-06-04 04:06:00 parsl.dataflow.usage_tracking.usage:127 [DEBUG]  Testing mode   : False
Process Process-1:
Traceback (most recent call last):
  File "/opt/lsst/software/stack/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/lsst/software/stack/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/global/homes/b/bxc/.local/lib/python3.6/site-packages/parsl/monitoring/monitoring.py", line 386, in hub_starter
    hub = Hub(*args, **kwargs)
  File "/global/homes/b/bxc/.local/lib/python3.6/site-packages/parsl/monitoring/monitoring.py", line 340, in __init__
    self.sock.bind(('0.0.0.0', hub_port))
TypeError: an integer is required (got type NoneType)
```

and then my run hangs, rather than exiting as I would like.

I would be expecting 

There's a test in the constructor for `Hub`, which logs a critical message - but that message does not appear on my console, and does not cause further shutdown of parsl.
```
        if not hub_port:
            self.logger.critical("At this point the hub port must be set")
```

After a long time, the following is output, but the workflow still hangs:

```
Traceback (most recent call last):
  File "/global/homes/b/bxc/.local/lib/python3.6/site-packages/parsl/monitoring/monitoring.py", line 221, in start
    udp_dish_port = comm_q.get(block=True, timeout=120)
  File "/opt/lsst/software/stack/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/multiprocessing/queues.py", line 105, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "workflow.py", line 152, in <module>
    parsl.load(config)
  File "/global/homes/b/bxc/.local/lib/python3.6/site-packages/typeguard.py", line 513, in wrapper
    retval = func(*args, **kwargs)
  File "/global/homes/b/bxc/.local/lib/python3.6/site-packages/parsl/dataflow/dflow.py", line 1067, in load
    cls._dfk = DataFlowKernel(config)
  File "/global/homes/b/bxc/.local/lib/python3.6/site-packages/parsl/dataflow/dflow.py", line 96, in __init__
    self.monitoring.start()
  File "/global/homes/b/bxc/.local/lib/python3.6/site-packages/parsl/monitoring/monitoring.py", line 224, in start
    raise Exception("Hub failed to start")
Exception: Hub failed to start
```

**Comment by benclifford** [comment]
crossref #1167
