### ISSUE TITLE
checkpointing vs monitoring

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1014]
With both checkpoint and monitoring, it looks like `task` rows are not written out for checkpointed tasks; then when those checkpointed tasks are competed, monitoring tries to UPDATE the (missing) task rows, and gives:

```sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'task' expected to update 3 row(s); 0 were matched.```

with this full stack trace:

```
Process Process-2:
Traceback (most recent call last):
  File "/opt/lsst/software/stack/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/lsst/software/stack/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/global/homes/b/bxc/.local/lib/python3.6/site-packages/parsl/monitoring/db_manager.py", line 414, in dbm_starter
    dbm.start(priority_msgs, resource_msgs)
  File "/global/homes/b/bxc/.local/lib/python3.6/site-packages/parsl/monitoring/db_manager.py", line 296, in start
    messages=update_messages)
  File "/global/homes/b/bxc/.local/lib/python3.6/site-packages/parsl/monitoring/db_manager.py", line 347, in _update
    self.db.update(table=table, columns=columns, messages=messages)
  File "/global/homes/b/bxc/.local/lib/python3.6/site-packages/parsl/monitoring/db_manager.py", line 68, in update
    self.session.bulk_update_mappings(mapper, mappings)
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/sqlalchemy/1.2.16/lib/python/SQLAlchemy-1.2.16-py3.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 2798, in bulk_update_mappings
    mapper, mappings, True, False, False, False, False
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/sqlalchemy/1.2.16/lib/python/SQLAlchemy-1.2.16-py3.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 2837, in _bulk_save_mappings
    transaction.rollback(_capture_exception=True)
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/sqlalchemy/1.2.16/lib/python/SQLAlchemy-1.2.16-py3.6-linux-x86_64.egg/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/sqlalchemy/1.2.16/lib/python/SQLAlchemy-1.2.16-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/sqlalchemy/1.2.16/lib/python/SQLAlchemy-1.2.16-py3.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 2822, in _bulk_save_mappings
    update_changed_only,
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/sqlalchemy/1.2.16/lib/python/SQLAlchemy-1.2.16-py3.6-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 180, in _bulk_update
    bookkeeping=False,
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/sqlalchemy/1.2.16/lib/python/SQLAlchemy-1.2.16-py3.6-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 1008, in _emit_update_statements
    % (table.description, len(records), rows)
sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'task' expected to update 3 row(s); 0 were matched.
```

**Comment by annawoodard** [comment]
This is critical-path for @ravihansa3000 (they are starting a production run early November).

**Comment by ZhuozhaoLi** [comment]
@benclifford I cannot seem to reproduce this problem with a minimal example. Looking at the code, it seems it should be fixed with these few lines of changes in the previous PR. If you still remember how to reproduce, could you please try that? 

https://github.com/Parsl/parsl/blob/1b0f63f7d4bbb9a23b99dc58c642a2f948c63b9c/parsl/monitoring/db_manager.py#L290-L294

**Comment by ZhuozhaoLi** [comment]
@benclifford Not sure what the ideal fix here is. How about adding mechanism to guarantee the monitoring wrapper sends out the first message?

**Comment by benclifford** [comment]
The below program demonstrates the problem if run *twice*, against the commit immediately before the code that you pasted above (which was PR #1104). After PR #1104 was applied, this code no longer fails, so i think this issue is fixed.

```
import parsl

from parsl.monitoring.monitoring import MonitoringHub
from parsl.configs.local_threads import config
from parsl.utils import get_all_checkpoints
from parsl.addresses import address_by_hostname

config.checkpoint_mode = 'task_exit'
config.checkpoint_files = get_all_checkpoints()
config.monitoring=MonitoringHub(
       hub_address=address_by_hostname(),
       hub_port=55055,
       resource_monitoring_interval=10,
   )

parsl.load(config)

@parsl.python_app(cache=True)
def foo():
    print("Executing foo body")
    return 7

print(foo().result())
```
