### ISSUE TITLE
Debug monitoring UDP messages missing on Theta

### ISSUE THREAD

**Issue by ZhuozhaoLi** [Parsl/parsl#1069]
Some UDP messages for monitoring intermittently miss on Theta.

**Comment by benclifford** [comment]
I did some investigation on theta for a run where I was not seeing as many log messages as I expected.

In a simple test, messages were not being sent as frequently as I expected: the monitoring worker loop assumes that everything runs almost instantly, but the call in that loop to `pm.children()` was taking multiple seconds, causing a reduction in monitoring message frequency.

This might explain some missing messages.

On another theta run, I was only seeing a couple of messages near the start of a run then nothing more; in #1045 I have added additional logging of exceptions to see if the monitoring worker process is breaking. I haven't had results from that larger run back yet. (cc @villarrealas)

**Comment by villarrealas** [comment]
Ben and I just got some additional monitoring done on Theta: we get the following result when monitoring processes started in a Singularity container.

```Traceback (most recent call last):
  File "/projects/LSSTADSP_DESC/Run2.1i/miniconda3/envs/parsl-imsim-201903/lib/python3.6/site-packages/psutil/_pslinux.py", line 1513, in wrapper
    return fun(self, *args, **kwargs)
  File "/projects/LSSTADSP_DESC/Run2.1i/miniconda3/envs/parsl-imsim-201903/lib/python3.6/site-packages/psutil/_pslinux.py", line 1676, in io_counters
    with open_binary(fname) as f:
  File "/projects/LSSTADSP_DESC/Run2.1i/miniconda3/envs/parsl-imsim-201903/lib/python3.6/site-packages/psutil/_common.py", line 587, in open_binary
    return open(fname, "rb", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/118171/io'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lus/theta-fs0/projects/LSSTADSP_DESC/Run2.1i/parsl/parsl/monitoring/monitoring.py", line 454, in monitor
    d['psutil_process_disk_write'] += child.io_counters().write_bytes
  File "/projects/LSSTADSP_DESC/Run2.1i/miniconda3/envs/parsl-imsim-201903/lib/python3.6/site-packages/psutil/__init__.py", line 876, in io_counters
    return self._proc.io_counters()
  File "/projects/LSSTADSP_DESC/Run2.1i/miniconda3/envs/parsl-imsim-201903/lib/python3.6/site-packages/psutil/_pslinux.py", line 1516, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=118171)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lus/theta-fs0/projects/LSSTADSP_DESC/Run2.1i/parsl/parsl/monitoring/monitoring.py", line 456, in monitor
    except psutil._exceptions.AccessDenied:
AttributeError: module 'psutil' has no attribute '_exceptions'```

**Comment by benclifford** [comment]
On theta I ran this:

```
> singularity run alcf_run2.0i_production201903.simg /bin/bash
```

which starts up a shell using the production software stack that we've been using in our app.

Then in another shell:
```
> pstree -p benc
sshd(1763)─┬─bash(1764)───starter-suid(2614)─┬─docker_run.sh(2642)───bash(2686)
           │                                 ├─{starter-suid}(2649)
           │                                 ├─{starter-suid}(2650)
           │                                 ├─{starter-suid}(2651)
           │                                 ├─{starter-suid}(2652)
           │                                 ├─{starter-suid}(2653)
           │                                 └─{starter-suid}(2655)
           └─bash(2703)───pstree(3081)

systemd(1752)───(sd-pam)(1759)
(base) benc@thetalogin4:~> ls /proc/1763/io -l
-r-------- 1 root root 0 Jun 20 07:27 /proc/1763/io
(base) benc@thetalogin4:~> ls /proc/1764/io -l
-r-------- 1 benc users 0 Jun 20 07:27 /proc/1764/io
(base) benc@thetalogin4:~> ls /proc/2614/io -l
-r-------- 1 root root 0 Jun 20 07:27 /proc/2614/io
(base) benc@thetalogin4:~> ls /proc/2642/io -l
-r-------- 1 benc users 0 Jun 20 07:27 /proc/2642/io
```
The process invoking singularity is bash(1764) running as `benc` - in a parsl run this would be something like `process_worker_pool.py`, owned by the submitting user.

The application code is `docker_run.sh`, 2642, also running as `benc`.

But there's a setuid layer running as `root` in between, `starter-suid`, 2614.

This is likely the equivalent process that is causing the above exception - pid 118171 in @villarrealas 's stack trace.

**Comment by benclifford** [comment]
There's a further exception where an attempt is made to catch `psutil._exceptions.AccessDenied`. The latest `psutil` has this as `psutil.AccessDenied`, since https://github.com/giampaolo/psutil/commit/58491430, release 5.5.1.

A fix here would be to require psutil >= 5.5.1 and modify the source accordingly.

**Comment by benclifford** [comment]
@ZhuozhaoLi and I have done some more investigating. We found two more sources of lost messages:

i) on some theta nodes, socket.send() was failing to resolve hostname to IP address, and throwing an exception there. We re-ran with an IP address instead of a hostname and this error went away.

ii) This code was timing out sometimes:

```
        try:
            x = self.sock.sendto(buffer, (self.ip, self.port))
        except socket.timeout:
            logging.error("Could not send message within timeout limit")
```
with the default timeout of 10 seconds.

In further investigation of ii) we also observed that some successful sends were taking many seconds (for example, one took 7 seconds)

In the same run (though maybe on different nodes?) similar sends took around 10ms

**Comment by ZhuozhaoLi** [comment]
A followup of the investigation: we conducted some more tests.

1. 40/48/64 workers per node. We found that with 40 workers per node, we do not see the `Could not send message within timeout limit` error message on any task, and everything looks just fine. But with 48+ workers per node, we always observed the error message. With more workers per node, we observed error message on more tasks.

2. We tried both CPU-intensive and sleep tasks. It does not seem to change anything -- we see error message in both cases.

3. We tried to change to `timeout` in `UDPRadio` to 60 seconds -- we still got timeout error anyway.
Besides, we always saw the last UDP message was sent successfully, while all the previous messages got timeout.

I will try to write a minimal example to reproduce the problem and inquire ALCF about this.
