### ISSUE TITLE
aws installing parsl dev branch fails to communicate with worker node

### ISSUE THREAD

**Issue by macintoshpie** [Parsl/parsl#1096]
Pip installing parsl from a local cloned repo, or from `pip install git+...` doesn't seem to work, and results in an interchange exchange error (see logs below)

### Setup
```bash
$conda create --name parsl_py368 python=3.6
$conda activate parsl_py368
$python --version
Python 3.6.8 :: Anaconda, Inc.
$pip install git+https://github.com/Parsl/parsl.git
$python -c "import parsl; print(parsl.__version__)"
0.8.0
$pip install boto3
```

used ami with packages already installed, see issue #1094 - image is public

```python
import parsl
from parsl.config import Config
from parsl.executors import HighThroughputExecutor
from parsl.providers import AWSProvider
from parsl.app.app import python_app

parsl.set_stream_logger()

parsl_config = Config(
  executors=[
    HighThroughputExecutor(
      label='htex_local',
      worker_debug=True,
      address=myip,
      cores_per_worker=1,
      max_workers=1,
      provider=AWSProvider(
        image_id='ami-078018a195b149801', # image with packages already installed
        instance_type='t2.micro',
        nodes_per_block=1,
        init_blocks=1,
        max_blocks=1,
        min_blocks=0,
        region='us-east-2',
        key_name='myKeyPair',
        state_file='awsproviderstate.json',
        linger=True
      ),
    )
  ],
  strategy=None,
)

parsl.load(parsl_config)

@python_app
def hello ():
  return 'Hello World!'

print(hello().result())
```

### Logs
parsl.log
```
2019-06-25 18:11:02.889 parsl.dataflow.dflow:80 [DEBUG]  Starting DataFlowKernel with config
Config(
    app_cache=True, 
    checkpoint_files=None, 
    checkpoint_mode=None, 
    checkpoint_period=None, 
    data_management_max_threads=10, 
    executors=[HighThroughputExecutor(
        address='3.17.191.124', 
        cores_per_worker=1, 
        heartbeat_period=30, 
        heartbeat_threshold=120, 
        interchange_port_range=(55000, 56000), 
        label='htex_local', 
        launch_cmd='process_worker_pool.py {debug} {max_workers} -p {prefetch_capacity} -c {cores_per_worker} -m {mem_per_worker} --poll {poll_period} --task_url={task_url} --result_url={result_url} --logdir={logdir} --block_id={{block_id}} --hb_period={heartbeat_period} --hb_threshold={heartbeat_threshold} ', 
        managed=True, 
        max_workers=1, 
        mem_per_worker=None, 
        poll_period=10, 
        prefetch_capacity=0, 
        provider=AWSProvider(
            'ami-078018a195b149801',
            iam_instance_profile_arn='', 
            init_blocks=1, 
            instance_type='t2.micro', 
            key_file=None, 
            key_name='testKeyPair', 
            launcher=SingleNodeLauncher(), 
            linger=True, 
            max_blocks=1, 
            min_blocks=0, 
            nodes_per_block=1, 
            parallelism=1, 
            profile=None, 
            region='us-east-2', 
            spot_max_bid=0, 
            state_file='awsproviderstate.json', 
            walltime='01:00:00', 
            worker_init=''
        ), 
        storage_access=[], 
        suppress_failure=False, 
        worker_debug=True, 
        worker_logdir_root=None, 
        worker_port_range=(54000, 55000), 
        worker_ports=None, 
        working_dir=None
    )], 
    lazy_errors=True, 
    monitoring=None, 
    retries=0, 
    run_dir='runinfo', 
    strategy=None, 
    usage_tracking=False
)
2019-06-25 18:11:02.891 parsl.dataflow.dflow:81 [INFO]  Parsl version: 0.8.0
2019-06-25 18:11:02.891 parsl.dataflow.usage_tracking.usage:126 [DEBUG]  Tracking status: False
2019-06-25 18:11:02.891 parsl.dataflow.usage_tracking.usage:127 [DEBUG]  Testing mode   : False
2019-06-25 18:11:02.891 parsl.dataflow.dflow:103 [INFO]  Run id is: d383b22b-0861-4b5d-88b4-3fc51b17b870
2019-06-25 18:11:02.995 parsl.dataflow.memoization:52 [INFO]  App caching initialized
2019-06-25 18:11:02.996 parsl.executors.high_throughput.executor:430 [DEBUG]  Starting queue management thread
2019-06-25 18:11:02.997 parsl.executors.high_throughput.executor:307 [DEBUG]  [MTHREAD] queue management worker starting
2019-06-25 18:11:02.997 parsl.executors.high_throughput.executor:434 [DEBUG]  Started queue management thread
2019-06-25 18:11:03.007 parsl.executors.high_throughput.executor:266 [DEBUG]  Created management thread: <Thread(Thread-1, started daemon 140042702456576)>
2019-06-25 18:11:03.007 parsl.executors.high_throughput.executor:240 [DEBUG]  Launch command: process_worker_pool.py --debug --max_workers=1 -p 0 -c 1 -m None --poll 10 --task_url=tcp://3.17.191.124:54221 --result_url=tcp://3.17.191.124:54573 --logdir=/home/ubuntu/runinfo/016/htex_local --block_id={block_id} --hb_period=30 --hb_threshold=120 
2019-06-25 18:11:03.007 parsl.executors.high_throughput.executor:243 [DEBUG]  Starting HighThroughputExecutor with provider:
AWSProvider(
    'ami-078018a195b149801',
    iam_instance_profile_arn='', 
    init_blocks=1, 
    instance_type='t2.micro', 
    key_file=None, 
    key_name='testKeyPair', 
    launcher=SingleNodeLauncher(), 
    linger=True, 
    max_blocks=1, 
    min_blocks=0, 
    nodes_per_block=1, 
    parallelism=1, 
    profile=None, 
    region='us-east-2', 
    spot_max_bid=0, 
    state_file='awsproviderstate.json', 
    walltime='01:00:00', 
    worker_init=''
)
2019-06-25 18:11:04.051 parsl.providers.aws.aws:500 [INFO]  Started up 1 instance i-0b9163994b922b477 . Instance type:t2.micro
2019-06-25 18:11:04.052 parsl.providers.aws.aws:598 [DEBUG]  Started instance_id: i-0b9163994b922b477
2019-06-25 18:11:04.052 parsl.executors.high_throughput.executor:547 [DEBUG]  Launched block 0->i-0b9163994b922b477
2019-06-25 18:11:04.052 parsl.dataflow.strategy:125 [DEBUG]  Scaling strategy: None
2019-06-25 18:11:04.054 parsl.dataflow.dflow:687 [INFO]  Task 0 submitted for App hello, waiting on tasks []
2019-06-25 18:11:04.054 parsl.dataflow.dflow:697 [DEBUG]  Task 0 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f5e3ebe9898 state=pending> parent=None>
2019-06-25 18:11:04.054 parsl.executors.high_throughput.executor:514 [DEBUG]  Pushing function <function hello at 0x7f5e3a9e16a8> to queue with args ()
2019-06-25 18:11:04.112 parsl.dataflow.dflow:463 [INFO]  Task 0 launched on executor htex_local
2019-06-25 18:13:03.622 parsl.executors.high_throughput.executor:345 [WARNING]  Executor shutting down due to exception from interchange
2019-06-25 18:13:03.622 parsl.executors.high_throughput.executor:347 [ERROR]  Exception: Manager b'314849c805b4' attempted to register with a bad registration message. Caused a critical failure
NoneType: None
2019-06-25 18:13:03.622 parsl.dataflow.dflow:250 [ERROR]  Task 0 failed
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/parsl_py368/lib/python3.6/site-packages/parsl/dataflow/dflow.py", line 245, in handle_exec_update
    res = future.result()
  File "/home/ubuntu/miniconda3/envs/parsl_py368/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/ubuntu/miniconda3/envs/parsl_py368/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
parsl.executors.high_throughput.interchange.BadRegistration: Manager b'314849c805b4' attempted to register with a bad registration message. Caused a critical failure
2019-06-25 18:13:03.623 parsl.dataflow.dflow:271 [INFO]  Task 0 failed after 0 retry attempts
2019-06-25 18:13:03.623 parsl.executors.high_throughput.executor:384 [INFO]  [MTHREAD] queue management worker finished
2019-06-25 18:13:03.625 parsl.dataflow.dflow:822 [INFO]  DFK cleanup initiated
2019-06-25 18:13:03.626 parsl.dataflow.dflow:733 [INFO]  Summary of tasks in DFK:
2019-06-25 18:13:03.626 parsl.dataflow.dflow:764 [INFO]  Tasks in state States.failed: 0
2019-06-25 18:13:03.626 parsl.dataflow.dflow:771 [INFO]  End of summary
2019-06-25 18:13:03.626 parsl.dataflow.dflow:846 [INFO]  Terminating flow_control and strategy threads
2019-06-25 18:13:03.627 parsl.providers.aws.aws:625 [DEBUG]  Ignoring cancel requests due to linger mode
2019-06-25 18:13:03.627 parsl.executors.high_throughput.executor:618 [INFO]  Attempting HighThroughputExecutor shutdown
2019-06-25 18:13:03.627 parsl.executors.high_throughput.executor:622 [INFO]  Finished HighThroughputExecutor shutdown attempt
2019-06-25 18:13:03.627 parsl.data_provider.data_manager:98 [DEBUG]  Done with executor shutdown
2019-06-25 18:13:03.627 parsl.dataflow.dflow:878 [INFO]  DFK cleanup complete
```

interchange.log
```
2019-06-25 18:11:03.003 interchange:138 [DEBUG]  Initializing Interchange process
2019-06-25 18:11:03.003 interchange:146 [INFO]  Attempting connection to client at 127.0.0.1 on ports: 55225,55991,55561
2019-06-25 18:11:03.004 interchange:159 [INFO]  Connected to client
2019-06-25 18:11:03.004 interchange:187 [INFO]  Bound to ports 54221,54573 for incoming worker connections
2019-06-25 18:11:03.004 interchange:201 [INFO]  Platform info: {'parsl_v': '0.8.0', 'python_v': '3.6.8', 'os': 'Linux', 'hostname': 'ip-172-31-25-66', 'dir': '/home/ubuntu'}
2019-06-25 18:11:03.006 interchange:319 [INFO]  Incoming ports bound
2019-06-25 18:11:03.013 interchange:236 [INFO]  [TASK_PULL_THREAD] Starting
2019-06-25 18:11:03.013 interchange:260 [DEBUG]  [COMMAND] Command Server Starting
2019-06-25 18:11:03.024 interchange:246 [DEBUG]  [TASK_PULL_THREAD] 0 tasks in internal queue
2019-06-25 18:11:03.025 interchange:427 [DEBUG]  Managers count (total/interesting): 0/0
2019-06-25 18:11:03.025 interchange:460 [DEBUG]  [MAIN] either no interesting managers or no tasks, so skipping manager pass
2019-06-25 18:11:03.034 interchange:246 [DEBUG]  [TASK_PULL_THREAD] 0 tasks in internal queue
2019-06-25 18:11:03.035 interchange:427 [DEBUG]  Managers count (total/interesting): 0/0
2019-06-25 18:11:03.035 interchange:460 [DEBUG]  [MAIN] either no interesting managers or no tasks, so skipping manager pass
2019-06-25 18:11:03.045 interchange:246 [DEBUG]  [TASK_PULL_THREAD] 0 tasks in internal queue
2019-06-25 18:11:03.045 interchange:427 [DEBUG]  Managers count (total/interesting): 0/0

<skipping repeated messages>

2019-06-25 18:13:03.555 interchange:460 [DEBUG]  [MAIN] either no interesting managers or no tasks, so skipping manager pass
2019-06-25 18:13:03.561 interchange:246 [DEBUG]  [TASK_PULL_THREAD] 1 tasks in internal queue
2019-06-25 18:13:03.566 interchange:427 [DEBUG]  Managers count (total/interesting): 0/0
2019-06-25 18:13:03.566 interchange:460 [DEBUG]  [MAIN] either no interesting managers or no tasks, so skipping manager pass
2019-06-25 18:13:03.567 interchange:352 [DEBUG]  [MAIN] starting task_outgoing section
2019-06-25 18:13:03.568 interchange:365 [WARNING]  [MAIN] Got a non-json registration message from manager:b'314849c805b4'
2019-06-25 18:13:03.568 interchange:366 [DEBUG]  [MAIN] Message :
b'314849c805b4'

2019-06-25 18:13:03.575 interchange:246 [DEBUG]  [TASK_PULL_THREAD] 1 tasks in internal queue
2019-06-25 18:13:03.626 interchange:264 [DEBUG]  [COMMAND] Received command request: MANAGERS
2019-06-25 18:13:03.627 interchange:304 [DEBUG]  [COMMAND] Reply: [{'manager': '314849c805b4', 'block_id': None, 'worker_count': 0, 'tasks': 0, 'active': True}]
```

*on worker node*
manager.log
```
2019-06-25 18:13:03.556 parsl:524 Rank:0 [INFO]  Python version: 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
2019-06-25 18:13:03.556 parsl:525 Rank:0 [INFO]  Debug logging: True
2019-06-25 18:13:03.556 parsl:526 Rank:0 [INFO]  Log dir: /home/ubuntu/runinfo/016/htex_local
2019-06-25 18:13:03.556 parsl:527 Rank:0 [INFO]  Manager ID: 314849c805b4
2019-06-25 18:13:03.556 parsl:528 Rank:0 [INFO]  Block ID: 0
2019-06-25 18:13:03.556 parsl:529 Rank:0 [INFO]  cores_per_worker: 1
2019-06-25 18:13:03.556 parsl:530 Rank:0 [INFO]  mem_per_worker: None
2019-06-25 18:13:03.556 parsl:531 Rank:0 [INFO]  task_url: tcp://3.17.191.124:54221
2019-06-25 18:13:03.556 parsl:532 Rank:0 [INFO]  result_url: tcp://3.17.191.124:54573
2019-06-25 18:13:03.556 parsl:533 Rank:0 [INFO]  max_workers: 1
2019-06-25 18:13:03.556 parsl:534 Rank:0 [INFO]  poll_period: 10
2019-06-25 18:13:03.556 parsl:535 Rank:0 [INFO]  Prefetch capacity: 0
2019-06-25 18:13:03.556 parsl:107 Rank:0 [INFO]  Manager started
2019-06-25 18:13:03.559 parsl:121 Rank:0 [INFO]  Manager connected
2019-06-25 18:13:03.560 parsl:140 Rank:0 [INFO]  Manager will spawn 1 workers
2019-06-25 18:13:03.565 parsl:314 Rank:0 [DEBUG]  Manager synced with workers
2019-06-25 18:13:03.567 parsl:188 Rank:0 [INFO]  [TASK PULL THREAD] starting
2019-06-25 18:13:03.567 parsl:194 Rank:0 [DEBUG]  Sending registration message: b'{"parsl_v": "0.8.0", "python_v": "3.6.8", "worker_count": 1, "block_id": "0", "prefetch_capacity": 0, "max_capacity": 1, "os": "Linux", "hname": "ip-10-0-15-190", "dir": "/root"}'
2019-06-25 18:13:03.568 parsl:207 Rank:0 [DEBUG]  [TASK_PULL_THREAD] ready workers:1, pending tasks:0
2019-06-25 18:13:03.568 parsl:214 Rank:0 [DEBUG]  [TASK_PULL_THREAD] Requesting tasks: 1
2019-06-25 18:13:03.568 parsl:268 Rank:0 [DEBUG]  [RESULT_PUSH_THREAD] Starting thread
2019-06-25 18:13:03.568 parsl:323 Rank:0 [INFO]  Loop start
2019-06-25 18:13:03.568 parsl:271 Rank:0 [DEBUG]  [RESULT_PUSH_THREAD] push poll period: 0.01
2019-06-25 18:13:03.578 parsl:245 Rank:0 [DEBUG]  [TASK_PULL_THREAD] No incoming tasks
2019-06-25 18:13:03.578 parsl:207 Rank:0 [DEBUG]  [TASK_PULL_THREAD] ready workers:1, pending tasks:0
2019-06-25 18:13:03.578 parsl:214 Rank:0 [DEBUG]  [TASK_PULL_THREAD] Requesting tasks: 1

<skipping repeated messages>

2019-06-25 18:14:44.548 parsl:207 Rank:0 [DEBUG]  [TASK_PULL_THREAD] ready workers:1, pending tasks:0
2019-06-25 18:14:44.548 parsl:177 Rank:0 [DEBUG]  Return from heartbeat: None
2019-06-25 18:14:44.548 parsl:214 Rank:0 [DEBUG]  [TASK_PULL_THREAD] Requesting tasks: 1
2019-06-25 18:15:14.549 parsl:245 Rank:0 [DEBUG]  [TASK_PULL_THREAD] No incoming tasks
2019-06-25 18:15:14.550 parsl:254 Rank:0 [CRITICAL]  [TASK_PULL_THREAD] Missing contact with interchange beyond heartbeat_threshold
2019-06-25 18:15:14.550 parsl:256 Rank:0 [CRITICAL]  [TASK_PULL_THREAD] Exiting
2019-06-25 18:15:14.551 parsl:328 Rank:0 [CRITICAL]  [MAIN] Received kill event, terminating worker processes
2019-06-25 18:15:14.560 parsl:293 Rank:0 [CRITICAL]  [RESULT_PUSH_THREAD] Exiting
2019-06-25 18:15:14.560 parsl:335 Rank:0 [CRITICAL]  Terminating worker <Process(Process-1, started)>:True
2019-06-25 18:15:14.562 parsl:337 Rank:0 [DEBUG]  Worker:<Process(Process-1, stopped[SIGTERM])> joined successfully
2019-06-25 18:15:14.563 parsl:343 Rank:0 [INFO]  process_worker_pool ran for 131.00097918510437 seconds
2019-06-25 18:15:14.563 parsl:555 Rank:0 [INFO]  process_worker_pool exiting
```

worker_0.log
```
2019-06-25 18:13:03.567 worker_log:399 Rank:0 [INFO]  Worker 0 started
2019-06-25 18:13:03.567 worker_log:401 Rank:0 [DEBUG]  Debug logging enabled
```

**Comment by macintoshpie** [comment]
False alert - I needed to also edit the aws template.py to install from git as well. Things work as intended and this issue should be ignored.
