### ISSUE TITLE
Exceptions raised on the IPP is wrapped by RemoteError

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#110]
When running apps that raise an application, the exception is returned as is by Threads, however they 
are wrapped by IPP inside a RemoteError. This is confusing and adds inconsistencies in handling logic based on the executor being used. 

Here's a wrapped exception traceback 
```
Traceback (most recent call last):
  File "/home/yadu/src/parsl/parsl/dataflow/dflow.py", line 174, in handle_update
    future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/ipyparallel/client/asyncresult.py", line 224, in _resolve_result
    raise r
ipyparallel.error.RemoteError: TypeError(a float is required)
```

**Comment by annawoodard** [comment]
I think this should be very high-priority. Fixing this would speed up debugging on other items.

**Comment by yadudoc** [comment]
This is very hard. IPP converts the exceptions to a string, which makes it hard to reconstruct the original exception. Another confounding issue is that exceptions even if serialized might not have be deserializable on the local side due to missing (non-imported) libraries
