### ISSUE TITLE
Required Keywords Defaults missing under certain conditions

### ISSUE THREAD

**Issue by Lnaden** [Parsl/parsl#1166]
We've run into an issue where functions which specify required kwargs loose any defaults under certain conditions, causing app failures because the function cannot be called anymore.

The conditions this is under are as follows:
* Pure Python function
* `python_app(func)` call rather than as a decorator
* Directly providing the `python_app` output to the DataFlowKernal
* `HighThroughputExecutor`
* `SLURMProvider`
* Python 3.7
* func has a required keyword operator
* Parsl version 0.8.0

I cannot prove all of these conditions are required, but I do show some modifications where this error does not occur below

## More details:

The function we are wrapping with the `PythonApp` is:

```python
def compute(input_data: Union[Dict[str, Any], 'ResultInput'],
            program: str,
            *,
            raise_error: bool = False,
            local_options: Optional[Dict[str, Any]] = None,
            return_dict: bool = False) -> 'Result':
```

and we are specifically wrapping it with the `python_app(compute)` rather than as a decorator.

Looking at the `inspect.getfullargspec(compute)` output, we get the following:

```python
FullArgSpec(
    args=['input_data', 'program'], 
    varargs=None, 
    varkw=None, 
    defaults=None, 
    kwonlyargs=['raise_error', 'local_options', 'return_dict'], 
    kwonlydefaults={'raise_error': False, 'local_options': None, 'return_dict': False}, 
    annotations={'return': 'Result', 
        'input_data': typing.Union[typing.Dict[str, typing.Any], ForwardRef('ResultInput')],
        'program': <class 'str'>, 
        'raise_error': <class 'bool'>, 
        'local_options': typing.Union[typing.Dict[str, typing.Any], NoneType], 
        'return_dict': <class 'bool'>}
)
```

However, if we are to look at `inspect.getfullargspec(func)` again in `wrapper` internal funciton of the `app.wrap_error` decorator, I get this output:

```python
FullArgSpec(
    args=['input_data', 'program'], 
    varargs=None, 
    varkw=None, 
    defaults=None, 
    kwonlyargs=['raise_error', 'local_options', 'return_dict'], 
    kwonlydefaults=None,  # CRITICAL MISSING INFORMATION
    annotations={}  # Also missing
)
```

Our particular pipeline passes in only the `local_options` kwarg, expecting the other two (`raise_error` and `return_dict`) to have defaults, instead, we get this backtrace:

```
    Traceback (most recent call last):
      File "/home/lnaden/github/qcfractal/qcfractal/queue/parsl_adapter.py", line 17, in _get_future
        return future.result()
      File "/home/lnaden/miniconda3/envs/qca/lib/python3.7/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/home/lnaden/miniconda3/envs/qca/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception 
      File "/home/lnaden/miniconda3/envs/qca/lib/python3.7/site-packages/parsl/dataflow/futures.py", line 120, in parent_callback
        res.reraise()
      File "/home/lnaden/miniconda3/envs/qca/lib/python3.7/site-packages/parsl/app/errors.py", line 163, in reraise
        reraise(t, v, tb)
      File "/home/lnaden/miniconda3/envs/qca/lib/python3.7/site-packages/six.py", line 692, in reraise
        raise value.with_traceback(tb)
      File "/home/lnaden/miniconda3/envs/qca/lib/python3.7/site-packages/parsl/app/errors.py", line 186, in wrapper
        return func(*args, **kwargs)
    TypeError: compute() missing 2 required keyword-only arguments: 'raise_error' and 'return_dict'
```

## Modifications to bulleted outline above which allow normal execution:

These Items are all independent sets of modifications which on their own avoid the bug

1. If I comment out the bear `*` in the function call, everything works normally
2. Using a much simpler local config works fine, specifically this one:
    * `parsl.config.Config(executors=[parsl.executors.threads.ThreadPoolExecutor(max_threads=1)])`
0. The below block of code works fine as a standalone (modified from the Parsl Tests)
   ```python
    from parsl.app.app import App
    from parsl.tests.configs.local_threads import config

    @App('python')
    def app_double(x, *, waffles="soup", some_unused_req_kwarg=False):
        return x * 2

    @App('python')
    def app_sum(inputs=[]):
        return sum(inputs)

    @App('python')
    def slow_app_double(x, sleep_dur=0.05):
        import time
        time.sleep(sleep_dur)
        return x * 2

    def test_1(N=10):
        """Testing code snippet from the documentation
        """

        # Create a list of integers
        items = range(0, N)

        # Map Phase : Apply an *app* function to each item in list
        mapped_results = []
        for i in items:
            kwarg = {"waffles": "syrup"}
            arg = [i]
            x = app_double(i, waffles="syrup")
            x = app_double(i, **kwarg)
            x = app_double(*arg, **kwarg)
            mapped_results.append(x)

        total = app_sum(inputs=mapped_results)

        print(total.result())

        assert total.result() != sum(items), "Sum is wrong {0} != {1}".format(
            total.result(), sum(items))

    if __name__ == "__main__":
        parsl.clear()
        parsl.load(config)
        test_1(N=2)
   ```

**Comment by benclifford** [comment]
I think the likeliest change around: `2. Using a much simpler local config works fine` is that using a local executor passes python objects around (for functions, for example) but using a remote executor does some serialisation/deserialisation - if that is the case, then HighThroughputExecutor + slurm should behave the same as HighThroughpout + LocalProvider (or any other `Provider`) because HighThroughputExecutor always serialises things, when ThreadPoolExecutor doesn't.

I've seen some other places in python where kwargs get lost - I'll have a poke around based on the information you've given above.

**Comment by benclifford** [comment]
I think this recreates the same / similar problem - swap the commenting on the top two import lines to try the two behaviours. With htex_local, I get a missing keyword `b` exception; with local_threads I get the default `True` value returned.

```
# from parsl.configs.htex_local import config
from parsl.configs.local_threads import config
import parsl

parsl.load(config)

@parsl.python_app
def compute(a, *, b = True):
  return "the_result (" + str(b) + ")"

fut = compute(1)
r = fut.result()

print("Result is: {}".format(r))
```

**Comment by benclifford** [comment]
Removing the `,*,` makes my example work with htex_local.

**Comment by benclifford** [comment]
Pulling out the serialisation/deserialisation from the guts of the HighThroughputExecutor, the below gives: `TypeError: compute() missing 1 required keyword-only argument: 'b'`; but if `, *,` is removed, then it succeeds with a result.

```
from ipyparallel.serialize import pack_apply_message, unpack_apply_message

def compute(a, *, b = True):
  return "the_result (" + b.__repr__() + ")"

m = pack_apply_message(compute, [1], {})

f, a, p = unpack_apply_message(m)

r = f(*a, **p)

print("Result is: {}".format(r))
```

**Comment by benclifford** [comment]
and I can see from inspecting compute vs f with `:nspect.getfullargspec`:

```
inspect compute = FullArgSpec(args=['a'], varargs=None, varkw=None, defaults=None, kwonlyargs=['b'], kwonlydefaults={'b': True}, annotations={})
inspect f = FullArgSpec(args=['a'], varargs=None, varkw=None, defaults=None, kwonlyargs=['b'], kwonlydefaults=None, annotations={})
```

**Comment by benclifford** [comment]
@Lnaden - I think using what I am seeing against your original list of potential variables, you should only see behaviour different when switching between htex (on any provider) vs local threads, and with `,*,` vs without `,*,`, and that all your other potential variables should not have any effect.

Please comment if you see any of those other variables affecting things.

**Comment by Lnaden** [comment]
Thanks for delving into this, I was not in a position to test the other variables due to the hardware I had nor do I fully understand the Parsl stack well enough to know where to look. I defer to your judgement on what the actual variability is, and the minimal example you have helps. 

I suspected that the problem had laid in the serialization of the function somehow, but because I was not properly equipped to fully test it I provided as much as I could. 

Its interesting the serialization issue seems to come from `ipyparallel` more than anything, does this issue need to be sent up the chain there for them to fix? Further, is the Ipyparallel serialization what the HTExecutor uses or something different? If so on both, can I borrow your minimal example here and send it up the chain to them, or do you have a separate suggestion?

**Comment by benclifford** [comment]
HTExecutor uses (un)pack_apply_message from ipyparallel - for example, see `submit()` in parsl/executors/high_throughput/executor.py

It looks like that serialization sometimes uses `dill`, and `dill` has this issue open which is the same symptoms that we are seeing: https://github.com/uqfoundation/dill/issues/313  - but I haven't dug into what is actually being run here to know if that's the issue.

Hopefully removing `,*,` is enough of a workaround for you to keep going with using parsl, with slightly less argument safety.

**Comment by benclifford** [comment]
@Lnaden i'm fine with you taking the example and using it in other reports.

**Comment by Lnaden** [comment]
> HTExecutor uses (un)pack_apply_message from ipyparallel - for example, see submit() in parsl/executors/high_throughput/executor.py

Thanks, that keeps it simple.

> From the ipyparallel source, it looks like that serialization sometimes uses dill, and dill has this issue open which is the same symptoms that we are seeing:

That looks like similar issues, but I don't think thats quite the same. May be related, don't know.

> Hopefully removing ,*, is enough of a workaround for you to keep going with using parsl, with slightly less argument safety.

For now that workaround is fine, we had already switched over to it to keep working before I raised the issue here. 

> i'm fine with you taking the example and using it in other reports.

Great, I'll send this up the stack and see where that goes. Thanks for digging into this!

**Comment by benclifford** [comment]
I think I found where in ipyparallel this is happening. Try installing this fork of ipyparallel:

`pip install git+https://github.com/benclifford/ipyparallel@kwdefaults`

(kwdefaults branch in my fork of ipyparallel)

It makes my example work, but I haven't tested it further / thought about if it can be pushed upstream.

**Comment by Lnaden** [comment]
That would fix it from what I can see as well. I'll raise the issue on `ipyparallel` themselves, reference both this issue and point to those changes as a potential fix, we'll see what they say.

Fortunately, its not blocking on our end. Thanks again for looking into this!

**Comment by Lnaden** [comment]
It looks like this has been resolved at the ipython level. Not sure when it will make it into release, but the fix is in the code now. https://github.com/ipython/ipyparallel/pull/465
