### ISSUE TITLE
parsl + htex + slurm hangs if slurm command times out, without making further progress

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1241]
When slurm commands hang, parsl appears to hang. I have experienced this on cori in two different places:

1. a timeout occurs during DFK `__init__`. See first stack trace. This shows the main thread dying, I think, but the process didn't exit - some other thread is perhaps not exiting. I pressed ctrl-C and you can see the remaining stack trace there. It looks like the interchange is not exiting. This case is addressed by PR #1244

2. a similar slurm provider timeout happens, but launched from within flow control. I think this then kills the flow control thread -- see second stack trace. This case is addressed by PR #1242

A rough workaround is to massively increase the timeout, although this only reduces the problem and does not account for situations where there is a sporadic very long timeout of the slurm command.

The stack trace for 1:

```
2019-08-29 09:27:13 parsl.providers.slurm.slurm:185 [DEBUG]  Requesting one block with 1 nodes
2019-08-29 09:27:13 parsl.providers.slurm.slurm:202 [DEBUG]  Writing submit script
2019-08-29 09:27:13 parsl.providers.slurm.slurm:206 [DEBUG]  moving files
2019-08-29 09:27:23 parsl.channels.local.local:76 [WARNING]  Execution of command 'sbatch /global/u1/b/bxc/dm/parsl/runinfo_1inkn66/000/submit_scripts/parsl.auto.1567096033.0868108.submit' failed due to 
Command 'sbatch /global/u1/b/bxc/dm/parsl/runinfo_1inkn66/000/submit_scripts/parsl.auto.1567096033.0868108.submit' timed out after 10 seconds
2019-08-29 09:27:23 parsl.executors.high_throughput.executor:264 [ERROR]  Scaling out failed: Command 'sbatch /global/u1/b/bxc/dm/parsl/runinfo_1inkn66/000/submit_scripts/parsl.auto.1567096033.0868108.submit' timed out after 10 seconds
Traceback (most recent call last):
  File "parsl/tests/test_bash_apps/test_basic.py", line 101, in <module>
    dfk = parsl.load(config)
  File "/global/homes/b/bxc/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/typeguard/__init__.py", line 703, in wrapper
    retval = func(*args, **kwargs)
  File "/global/u1/b/bxc/dm/parsl/parsl/dataflow/dflow.py", line 1095, in load
    cls._dfk = DataFlowKernel(config)
  File "/global/u1/b/bxc/dm/parsl/parsl/dataflow/dflow.py", line 158, in __init__
    self.add_executors(config.executors + [data_manager_executor])
  File "/global/u1/b/bxc/dm/parsl/parsl/dataflow/dflow.py", line 818, in add_executors
    executor.start()
  File "/global/u1/b/bxc/dm/parsl/parsl/executors/high_throughput/executor.py", line 285, in start
    self.initialize_scaling()
  File "/global/u1/b/bxc/dm/parsl/parsl/executors/high_throughput/executor.py", line 265, in initialize_scaling
    raise e
  File "/global/u1/b/bxc/dm/parsl/parsl/executors/high_throughput/executor.py", line 262, in initialize_scaling
    self.scale_out(blocks=self.provider.init_blocks)
  File "/global/u1/b/bxc/dm/parsl/parsl/executors/high_throughput/executor.py", line 564, in scale_out
    internal_block = self.provider.submit(launch_cmd, 1)
  File "/global/u1/b/bxc/dm/parsl/parsl/providers/slurm/slurm.py", line 212, in submit
    retcode, stdout, stderr = self.execute_wait("sbatch {0}".format(channel_script_path))
  File "/global/u1/b/bxc/dm/parsl/parsl/providers/cluster_provider.py", line 86, in execute_wait
    return self.channel.execute_wait(cmd, t)
  File "/global/u1/b/bxc/dm/parsl/parsl/channels/local/local.py", line 70, in execute_wait
    proc.wait(timeout=walltime)
  File "/global/homes/b/bxc/.conda/envs/dm-play/lib/python3.7/subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "/global/homes/b/bxc/.conda/envs/dm-play/lib/python3.7/subprocess.py", line 1616, in _wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command 'sbatch /global/u1/b/bxc/dm/parsl/runinfo_1inkn66/000/submit_scripts/parsl.auto.1567096033.0868108.submit' timed out after 10 seconds




^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/global/homes/b/bxc/.conda/envs/dm-play/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Process Process-1:
Traceback (most recent call last):
  File "/global/homes/b/bxc/.conda/envs/dm-play/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/global/homes/b/bxc/.conda/envs/dm-play/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/global/u1/b/bxc/dm/parsl/parsl/executors/high_throughput/interchange.py", line 562, in starter
    ic.start()
  File "/global/u1/b/bxc/dm/parsl/parsl/executors/high_throughput/interchange.py", line 365, in start
    self.socks = dict(poller.poll(timeout=poll_period))
  File "/global/homes/b/bxc/.conda/envs/dm-play/lib/python3.7/site-packages/zmq/sugar/poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc

```

The stack trace for 2:

```
2019-08-29 09:20:57 parsl.dataflow.strategy:259 [DEBUG]  Requesting 1 more blocks
2019-08-29 09:20:57 parsl.providers.slurm.slurm:185 [DEBUG]  Requesting one block with 1 nodes
2019-08-29 09:20:57 parsl.providers.slurm.slurm:202 [DEBUG]  Writing submit script
2019-08-29 09:20:57 parsl.providers.slurm.slurm:206 [DEBUG]  moving files
2019-08-29 09:21:07 parsl.channels.local.local:76 [WARNING]  Execution of command 'sbatch /global/u1/b/bxc/dm/parsl/runinfo_45uj53m/000/submit_scripts/parsl.auto.1567095657.8399532.submit' failed due to 
Command 'sbatch /global/u1/b/bxc/dm/parsl/runinfo_45uj53m/000/submit_scripts/parsl.auto.1567095657.8399532.submit' timed out after 10 seconds
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/global/homes/b/bxc/.conda/envs/dm-play/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/global/homes/b/bxc/.conda/envs/dm-play/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/global/u1/b/bxc/dm/parsl/parsl/dataflow/flow_control.py", line 119, in _wake_up_timer
    self.make_callback(kind='timer')
  File "/global/u1/b/bxc/dm/parsl/parsl/dataflow/flow_control.py", line 139, in make_callback
    self.callback(tasks=self._event_buffer, kind=kind)
  File "/global/u1/b/bxc/dm/parsl/parsl/dataflow/strategy.py", line 260, in _strategy_simple
    executor.scale_out(excess_blocks)
  File "/global/u1/b/bxc/dm/parsl/parsl/executors/high_throughput/executor.py", line 564, in scale_out
    internal_block = self.provider.submit(launch_cmd, 1)
  File "/global/u1/b/bxc/dm/parsl/parsl/providers/slurm/slurm.py", line 212, in submit
    retcode, stdout, stderr = self.execute_wait("sbatch {0}".format(channel_script_path))
  File "/global/u1/b/bxc/dm/parsl/parsl/providers/cluster_provider.py", line 86, in execute_wait
    return self.channel.execute_wait(cmd, t)
  File "/global/u1/b/bxc/dm/parsl/parsl/channels/local/local.py", line 70, in execute_wait
    proc.wait(timeout=walltime)
  File "/global/homes/b/bxc/.conda/envs/dm-play/lib/python3.7/subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "/global/homes/b/bxc/.conda/envs/dm-play/lib/python3.7/subprocess.py", line 1616, in _wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command 'sbatch /global/u1/b/bxc/dm/parsl/runinfo_45uj53m/000/submit_scripts/parsl.auto.1567095657.8399532.submit' timed out after 10 seconds
```

**Comment by benclifford** [comment]
cc @TomGlanzman

**Comment by benclifford** [comment]
#1242 and #1244 have been merged.
