### ISSUE TITLE
Monitoring does not survive full test suite

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1267]
When running the pytest suite with local executor with this clause added, I get a hang at the end of tests (after the test summary is printed) in Travis, although the same test works for me on my laptop. This clause is also the commented out clause added in PR #1261 

```  monitoring=MonitoringHub(
￼                    hub_address="localhost",
                    hub_port=55055,
                    logging_level=logging.INFO,
                    resource_monitoring_interval=1,
                )
```

My guess is a race condition in monitoring shutdown.

**Comment by annawoodard** [comment]
One requirement for considering this issue fixed is that the original monitoring clause in PR #1261 is re-introduced and CI passes.

**Comment by benclifford** [comment]
@TomGlanzman has seen a monitoring related hang at shutdown, with PR #1367. Here's the stack trace after pressing ctrl-C:

```
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19-dev/python/miniconda3-4.5.12/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
Process Monitoring-DBM-Process:
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19-dev/python/miniconda3-4.5.12/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19-dev/python/miniconda3-4.5.12/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/global/homes/d/descdm/.local/lib/python3.7/site-packages/parsl/monitoring/db_manager.py", line 451, in dbm_starter
    dbm.start(priority_msgs, node_msgs, resource_msgs)
  File "/global/homes/d/descdm/.local/lib/python3.7/site-packages/parsl/monitoring/db_manager.py", line 327, in start
    threshold=self.batching_threshold)
  File "/global/homes/d/descdm/.local/lib/python3.7/site-packages/parsl/monitoring/db_manager.py", line 395, in _get_messages_in_batch
    x = msg_queue.get(timeout=0.1)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19-dev/python/miniconda3-4.5.12/lib/python3.7/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19-dev/python/miniconda3-4.5.12/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
```

**Comment by benclifford** [comment]
I've been able to recreate this on my laptop in my Python 3.5 environment but not in my Python 3.7 environment. That mirrors what I have seen with PR #1472 with a failure in 3.5 but not 3.7.

The hangs on my laptop appear to relate to the `priority_msgs` queue.

If I remove `priority_msgs.put((msg, 0))` from the loop in `Hub.start` then the hang does not happen (but those messages are instead discarded)

If I put a debug message at the end of `Hub.start` to show how many messages are in the queue (without removing that `put`), I can see that there can be a few hundred messages. However, nothing will remove the messages from the queue (because the DB manager has shut down by then) and so this process will hang at exit waiting for the messages to be processed.

This behaviour can be disabled: if I put `priority_msgs.cancel_join_thread()` at the start of `Hub.start`, then the Hub process will not wait for these message, and the hang does not happen; and the unprocessed messages are instead discarded.

Maybe the database manager needs to stay alive until after the hub loop has processed all messages and put them in queues - there are several queues and this deadlock might happen with any of them (in the absence of further reasoning why not)

I'll keep looking at this.

**Comment by ZhuozhaoLi** [comment]
Based on the discussions on slack with @benclifford , the things to fix are:

1. for every kwarg, check if it is a tuple
2. Try catch every insert/update in dbm
3. wrap the starter process with logging

**Comment by benclifford** [comment]
As of #1472, monitoring has been running in CI as part of the htex alternate configuration. That hasn't been causing trouble since it was merged 5 weeks ago, so I'm closing this issue.
