### ISSUE TITLE
Handle case where `stdout=None` when calling `qstat` in TorqueProvider._status

### ISSUE THREAD

**Issue by ravihansa3000** [Parsl/parsl#1289]
When shell command `qstat <list of job ids>` fails due to timeout, the returned stdout, stderr will be None causing a `AttributeError: 'NoneType' ` Exception while trying to parse the stdout.

Solution: NoneType case should be handled by first checking whether `stdout is not None` and `stderr is not None`

```
2019-09-17 03:57:23 parsl.dataflow.strategy:204 [DEBUG]  Executor htex has 1 active tasks, 0/0/1 running/submitted/pending blocks, and 8 connected workers
Caught exception: Command 'qstat 8972700.wlm01 8973036.wlm01 8973047.wlm01 8973173.wlm01 8973640.wlm01 8973649.wlm01 8973674.wlm01 8973692.wlm01 8973750.wlm01 8973774.wlm01' timed out after 120 seconds
2019-09-17 03:59:23 parsl.channels.local.local:77 [WARNING]  Execution of command [qstat 8972700.wlm01 8973036.wlm01 8973047.wlm01 8973173.wlm01 8973640.wlm01 8973649.wlm01 8973674.wlm01 8973692.wlm01 8973750.wl
m01 8973774.wlm01] failed due to
 Command 'qstat 8972700.wlm01 8973036.wlm01 8973047.wlm01 8973173.wlm01 8973640.wlm01 8973649.wlm01 8973674.wlm01 8973692.wlm01 8973750.wlm01 8973774.wlm01' timed out after 120 seconds
Exception in thread Thread-2:
Traceback (most recent call last):  
  File "/home/users/nus/csipav/anaconda3/envs/gdc/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/users/nus/csipav/anaconda3/envs/gdc/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/users/nus/csipav/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl/dataflow/flow_control.py", line 119, in _wake_up_timer
    self.make_callback(kind='timer')
  File "/home/users/nus/csipav/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl/dataflow/flow_control.py", line 139, in make_callback
    self.callback(tasks=self._event_buffer, kind=kind)
  File "/home/users/nus/csipav/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl/dataflow/strategy.py", line 177, in _strategy_simple
    status = executor.status()
  File "/home/users/nus/csipav/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl/executors/high_throughput/executor.py", line 600, in status
    status = self.provider.status(self.blocks.values())
  File "/home/users/nus/csipav/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl/providers/cluster_provider.py", line 167, in status
    self._status()
  File "/home/users/nus/csipav/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl/providers/torque/torque.py", line 118, in _status
    for line in stdout.split('\n'): 
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by ravihansa3000** [comment]
https://github.com/Parsl/parsl/blob/665bb9db66d60e5c7b15a6269678a587b4115fd4/parsl/providers/torque/torque.py#L118
