### ISSUE TITLE
Ad Hoc Cluster configuration not working on Beowulf cluster

### ISSUE THREAD

**Issue by rajiniw95** [Parsl/parsl#1475]
**Describe the bug**
I built a Beowulf cluster and tried configuring it as an ad hoc cluster, following parsl instructions. However, when I ran the python-parsl program, it returned the following error. 

```console
Traceback (most recent call last):
  File "/home/mpiuser/.local/lib/python3.5/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/mpiuser/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mpiuser/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/mpiuser/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/mpiuser/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/mpiuser/.local/lib/python3.5/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/home/mpiuser/.local/lib/python3.5/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f21ee8216d8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mpiuser/.local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/mpiuser/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/mpiuser/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f21ee8216d8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parallel_wf.py", line 12, in <module>
    from remote_htex import remote_htex
  File "/home/mpiuser/Downloads/parallel-parsl-workflow/remote_htex.py", line 23, in <module>
    address=address_by_query(),
  File "/home/mpiuser/.local/lib/python3.5/site-packages/parsl/addresses.py", line 21, in address_by_query
    addr = requests.get('https://api.ipify.org').text
  File "/home/mpiuser/.local/lib/python3.5/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mpiuser/.local/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mpiuser/.local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mpiuser/.local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/mpiuser/.local/lib/python3.5/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f21ee8216d8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) 
```
**To Reproduce**
Steps to reproduce the behavior, for e.g:
1. Setup Parsl 0.9.0 with Python 3.5.2 on a beowulf cluster
2. Run a parsl-python script
3. Wait 

**Expected behavior**
Run correctly, in lesser time, without generating the following error.
```console
/home/mpiuser/Downloads//home/mpiuser/Downloads/parallel-parsl-workflow//parsl.auto.1575015988.2083118.sh: line 2: process_worker_pool.py: command not found
```
**Environment**
 - ubuntu 16.04
 - Python 3.5.2
 - Parsl 0.9.0

**Distributed Environment**
- Where are you running the Parsl script from ? Login node
- Where do you need the workers to run ? Login node and Compute nodes

**Comment by benclifford** [comment]
Those errors are coming from parsl trying to guess IP addresses to use for your submitting node. You can override that behaviour and specify an address explicitly by using the `address` parameter to the HighThroughputExecutor constructor.

Find out what the IP address of your submit node that can be used to connect from your worker nodes, and then configure that address in parsl: `Config(...HighThroughputExecutor(address=IP_ADDRESS...`

**Comment by benclifford** [comment]
What does your program do after this error appears? Does it exit? or does it hang?

**Comment by rajiniw95** [comment]
It exits.

**Comment by rajiniw95** [comment]
We did try with the ip addresses. Our configuration for a two node cluster is as follows. We want both nodes to be computer nodes.   

```console
remote_htex = Config(
    executors=[
	
        HighThroughputExecutor(
            label='remote_htex',
	    address = '127.0.0.1',
            max_workers=2,
            #address=address_by_query(),
            worker_logdir_root=user_opts['adhoc']['script_dir'],
            provider=AdHocProvider(
                # Command to be run before starting a worker, such as:
                # 'module load Anaconda; source activate parsl_env'.
                worker_init='',
                channels=[SSHChannel(hostname=m,
                                     username=user_opts['adhoc']['username'],
                                     script_dir=user_opts['adhoc']['script_dir'],
                ) for m in user_opts['adhoc']['remote_hostnames']]
            )
        )
    ],
    max_idletime=2.0,
    strategy=None,
)
```

**Comment by rajiniw95** [comment]
We did try with the ip addresses. Our configuration for a two node cluster is as follows. We want both nodes to be computer nodes.

```console
import parsl
from parsl.config import Config
from parsl.providers import AdHocProvider
from parsl.channels import SSHChannel
from parsl.executors import HighThroughputExecutor
from parsl.addresses import address_by_query

user_opts = {'adhoc':
             {'username': 'mpiuser',
              'script_dir': '/home/mpiuser/Downloads/TravellingSalesmanProblem-master/PSO-GA/',
              'remote_hostnames': ['10.0.0.2']
             }
}

remote_htex = Config(
    executors=[
	
        HighThroughputExecutor(
            label='remote_htex',
	    address = '127.0.0.1',
            max_workers=2,
            #address=address_by_query(),
            worker_logdir_root=user_opts['adhoc']['script_dir'],
            provider=AdHocProvider(
                # Command to be run before starting a worker, such as:
                # 'module load Anaconda; source activate parsl_env'.
                worker_init='',
                channels=[SSHChannel(hostname=m,
                                     username=user_opts['adhoc']['username'],
                                     script_dir=user_opts['adhoc']['script_dir'],
                ) for m in user_opts['adhoc']['remote_hostnames']]
            )
        )
    ],
    max_idletime=2.0,
    #  AdHoc Clusters should not be setup with scaling strategy.
    strategy=None,
)
```

**Comment by benclifford** [comment]
OK. `address_by_query` isn't working in your setup - perhaps because you do not have DNS set up configured.

There are several different helper functions that you can use, or you can specify the IP address explicitly as a string there. In your case, it is probably best to specify it explicitly.

**Comment by rajiniw95** [comment]
We attempted specifying the addressed as well. (10.0.0.1 corresponds to the master node)
```console 
address='10.0.0.1',
```
However, this did not give the intended result as well.

**Comment by benclifford** [comment]
OK. Stick with specifying the address manually. What error do you get then?

**Comment by rajiniw95** [comment]
parsl.auto.1575015988.2083118.sh.out 

```console
/home/mpiuser/Downloads//home/mpiuser/Downloads/parallel-parsl-workflow//parsl.auto.1575015988.2083118.sh: line 2: process_worker_pool.py: command not found
```

The above error is printed in the parsl.auto.1575015988.2083118.sh.out file.

The program doesn't exit. It hangs after this.

**Comment by benclifford** [comment]
`process_worker_pool.py` is the parsl worker which will run your remote jobs - that error says that it can't be found (on the remote 10.0.0.2 machine, probably)

Do you have parsl installed on 10.0.0.2?

If so, do you need to run any commands to make it available when you log in? If so, put those commands in `worker_init` in your config.

**Comment by rajiniw95** [comment]
We built a two-node beowulf cluster. Parsl is installed on both nodes. We're not aware of any specific commands required to make the node available.

**Comment by benclifford** [comment]
OK. if you log into 10.0.0.2, and type:
```
which process_worker_pool.py
```
what do you get as a response?

And,

```
$ python
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import parsl
>>> parsl
...
```
What do you see then?

**Comment by rajiniw95** [comment]
The responses are as follows; 
```console
/home/mpiuser/.local/bin/process_worker_pool.py
```

```console
<module 'parsl' from '/home/mpiuser/.local/lib/python3.5/site-packages/parsl/_init_.py'>
```

**Comment by benclifford** [comment]
OK. Those look good.

I have seen these symptoms before. The user environment is set up correctly when you ssh in with a command line, but not when parsl SSHes in to run the process worker.

**Comment by benclifford** [comment]
Try setting this parameter in your parsl config (in place of the existing `worker_init=''`). It is an attempt to replicate what happens when you do a normal SSH.

```
worker_init="""
source /etc/profile
source ~/.profile
"""
```

**Comment by rajiniw95** [comment]
It works!!! I used the worker_init config you mentioned. 

Thank you!
