### ISSUE TITLE
Invalid reference to queue.Empty causing an unhandled exception when monitoring is enabled

### ISSUE THREAD

**Issue by ravihansa3000** [Parsl/parsl#1483]
**Describe the bug**
An exception is raised while handling another exception when monitoring is enabled.

----------
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/csipav/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl-0.9.0-py3.7.egg/parsl/monitoring/monitoring.py", line 537, in monitor
    msg = command_q.get(block=False)
  File "/home/csipav/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl-0.9.0-py3.7.egg/parsl/monitoring/monitoring.py", line 537, in monitor
    msg = command_q.get(block=False)
2019-12-03 04:11:28 parsl.app.futures:56 [WARNING]  DataFuture constructed with a string, not a File. This is deprecated.
  File "/home/csipav/anaconda3/envs/gdc/lib/python3.7/multiprocessing/queues.py", line 107, in get
    raise Empty
  File "/home/csipav/anaconda3/envs/gdc/lib/python3.7/multiprocessing/queues.py", line 107, in get
    raise Empty
_queue.Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

During handling of the above exception, another exception occurred:

  File "/home/csipav/anaconda3/envs/gdc/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/csipav/anaconda3/envs/gdc/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
2019-12-03 04:11:28 parsl.app.futures:72 [DEBUG]  Creating DataFuture with parent: <AppFuture super=<AppFuture at 0x7f09cc9b8d10 state=pending>> and file: <<class 'parsl.data_provider.files.File'> at 0x7f09cc9b8e50 url=/opt/GDC-Pipeline-Output/TCGA_OV_0/TCGA-04-1332/4/annotations/somatic.indels.vcf scheme=file netloc= path=/opt/GDC-Pipeline-Output/TCGA_OV_0/TCGA-04-1332/4/annotations/somatic.indels.vcf filename=somatic.indels.vcf>
  File "/home/csipav/anaconda3/envs/gdc/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/csipav/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl-0.9.0-py3.7.egg/parsl/monitoring/monitoring.py", line 541, in monitor
    except Queue.empty:
  File "/home/csipav/anaconda3/envs/gdc/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
2019-12-03 04:11:28 parsl.dataflow.dflow:726 [INFO]  Task 21 submitted for App annotatate_vep, waiting on tasks [20]
  File "/home/csipav/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl-0.9.0-py3.7.egg/parsl/monitoring/monitoring.py", line 541, in monitor
    except Queue.empty:
AttributeError: 'function' object has no attribute 'empty'
AttributeError: 'function' object has no attribute 'empty'

---------

**To Reproduce**
Steps to reproduce the behavior, for e.g:
1. Setup Parsl master (commit: e52cbfbbe9615c0a89d02678790864e71e4526b6) with Python 3.7 on cluster
2. Run a test script with monitoring enabled

**Expected behavior**
The exception should have been handled without raising further exceptions.

**Environment**
 - OS: Ubuntu 18.04 server
 - Python version: 3.7
 - Parsl version: master (commit: e52cbfbbe9615c0a89d02678790864e71e4526b6)

**Distributed Environment**
Laptop: standalone

**Comment by benclifford** [comment]
fixed by #1482

**Comment by ZhuozhaoLi** [comment]
Fixed.  Closing.
