### ISSUE TITLE
Error when monitoring and checkpointing enabled - unknown type for memoization

### ISSUE THREAD

**Issue by ravihansa3000** [Parsl/parsl#1603]
**Describe the bug**
Memoization error is thrown after a Parsl task is complete and dependent tasks are not executed.

```
2020-03-11 17:48:27.460 parsl.dataflow.strategy:205 [DEBUG]  Executor htex has 2 active tasks, 0/12 running/pending blocks, and 20 connected workers
2020-03-11 17:48:30.746 parsl.dataflow.dflow:304 [INFO]  Task 5 completed
2020-03-11 17:48:30.747 parsl.dataflow.dflow:308 [INFO]  Standard output for task 5 available at /home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/TCRB_1/runinfo/000/task_logs/0000/task_0005_sort_bam_by_queryname_case_001.stdout
2020-03-11 17:48:30.747 parsl.dataflow.dflow:310 [INFO]  Standard error for task 5 available at /home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/TCRB_1/runinfo/000/task_logs/0000/task_0005_sort_bam_by_queryname_case_001.stderr
2020-03-11 17:48:30.747 parsl.monitoring.monitoring:261 [DEBUG]  Sending message MessageType.TASK_INFO, {'task_func_name': 'sort_bam_by_queryname', 'task_fn_hash': 'ee118c3ed74c3cb1da311131d1f17635', 'task_memoize': True, 'task_hashsum': '42ebbcc49bf9fddfb42752f643d1381f', 'task_fail_count': 0, 'task_status': <States.done: 3>, 'task_id': 5, 'task_time_submitted': datetime.datetime(2020, 3, 11, 16, 49, 32, 20705), 'task_time_returned': datetime.datetime(2020, 3, 11, 17, 48, 30, 746975), 'task_executor': 'htex', 'run_id': '69561608-bf41-4daf-a688-c9d55a3d9315', 'timestamp': datetime.datetime(2020, 3, 11, 17, 48, 30, 747492), 'task_status_name': 'done', 'tasks_failed_count': 0, 'tasks_completed_count': 1, 'task_inputs': 'None', 'task_outputs': "['/home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/TCRB_1/case_001/TCRBOA1-N-WEX/sorted/TCRBOA1-N-WEXsorted.bam']", 'task_stdin': None, 'task_stdout': '/home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/TCRB_1/runinfo/000/task_logs/0000/task_0005_sort_bam_by_queryname_case_001.stdout', 'task_stderr': '/home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/TCRB_1/runinfo/000/task_logs/0000/task_0005_sort_bam_by_queryname_case_001.stderr', 'task_fail_history': '', 'task_depends': '', 'task_elapsed_time': 3538.72627, 'task_fail_mode': 'lazy'}
2020-03-11 17:48:30.748 parsl.dataflow.memoization:159 [DEBUG]  Ignoring these kwargs for checkpointing: []
2020-03-11 17:48:30.755 parsl.dataflow.memoization:39 [ERROR]  id_for_memo attempted on unknown type <class 'parsl.data_provider.files.File'>
2020-03-11 17:48:30.756 concurrent.futures:326 [ERROR]  exception calling callback for <DataFuture at 0x2aaab845d550 state=finished with file <<class 'parsl.data_provider.files.File'> at 0x2aaab845d990 url=/home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/TCRB_1/case_001/TCRBOA1-N-WEX/sorted/TCRBOA1-N-WEXsorted.bam scheme=file netloc= path=/home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/TCRB_1/case_001/TCRBOA1-N-WEX/sorted/TCRBOA1-N-WEXsorted.bam filename=TCRBOA1-N-WEXsorted.bam>>
Traceback (most recent call last):
  File "/home/users/nus/e0503495/anaconda3/envs/gdc/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/home/users/nus/e0503495/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl-0.9.0-py3.7.egg/parsl/dataflow/dflow.py", line 787, in callback_adapter
    self.launch_if_ready(task_id)
  File "/home/users/nus/e0503495/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl-0.9.0-py3.7.egg/parsl/dataflow/dflow.py", line 419, in launch_if_ready
    task_id, task_record['func'], *new_args, **kwargs)
  File "/home/users/nus/e0503495/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl-0.9.0-py3.7.egg/parsl/dataflow/dflow.py", line 470, in launch_task
    hit, memo_fu = self.memoizer.check_memo(task_id, self.tasks[task_id])
  File "/home/users/nus/e0503495/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl-0.9.0-py3.7.egg/parsl/dataflow/memoization.py", line 201, in check_memo
    hashsum = self.make_hash(task)
  File "/home/users/nus/e0503495/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl-0.9.0-py3.7.egg/parsl/dataflow/memoization.py", line 173, in make_hash
    id_for_memo(task['args'])]
  File "/home/users/nus/e0503495/anaconda3/envs/gdc/lib/python3.7/functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/users/nus/e0503495/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl-0.9.0-py3.7.egg/parsl/dataflow/memoization.py", line 60, in id_for_memo_list
    normalized_list.append(id_for_memo(e, output_ref=output_ref))
  File "/home/users/nus/e0503495/anaconda3/envs/gdc/lib/python3.7/functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/users/nus/e0503495/anaconda3/envs/gdc/lib/python3.7/site-packages/parsl-0.9.0-py3.7.egg/parsl/dataflow/memoization.py", line 40, in id_for_memo
    raise ValueError("unknown type for memoization: {}".format(type(obj)))
ValueError: unknown type for memoization: <class 'parsl.data_provider.files.File'>
2020-03-11 17:48:30.797 parsl.dataflow.dflow:1017 [DEBUG]  Task 5 checkpointed
2020-03-11 17:48:30.798 parsl.dataflow.dflow:1027 [INFO]  Done checkpointing 1 tasks
```

**To Reproduce**
 - Enable Parsl monitoring and checkpointing

**Expected behavior**
No memoization errors. Dependent tasks should get executed.

**Environment**
 - OS: RHEL6.1
 - Python version: 3.7 (Anaconda 4.8.2)
 - Parsl version: master branch commit: 4fade9973733fba145d489c9fba05d4dfa78f4a4

**Distributed Environment**
- PBS Pro in NSCC's ASPIRE1

**Comment by ravihansa3000** [comment]
@annawoodard @ZhuozhaoLi

**Comment by benclifford** [comment]
This is intended, but I guess a bit surprising.

The way that checkpointing for different inputs types was changed a lot in PR #1291, and parsl will now only let you checkpoint with input parameters that it knows how to compare safely across runs.

By default, that is: str, int, float, functions, None, lists and dicts.

Notably that *doesn't* include the File type by default - when I implemented #1291 I could see several ways of checkpointing File objects. To get the old behaviour, add something like this near the start of your code:

from parsl.data_provider.files import File
from parsl.dataflow.memoization import id_for_memo
from parsl
@id_for_memo.register(File)
def id_for_memo_serialize(obj, output_ref=False):
    return serialize_object(obj)[0]

This will checkpoint based on the attributes of the File object, which should mean that a run with a File with a particular URL/filename will be regarded as the same across runs.

Another implementation I have used checkpoints based on the modification time and size of the named file, so that modifying that file stop checkpointing from re-using the result. That code is here:

```
@id_for_memo.register(File)
def id_for_memo_File(f, output_ref=False):
    if output_ref:
        logger.debug("hashing File as output ref without content: {}".format(f))
        return f.url
    else:
        logger.debug("hashing File as input with content: {}".format(f))
        assert f.scheme == "file"
        filename = f.filepath
        stat_result = os.stat(filename)

        return [f.url, stat_result.st_size, stat_result.st_mtime]
```

A third option would be to hash file content, but that's more expensive.

**Comment by benclifford** [comment]
> Error when monitoring and checkpointing enabled - unknown type for memoization #1603

This should be happening whether you have monitoring enabled or disabled

**Comment by ravihansa3000** [comment]
Thank you for the detailed explanation. I wonder why the default behavior (old way of checking File attributes) was not included. 

Moreover, it would have been helpful if this error was thrown at the beginning of the execution (if it detects unsupported types in any of the tasks)

**Comment by benclifford** [comment]
> it would have been helpful if this error was thrown at the beginning of the execution (if it detects unsupported types in any of the tasks)

In regular python, those types don't in general exist until all of the dependencies of a task are completed and have output their values.

**Comment by benclifford** [comment]
>  wonder why the default behavior (old way of checking File attributes) was not included.

Perhaps it should be - I'm open to persuasion. I'm not sure what the right way of checking Files (or other "external") types is.

**Comment by ravihansa3000** [comment]
Hi Ben,

For our specific workflow, an app should re-run only if the input file content has been changed (assuming app code hash has not changed). As you mentioned, it'd be more expensive but in our case only top-level apps are provided with large input files (~10-20GB). However, the downstream tasks will get smaller input files (~10MB).

I'd suggest this behavior to be configurable via app annotations. IMO, each app has different input File checking expectations depending on the app logic. The default behavior could be set to attributes based checking (old way) because it doesn't care about the File location/protocol.

**Comment by benclifford** [comment]
> The default behavior could be set to attributes based checking (old way) because it doesn't care about the File location/protocol.

The old way of checking File object attributes *does* memoize based on location/protocol - the whole URL/path used to construct a File object is used for memoization comparisons.

**Comment by ravihansa3000** [comment]
Yes, indeed. What I meant was it works regardless of the underlying location/protocol.
