### ISSUE TITLE
interchange removes task that is not in task list

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1657]
**Describe the bug**
@TomGlanzman encountered this exception on the lsst-dm-202002 branch when running on cori at scale. We have not tried to reproduce. I am investigating this but logging here.

```
2020-04-21 10:25:41 parsl.dataflow.strategy:199 [DEBUG]  Executor batch-1 has 518 active tasks, 1/0 running/pending blocks, and 540 connected workers
Process HTEX-Interchange:
Traceback (most recent call last):
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/parsl/executors/high_throughput/interchange.py", line 564, in starter
    ic.start()
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/parsl/executors/high_throughput/interchange.py", line 494, in start
    self._ready_manager_queue[manager]['tasks'].remove(r['task_id'])
ValueError: list.remove(x): x not in list
```

**Comment by benclifford** [comment]
This has happened on a subsequent run.

**Comment by benclifford** [comment]
When a manager dies, the interchange removes that manager record from `_ready_manager_queue`.

If subequently a message is processed from that manager, an empty manager record is created. The message processing code assumes that the manager record is the original manager record, not the new empty one, giving this exception.

I think this is what is happening in my situation as the exceptions have both times come a few minutes after a slurm block has ended.

This existing test almost deals with this, but does not because being in _ready_manager_queue is not a test of being registered.

```
                if manager not in self._ready_manager_queue:
                    logger.warning("[MAIN] Received a result from a un-registered manager: {}".format(manager))
```

**Comment by benclifford** [comment]
I am testing a workaround in production to ignore this exception.

**Comment by benclifford** [comment]
PR #1665 should fix this
