### ISSUE TITLE
AWS provider (and maybe GCS provider) does not report job state

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1733]
**Describe the bug**
When using the AWS provider, this error happens with every job status poller loop:

```
2020-06-01 13:40:16.122 parsl.dataflow.task_status_poller:62 [DEBUG]  Polling
2020-06-01 13:40:16.126 parsl.dataflow.flow_control:114 [ERROR]  Flow control callback threw an exception - logging and proceeding anyway
Traceback (most recent call last):
  File "/home/benc/parsl/src/parsl/parsl/dataflow/flow_control.py", line 112, in make_callback
    self.callback(tasks=self._event_buffer, kind=kind)
  File "/home/benc/parsl/src/parsl/parsl/dataflow/task_status_poller.py", line 64, in poll
    self._strategy.strategize(self._poll_items, tasks)
  File "/home/benc/parsl/src/parsl/parsl/dataflow/strategy.py", line 198, in _strategy_simple
    running = sum([1 for x in status.values() if x.state == JobState.RUNNING])
  File "/home/benc/parsl/src/parsl/parsl/dataflow/strategy.py", line 198, in <listcomp>
    running = sum([1 for x in status.values() if x.state == JobState.RUNNING])
AttributeError: 'JobState' object has no attribute 'state'
```

It looks like this arises from the AWS provider `.status` method returning incorrect values. This type annotation reveals that with `make mypy`:

```
 -    def status(self, job_ids):
 +    def status(self, job_ids) -> List[JobStatus]:
```

I think this was probably introduced by the work around PR #1493 which rearranged job status representation.

**To Reproduce**
parsl master 7b1c4594582773cf701f7c0096956a87375acdf5
set some arbitrary config for ec2 testing in parsl/tests/configs/local_user_opts.py:
```
   'ec2': {
        'image_id': "ami-0e63f5af5130c9681",
        'region': "eu-west-2",
        'key_name': "aws-cqx-eu-west-2"
    }
```

> pytest parsl --config parsl/tests/configs/ec2_single_node.py

This will hang, but the runinfo_*/000/parsl.log file should now be showing the above exception stack trace.

It looks likely that this problem will also happen with the `googlecloud` provider: add the same status type annotation gives the same mypy error.

**Environment**
my laptop, python 3.7

**Comment by youssefavx** [comment]
Hey guys I don't know if this is the same error or not but trying this on my Macbook 15" Retina MacOS Mojave Python 3.7 set up, I get this error. 

Now, when I then run another function in parallel (not using Parsl, using threading), after it it runs fine. But right after that function, the rest of the code for some reason doesn't do anything. 

It just keeps spitting out this error and the program does not seem to progress to the next line:
`DEBUG:parsl.dataflow.task_status_poller:Polling`

This is my code, I'm using twint to download (out of a list of twitter users) who each one is following: 

```
import parsl
from parsl import python_app

parsl.load()
import twint
users= ['MLevitt_NP2013', 'Iearnsomethlng', 'wintonARK', 'TashaARK', 'archillect', 'skorusARK', 'neiltyson', 'SciGuySpace', 'wlopwangling', 'Berger_SN', 'Jon_Favreau', 'NatGeo',  'NASAJPL', 'Space_Station', 'medical_xpress', 'SouthPark', 'HistoryInPics', 'NASA', 'developonline', 'TheHackersNews', 'xkcdComic', 'atlasobscura']


@python_app
def followingcount(fcount):
    print("Checking following count for: " + str(fcount))

    users_list = []
    c = twint.Config()
    c.Username = fcount
    c.Store_object = True
    c.Store_object_users_list = users_list

    while True:
        try:
            twint.run.Lookup(c)
            followingnumber = users_list[0].following
            #dictofusersandfollowingcounts.update({fcount:followingnumber})
            return {fcount:followingnumber}
            break
        except aiohttp.ClientConnectorError:
            print('Cant connect to internet. Retrying in 2 seconds...')
            time.sleep(2)
        except aiohttp.ClientOSError:
            print('Cant connect to internet. Retrying in 2 seconds...')

            time.sleep(2)
        except aiohttp.ServerDisconnectedError:
            print('Cant connect to internet. Retrying in 2 seconds...')
            time.sleep(2)
        except asyncio.TimeoutError:
            print('Cant connect to internet. Retrying in 2 seconds...')
            time.sleep(2)

def getfollowingcounts(users):    
    dictofusersandfollowingcounts = []
    for user in users:
        dictofusersandfollowingcounts.append(followingcount(user))

    outputs = [r.result() for r in dictofusersandfollowingcounts]
    #outputs = [r.result() for r in dictofusersandfollowingcounts]
    newdict = {}
    for i in outputs:
        username = list(i.keys())[0]
        followingcount = list(i.values())[0]
        newdict.update({username:followingcount})
    return newdict
```

**Comment by youssefavx** [comment]
Sorry, never mind, I think this is a problem with the threading function I have rather than with parsl!
