### ISSUE TITLE
Parsl fails if there are unexpectedly named files in runinfo

### ISSUE THREAD

**Issue by danielskatz** [Parsl/parsl#1743]
Here's an example where I tgz'd a dir, but didn't delete that new file, then tried to run Parsl:

Traceback (most recent call last):
  File "parsl_basic.py", line 97, in <module>
    parsl.load(bw_config)
  File "/u/sciteam/dsk/.local/lib/python3.6/site-packages/typeguard/__init__.py", line 840, in wrapper
    retval = func(*args, **kwargs)
  File "/u/sciteam/dsk/.local/lib/python3.6/site-packages/parsl/dataflow/dflow.py", line 1150, in load
    cls._dfk = DataFlowKernel(config)
  File "/u/sciteam/dsk/.local/lib/python3.6/site-packages/parsl/dataflow/dflow.py", line 77, in __init__
    self.run_dir = make_rundir(config.run_dir)
  File "/u/sciteam/dsk/.local/lib/python3.6/site-packages/parsl/dataflow/rundirs.py", line 32, in make_rundir
    x = sorted([int(os.path.basename(x)) for x in prev_rundirs])[-1]
  File "/u/sciteam/dsk/.local/lib/python3.6/site-packages/parsl/dataflow/rundirs.py", line 32, in <listcomp>
    x = sorted([int(os.path.basename(x)) for x in prev_rundirs])[-1]
ValueError: invalid literal for int() with base 10: '002.tar.gz'

**Comment by yadudoc** [comment]
Closed by #1752

**Comment by benclifford** [comment]
#1752 probably won't catch  `000.tar.bz2`
