### ISSUE TITLE
[htex auto scale] RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by ravihansa3000** [Parsl/parsl#1862]
**Describe the bug**
A RuntimeError exception is thrown (stack trace below) while running a workflow based on Parsl.

```
2020-09-10 00:15:14 parsl.dataflow.dflow:509 [INFO]  Task 0 launched on executor medium
2020-09-10 00:15:14 workflow:68 [INFO]  Waiting for validation task to complete...
2020-09-10 00:15:17 parsl.providers.torque.torque:128 [DEBUG]  coerced job_id 1838438.wlm01 -> 1838438.wlm01
2020-09-10 00:15:17 parsl.dataflow.strategy:332 [DEBUG]  Executor medium has 0 active tasks, 0/1 running/pending blocks, and 0 connected workers
2020-09-10 00:15:17 parsl.dataflow.flow_control:114 [ERROR]  Flow control callback threw an exception - logging and proceeding anyway
Traceback (most recent call last):
  File "/home/akila/Documents/NUS_CSI/Parsl/parsl.git/parsl/dataflow/flow_control.py", line 112, in make_callback
    self.callback(tasks=self._event_buffer, kind=kind)
  File "/home/akila/Documents/NUS_CSI/Parsl/parsl.git/parsl/dataflow/task_status_poller.py", line 66, in poll
    self._strategy.strategize(self._poll_items, tasks)
  File "/home/akila/Documents/NUS_CSI/Parsl/parsl.git/parsl/dataflow/strategy.py", line 302, in _strategy_htex_auto_scale
    for label, executor in self.dfk.executors.items():
RuntimeError: dictionary changed size during iteration
2020-09-10 00:15:22 parsl.providers.torque.torque:128 [DEBUG]  coerced job_id 1838438.wlm01 -> 1838438.wlm01
```

This is similar to the issue reported in #1606 which occurred intermittently when using `strategy='simple'`
The same fix should be done for `htex_auto_scale` which was introduced in #1563

**To Reproduce**
1. Setup Parsl with master branch commit: 5445f90
2. Enable checkpointing and monitoring
3. Set `strategy='htex_auto_scale'` in Parsl config
4. Execute a simple workflow (multiple bash_apps and python_apps chained together)

**Expected behavior**
No RuntimeError exceptions.

**Environment**
OS: RHEL6.1
Python version: 3.7 (Anaconda 4.8.2)
Parsl version: master branch commit: 5445f90

**Distributed Environment**
PBS Pro in NSCC's ASPIRE1

**Comment by ravihansa3000** [comment]
@benclifford perhaps we should add a test case to uncover this race condition

**Comment by benclifford** [comment]
ideally i think those two strategies should share more code because they don't do very much different from each other.
