### ISSUE TITLE
Is Parsl on Windows supported?

### ISSUE THREAD

**Issue by bilke** [Parsl/parsl#1878]
Is Parsl supported on Windows?

**To Reproduce**
Run a simple Parsl workflow (e.g. the one the [Quickstart-guide](https://parsl.readthedocs.io/en/stable/quickstart.html#getting-started)) on Windows:

```
....\.venv\lib\site-packages\parsl\addresses.py", line 14, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

The module `fcntl` [exists on Linux only](https://docs.python.org/3.7/library/fcntl.html).

**Environment**
 - OS: windows
 - Python version 3.7
 - Parsl version 1.0.0

**Comment by benclifford** [comment]
I don't think we can put much effort into supporting Windows. If you're encountering bugs as simple as this, it sounds like no one has cared enough in the past to report this.

I think there will be a bunch of small things like this bug which should be straightforward to fix if you wanted to: nothing in parsl.addresses is strictly required to use parsl, as all that is in there is address autodetection code.

However, there are more serious problems that I can imagine, for example, the high throughput executor being able to run on Windows, because of the way it uses `multiprocessing`. (see https://github.com/Parsl/parsl/issues/1659)

**Comment by bilke** [comment]
Thank you Ben for the response. I perfectly understand that Windows is not an OS you target. But maybe this should be stated somewhere that Windows is simply not supported.

**Comment by jonoharms** [comment]
When importing on windows, I get the error:

>>> import parsl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Applications\Anaconda3\envs\py310\lib\site-packages\parsl\__init__.py", line 22, in <module>
    from parsl.app.app import bash_app, join_app, python_app
  File "C:\Applications\Anaconda3\envs\py310\lib\site-packages\parsl\app\app.py", line 12, in <module>
    from parsl.dataflow.dflow import DataFlowKernel
  File "C:\Applications\Anaconda3\envs\py310\lib\site-packages\parsl\dataflow\dflow.py", line 23, in <module>
    from parsl.config import Config
  File "C:\Applications\Anaconda3\envs\py310\lib\site-packages\parsl\config.py", line 7, in <module>
    from parsl.executors.base import ParslExecutor
  File "C:\Applications\Anaconda3\envs\py310\lib\site-packages\parsl\executors\__init__.py", line 4, in <module>
    from parsl.executors.high_throughput.executor import HighThroughputExecutor
  File "C:\Applications\Anaconda3\envs\py310\lib\site-packages\parsl\executors\high_throughput\executor.py", line 16, in <module>
    from parsl.executors.high_throughput import interchange
  File "C:\Applications\Anaconda3\envs\py310\lib\site-packages\parsl\executors\high_throughput\interchange.py", line 21, in <module>
    from parsl.monitoring.message_type import MessageType
  File "C:\Applications\Anaconda3\envs\py310\lib\site-packages\parsl\monitoring\__init__.py", line 1, in <module>
    from parsl.monitoring.monitoring import MonitoringHub
  File "C:\Applications\Anaconda3\envs\py310\lib\site-packages\parsl\monitoring\monitoring.py", line 12, in <module>
    from parsl.multiprocessing import ForkProcess, SizedQueue
  File "C:\Applications\Anaconda3\envs\py310\lib\site-packages\parsl\multiprocessing.py", line 15, in <module>
    ForkProcess: Type = multiprocessing.get_context('fork').Process
  File "C:\Applications\Anaconda3\envs\py310\lib\multiprocessing\context.py", line 239, in get_context
    return super().get_context(method)
  File "C:\Applications\Anaconda3\envs\py310\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'

**Environment:**

OS: Windows 10
Python: 3.10
parsl: 1.2.0

**Comment by TummyPan** [comment]
Would it be possible to have a version of Parsl supported on Windows? My team is developing a plugin for CellProfiler 4.2.1 which requires the function to connect to a cluster from a local Windows machine. Many thanks.

**Environment**:
OS: Windows 10
Python: 3.8
parsl: 1.1.0

**Comment by d33bs** [comment]
Wanted to share along that I'm also noticing a Windows-focused bug which results in an error message: `ValueError: cannot find context for 'fork'` (seemingly related to the later comments here and also in #2895). I wanted to seek clarification here as there's some ambiguity to whether Windows is supported or not by Parsl. Looking at the status of this issue as `open` and the work performed for #2107 made me think there might be a glimmer of hope yet for Windows support (even if disparate in behavior from other OS's).

Should we plan on Windows not being supported by Parsl? If so, should the docs and `setup.py` be updated accordingly (so as to alert developers ahead of time)? If not, would it make sense to reopen #2895 as a planned issue which might be resolved in the future?

**Comment by benclifford** [comment]
@d33bs there's not a lot of enthusiasm within the traditional set of parsl developers for supporting Windows, but that's mostly "this is not high priority" rather than "we shouldn't do this". There isn't anything in core Parsl that is tied to Unix, I think.

Something I'm working on at the moment is code maturity/support labelling at a feature level - see https://github.com/Parsl/parsl/issues/2554   In that context:

i) it would be interesting if someone outside of the traditional parsl developers wanted to be the tech sponsor for Windows (which is a somewhat ill defined role, but could be as little as making sure windows issues get documented properly)

ii) one attribute for code maturity of a feature in that context might be whether it works on the two not-Linux OSes that we encounter: OS X and Windows

So it might be interesting to at least get issues opened and tagged with a windows tag for everything that doesn't work.

For all the stuff that comes from `fork` not being supported on Windows: `fork` is bad in general in Python and I'd like that to disappear from Parsl completely. @rjmello has done some work towards that within htex and I hope that the other occurences will be replaced later on. So that should unlock more Windows functionality.

**Comment by d33bs** [comment]
Thanks @benclifford ! I completely understand, really appreciate the thorough information you provided here. Maybe the [GitHub Actions Windows Server images](https://github.com/actions/runner-images?tab=readme-ov-file#available-images) would be enough to build a test-driven approach on this topic. As a background for where I encountered the error, I first noticed this incompatibility when submitting a package to conda-forge which leverages Parsl as a dependency (the conda-forge Azure CI build failed for Windows, and as a workaround I skipped Windows tests for now). I'm unsure if/how the images between GitHub Actions and Azure align, but imagine these might overlap somewhat given Microsoft ownership.

Wondering aloud: what would the best possible workaround for Parsl users be in the meantime as `fork` is removed or replaced as a reference? Would it be best to leverage [WSL2](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) or perhaps Linux-based container images (unsure if the `fork` errors would persist there)?

**Comment by benclifford** [comment]
My gut feeling without any actual experience is that providing linux OS calls like fork is very much the sort of thing that WSL is intended to address. I suspect any of WSL1, WSL2 or Linux containers in a VM would work in that sense. I don't know how any of that integrates with other stuff you have/would want to have running in your Windows environment.

**Comment by benclifford** [comment]
@d33bs do you have any more info about what actually failed in that azure build?

**Comment by d33bs** [comment]
Sure thing @benclifford .  I believe this occurs on import of CytoTable on Windows, which leverages Parsl as a dependency. Here's the Azure Pipelines link: https://github.com/conda-forge/staged-recipes/runs/19759698684 (see the build recipe step). This was run as part of conda-forge/staged-recipes#24816 . It might align more with the error description of #2895 (`fork` and not `fcntl`).

**Comment by christopherwharrop-noaa** [comment]
FYI: I just ran into Windows compatibility issues when attempting to get my project uploaded to conda-forge.  I was attempting to make my project a noarch package but ran into issues on Windows when my code did `from parsl.config import Config` which eventually resulted in:

```
from multiprocessing.context import ForkProcess as ForkProcessType
ImportError: cannot import name 'ForkProcess' from 'multiprocessing.context'
```

I think the problem is that even though some effort was made to improve cross-platform multiprocessing, the multi-processing module still [calls](https://github.com/Parsl/parsl/blob/64aa5fdec0e14ba04341a2d9dc4e9d815cdbdab6/parsl/multiprocessing.py#L7-L8) both the POSIX and Windows style imports:

```
from multiprocessing.context import ForkProcess as ForkProcessType
from multiprocessing.context import SpawnProcess as SpawnProcessType
```
Just the act of importing `Config` caused the failure.

I am mostly just documenting here as it appears there is some interest in an ongoing discussion.  I don't know if there is a simple-ish way to avoid the problem by just wrapping the imports into a platform test:
```
import platform
if platform.system() != "Windows":
    from multiprocessing.context import ForkProcess as ForkProcessType
else:
    from multiprocessing.context import SpawnProcess as SpawnProcessType
```
I'm guessing my thinking there is very naive, and there would be additional downstream effects.  Plus it makes things ugly.

In any case, I have already made the decision to explicitly NOT support Windows in my project because the required effort exceeds the available resources to make it happen.  So, this post is for documentation/informational purposes in case others find it helpful.  I am not registering a complaint/request.
