### ISSUE TITLE
Fix stdout test in `test_ipp/python_app_examples.py`

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#188]
```
Traceback (most recent call last):
  File "test_ipp/python_app_examples.py", line 103, in <module>
    x = test_stdout()
  File "test_ipp/python_app_examples.py", line 84, in test_stdout
    assert f.read() == string, "String did not match output file"
AssertionError: String did not match output file
INFO:parsl.dataflow.dflow:DFK cleanup initiated
```

**Comment by annawoodard** [comment]
Fixed
