### ISSUE TITLE
Monitoring failed to capture FAILED blocks info in database

### ISSUE THREAD

**Issue by ZhuozhaoLi** [Parsl/parsl#1948]
**Describe the bug**

In PR #1877, we log block polling status in monitoring. However, as reported on slack, this incurs a new error when Parsl fails to request a new block due to some provider errors (e.g., job limit). 

```
2021-01-20 17:54:11.478 parsl.dataflow.flow_control:114 [ERROR]  Flow control callback threw an exception - logging and proceeding anyway
Traceback (most recent call last):
  File "/home1/05340/mcflynn/miniconda3/envs/sra_workflow/lib/python3.7/site-packages/parsl/dataflow/flow_control.py", line 112, in make_callback
    self.callback(tasks=self._event_buffer, kind=kind)
  File "/home1/05340/mcflynn/miniconda3/envs/sra_workflow/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 99, in poll
    self._update_state()
  File "/home1/05340/mcflynn/miniconda3/envs/sra_workflow/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 106, in _update_state
    item.poll(now)
  File "/home1/05340/mcflynn/miniconda3/envs/sra_workflow/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 46, in poll
    self.send_monitoring_info(self._status, block_id_type='internal')
  File "/home1/05340/mcflynn/miniconda3/envs/sra_workflow/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 52, in send_monitoring_info
    block_id_type=block_id_type)
  File "/home1/05340/mcflynn/miniconda3/envs/sra_workflow/lib/python3.7/site-packages/parsl/executors/high_throughput/executor.py", line 600, in create_monitoring_info
    d['block_id'] = self.removed_block_mapping.pop(id)
KeyError: '30'
```

After some investigations, this is not quite relevant with monitoring itself. Instead, this is because the block id type in HTEX is quite messy.

In https://github.com/Parsl/parsl/blob/bc51d0a6e2d61832e9501f81a302ff53b6c6c2c1/parsl/executors/status_handling.py#L68-L78, the returned status is a dict of the status of each block. For normal running blocks, their keys in the dict are INTERNAL block ids (e.g., job ids returned by batch scheduler). However, for failed blocks, they are stored in `self._simulated_blocks` and their keys in dict are EXTERNAL block ids (e.g., a block id counter inside HTEX). The mismatch of the id types between normal running blocks and failed blocks leads to the monitoring issue above.

To solve this issue, after discussing with @benclifford , there are three things to fix.

- [ ] Fix the block id types mismatch in the status and clean up the block id relevant code in HTEX. Probably need to rework the status method a bit and also rename different blocks id variables to make them easy to understand
- [ ] Minor monitoring code style fixes---`create_monitoring_info` should not involve removing any scale in blocks in dict  (i.e., removed_block_mapping). It should be removed at the same time as the other blocks, like completed blocks and failed blocks.
- [ ] Figure out a policy on when a block needs to be polled, returned in status, logged in monitoring. For example, a completed or failed block should be never polled again and should be only logged to monitoring once when after it failed or completed.

**To Reproduce**
1. Use a htex local config with monitoring enabled
2. Manually let local provider `return None` for `provider.submit` method
3. Run with any example and you will see the above error in `parsl.log`

**Expected behavior**
Monitoring should log those failed block status

**Environment**
 Parsl master

**Comment by benclifford** [comment]
I've verified that on my laptop #1952 fixes this.
