### ISSUE TITLE
Stack traces of remote exceptions raised by python_apps not are not printed in initial attempts

### ISSUE THREAD

**Issue by ravihansa3000** [Parsl/parsl#1982]
**Describe the bug**
Whenever a python_app throws an exception, it is not printed (stack trace) in the parsl.log during initial attempts. However, the stack trace can be seen during the final attempt

```
2021-02-27 19:46:16.893 parsl.dataflow.dflow:587 [INFO]  Task 3 launched on executor job_array
2021-02-27 19:46:16.893 parsl.dataflow.dflow:1244 [INFO]  Standard output for task 3 available at /home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/brca_mutsig_v2_analyze_batch_0/runinfo/000/task_logs/0000/task_0003_validate_contigs_app_a_2_1_1_tumor_contig_.stdout
2021-02-27 19:46:16.893 parsl.dataflow.dflow:1246 [INFO]  Standard error for task 3 available at /home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/brca_mutsig_v2_analyze_batch_0/runinfo/000/task_logs/0000/task_0003_validate_contigs_app_a_2_1_1_tumor_contig_.stderr
2021-02-27 19:46:17.066 parsl.app.errors:126 [DEBUG]  Reraising exception of type <class 'RuntimeError'>
2021-02-27 19:46:17.066 parsl.dataflow.dflow:289 [DEBUG]  Task 3 try 2 failed
2021-02-27 19:46:17.067 parsl.dataflow.dflow:313 [INFO]  Task 3 marked for retry
2021-02-27 19:46:17.067 parsl.dataflow.dflow:1244 [INFO]  Standard output for task 3 available at /home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/brca_mutsig_v2_analyze_batch_0/runinfo/000/task_logs/0000/task_0003_validate_contigs_app_a_2_1_1_tumor_contig_.stdout
2021-02-27 19:46:17.067 parsl.dataflow.dflow:1246 [INFO]  Standard error for task 3 available at /home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/brca_mutsig_v2_analyze_batch_0/runinfo/000/task_logs/0000/task_0003_validate_contigs_app_a_2_1_1_tumor_contig_.stderr
2021-02-27 19:46:17.067 parsl.dataflow.memoization:194 [DEBUG]  Ignoring these kwargs for checkpointing: ['stderr', 'stdout']
2021-02-27 19:46:17.067 parsl.dataflow.memoization:196 [DEBUG]  Ignoring kwarg stderr
2021-02-27 19:46:17.067 parsl.dataflow.memoization:196 [DEBUG]  Ignoring kwarg stdout
2021-02-27 19:46:17.075 parsl.dataflow.memoization:233 [DEBUG]  Task 3 has memoization hash 2f687c3ea23ced7dea86d6e98a25be18
2021-02-27 19:46:17.075 parsl.dataflow.memoization:239 [INFO]  Task 3 had no result in cache
2021-02-27 19:46:17.076 parsl.executors.high_throughput.executor:562 [DEBUG]  Pushing function <function validate_contigs_app at 0x2aaab7998050> to queue with args ("{'MuSE': 'MuSE', 'appletviewer': 'appletviewer', 'bam': 'bam', 'bam-somaticsniper': 'bam-somaticsnip...", "['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', ...", 'a_2_1_1_tumor_contig_', "<<class 'parsl.data_provider.files.File'> at 0x2aaad006b310 url=/home/users/nus/e0503495/scratch/Par...")
2021-02-27 19:46:17.077 parsl.dataflow.dflow:587 [INFO]  Task 3 launched on executor job_array
2021-02-27 19:46:17.077 parsl.dataflow.dflow:1244 [INFO]  Standard output for task 3 available at /home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/brca_mutsig_v2_analyze_batch_0/runinfo/000/task_logs/0000/task_0003_validate_contigs_app_a_2_1_1_tumor_contig_.stdout
2021-02-27 19:46:17.077 parsl.dataflow.dflow:1246 [INFO]  Standard error for task 3 available at /home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/brca_mutsig_v2_analyze_batch_0/runinfo/000/task_logs/0000/task_0003_validate_contigs_app_a_2_1_1_tumor_contig_.stderr
2021-02-27 19:46:17.246 parsl.app.errors:126 [DEBUG]  Reraising exception of type <class 'RuntimeError'>
2021-02-27 19:46:17.247 parsl.dataflow.dflow:289 [DEBUG]  Task 3 try 3 failed
2021-02-27 19:46:17.247 parsl.dataflow.dflow:317 [ERROR]  Task 3 failed after 3 retry attempts
Traceback (most recent call last):
  File "/home/users/nus/e0503495/Documents/parsl.git/parsl/dataflow/dflow.py", line 286, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
  File "/home/users/nus/e0503495/Documents/parsl.git/parsl/dataflow/dflow.py", line 441, in _unwrap_remote_exception_wrapper
    result.reraise()
  File "/home/users/nus/e0503495/Documents/parsl.git/parsl/app/errors.py", line 131, in reraise
    reraise(t, v, tb)
  File "/home/users/nus/e0503495/anaconda3/envs/swag_v0.2.0/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/users/nus/e0503495/Documents/parsl.git/parsl/app/errors.py", line 159, in wrapper
    return func(*args, **kwargs)  # type: ignore
  File "/home/users/nus/e0503495/Documents/Swag.git/swag/apps/util_apps.py", line 321, in validate_contigs_app
    raise RuntimeError(f"[validate_contig_app] samtools index failed | patient: {label},"
RuntimeError: [validate_contig_app] samtools index failed | patient: a_2_1_1_tumor_contig_, contig_bam_filepath: /home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/brca_mutsig_v2_analyze_batch_0/a_2_1/1/tumor/contigs_split/a_2_1_1_tumor_contig_chr1.bam, returncode: 1
```

**To Reproduce**
Steps to reproduce the behavior, for e.g:
1. Setup Parsl master branch (02d3b93ad4fd97b2411c000cf0b8820c76e5dfef) with Python 3.7 on cluster
2. Run a test script with a simple python_app that `raise RuntimeError("error")`
3. Wait 5 mins
4. See parsl.log

**Expected behavior**
Stack trace of python_app should be printed at each attempt

**Environment**
 - OS: RHEL
 - Python 3.7, Anaconda
 - Parsl version: master

**Distributed Environment**
- PBSPro

**Comment by ravihansa3000** [comment]
@benclifford appreciate it if this can be fixed before the next release. This issue did not exist in parsl-1.0.0 and it could be a major pain when troubleshooting workflow bugs in production.

**Comment by ravihansa3000** [comment]
sidenote: stdout and stderr of python_apps are not redirected to files as indicated in parsl.log
```
Standard output for task 3 available at /home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/brca_mutsig_v2_analyze_batch_0/runinfo/000/task_logs/0000/task_0003_validate_contigs_app_a_2_1_1_tumor_contig_.stdout
2021-02-27 19:46:17.077 parsl.dataflow.dflow:1246 [INFO]  Standard error for task 3 available at /home/users/nus/e0503495/scratch/Parsl-workflows/GDC-Pipeline-Output/brca_mutsig_v2_analyze_batch_0/runinfo/000/task_logs/0000/task_0003_validate_contigs_app_a_2_1_1_tumor_contig_.stderr
```

This is somewhat misleading.

**Comment by benclifford** [comment]
@ravihansa3000  the stack traces I think you mean for retryable failures were removed in #1322 which is before 0.9.0. If so, logs have been this way both in 0.9.0 and 1.0.0, since before October 2019.

See https://github.com/Parsl/parsl/pull/1322/files#diff-925607d59cf08d406591135640088fe4e3f372dec7769adc4dc6a49565cfac6fL257

Is this the log message you mean or are you talking about some more recent change?

**Comment by ravihansa3000** [comment]
@benclifford Apologies for the confusion. I may have mixed it up with Parsl 0.9.0. We were on a pre-1.0.0 commit which I assumed as final release.

**Comment by benclifford** [comment]
you shouldn't have been seeing these traces in 0.9.0 either

**Comment by ravihansa3000** [comment]
hmm...that is interesting. Maybe I was thinking of bash_apps that redirect std pipes to files. Actually, this is the first time I had to troubleshoot a python_app so I guess I was wrong here. Sorry for the noise.

Is there any reason not to print the stack trace in case of RemoteExceptions? I really don't think that's a good way to reduce log output. Maybe at least have it as configurable (env var) - only for exceptions?

**Comment by benclifford** [comment]
It was a user requested feature: those errors are a huge source of noise in the logs when there are transient application failures that go away on retry - for example, batch jobs ending with a large number of nodes.

It might be good to make this user configurable through the python logging mechanism, rather than as another parsl option.

**Comment by ravihansa3000** [comment]
Ok, thanks. Any pointers on how to make this user-configurable?

**Comment by benclifford** [comment]
For logging from within python apps when running with htex, I have submitted a feature proposal here: https://github.com/Parsl/parsl/issues/1984

**Comment by ravihansa3000** [comment]
@benclifford Thank you!
