### ISSUE TITLE
potential race condition in htex tasks structure

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1989]
**Describe the bug**
I've seen the following exception occur in a debugging branch. This looks like a potential race condition with the HTEX task list (not the DFK task list, as other race conditions might be triggering).

This occured in test_fibonacci_recursive.py which I think is exercising concurrency a lot harder than other tests.

```
ERROR    parsl.dataflow.dflow:dflow.py:316 Task 400 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/travis/build/Parsl/parsl/parsl/dataflow/dflow.py", line 286, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
  File "/home/travis/build/Parsl/parsl/parsl/dataflow/dflow.py", line 439, in _unwrap_remote_exception_wrapper
    result = future.result()
  File "/opt/python/3.8.7/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/opt/python/3.8.7/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/travis/build/Parsl/parsl/parsl/dataflow/dflow.py", line 492, in launch_if_ready
    exec_fu = self.launch_task(
  File "/home/travis/build/Parsl/parsl/parsl/dataflow/dflow.py", line 582, in launch_task
    exec_fu = executor.submit(executable, self.tasks[task_id]['resource_specification'], *args, **kwargs)
  File "/home/travis/build/Parsl/parsl/parsl/executors/high_throughput/executor.py", line 579, in submit
    return self.tasks[task_id]
KeyError: 188
```

**To Reproduce**

occasional in CI, near master 02d3b93ad4fd97b2411c000cf0b8820c76e5dfef

**Environment**

CI

**Comment by benclifford** [comment]
This is the same as #2033 with a potential fix in #2034.  Closing this issue in favour of #2033.
