### ISSUE TITLE
error in monitoring packaging? (tutorial 2)

### ISSUE THREAD

**Issue by danielskatz** [Parsl/parsl#2008]
In the first cell for monitoring in tutorial 2, I get the following error, which makes me think that we might have a dependency missing in our packaging

```
---------------------------------------------------------------------------
OptionalModuleMissing                     Traceback (most recent call last)
<ipython-input-1-c4e247be2eda> in <module>
     27        hub_address=address_by_hostname(),
     28        hub_port=6553,
---> 29        resource_monitoring_interval=1,
     30    )
     31 )

/usr/local/lib/python3.7/site-packages/typeguard/__init__.py in wrapper(*args, **kwargs)
    910         memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
    911         check_argument_types(memo)
--> 912         retval = func(*args, **kwargs)
    913         try:
    914             check_return_type(retval, memo)

/usr/local/lib/python3.7/site-packages/parsl/monitoring/monitoring.py in __init__(self, hub_address, hub_port, hub_port_range, client_address, client_port_range, workflow_name, workflow_version, logging_endpoint, logdir, monitoring_debug, resource_monitoring_enabled, resource_monitoring_interval)
    179 
    180         if _db_manager_excepts:
--> 181             raise(_db_manager_excepts)
    182 
    183         self.client_address = client_address

/usr/local/lib/python3.7/site-packages/parsl/monitoring/monitoring.py in <module>
     21 
     22 try:
---> 23     from parsl.monitoring.db_manager import dbm_starter
     24 except Exception as e:
     25     _db_manager_excepts = e

/usr/local/lib/python3.7/site-packages/parsl/monitoring/db_manager.py in <module>
     44 
     45 
---> 46 class Database:
     47 
     48     if not _sqlalchemy_enabled:

/usr/local/lib/python3.7/site-packages/parsl/monitoring/db_manager.py in Database()
     52     if not _sqlalchemy_utils_enabled:
     53         raise OptionalModuleMissing(['sqlalchemy_utils'],
---> 54                                     ("Default database logging requires the sqlalchemy_utils library."
     55                                      " Enable monitoring support with: pip install parsl[monitoring]"))
     56 

OptionalModuleMissing: (['sqlalchemy_utils'], 'Default database logging requires the sqlalchemy_utils library. Enable monitoring support with: pip install parsl[monitoring]')
```

**Comment by benclifford** [comment]
I've seen this error come up when sqlalchemy fails for some other reason - the dependency missing error was wrong in that case. Check that you have sqlalchemy 1.3.x installed with `pip list |grep - sqlal`

**Comment by danielskatz** [comment]
I'm not sure about the naked `-` in grep, but if I run `python3 -m pip list | grep -i sqlal` I get 
```python3 -m pip list | grep -i sqlal
Flask-SQLAlchemy              2.5.1      
SQLAlchemy                    1.4.7      
SQLAlchemy-Utils              0.36.8   ```
so it looks like you are right and there's some other problem

**Comment by benclifford** [comment]
This was fixed in master in #1994, after 1.1.0a1 was made. So using `master` should make this error go away.

**Comment by danielskatz** [comment]
How do I do this?

I just did `python3 -m pip install 'parsl[monitoring] @ git+https://github.com/parsl/parsl@master'` but it didn't seem to change anything - the results all seem to be `Requirement already satisfied:...` lines

**Comment by danielskatz** [comment]
The answer was to do `python3 -m pip install 'parsl[monitoring] @ git+https://github.com/parsl/parsl@master' --upgrade`

**Comment by danielskatz** [comment]
but this also found another missing dependency, which can be fixed by `python3 -m pip install typing-extensions` and as documented in #2010

**Comment by danielskatz** [comment]
The first monitoring cell now gives this error on my mac:
```Exception in thread Monitoring-migrate-priority:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/parsl/process_loggers.py", line 27, in wrapped
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/parsl/monitoring/db_manager.py", line 522, in _migrate_logs_to_internal
    .format(queue_tag, kill_event.is_set(), logs_queue.qsize() != 0))
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
Exception in thread Monitoring-migrate-node:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/parsl/process_loggers.py", line 27, in wrapped
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/parsl/monitoring/db_manager.py", line 522, in _migrate_logs_to_internal
    .format(queue_tag, kill_event.is_set(), logs_queue.qsize() != 0))
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
Exception in thread Monitoring-migrate-resource:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/parsl/process_loggers.py", line 27, in wrapped
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/parsl/monitoring/db_manager.py", line 522, in _migrate_logs_to_internal
    .format(queue_tag, kill_event.is_set(), logs_queue.qsize() != 0))
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
Exception in thread Monitoring-migrate-block:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/parsl/process_loggers.py", line 27, in wrapped
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/parsl/monitoring/db_manager.py", line 522, in _migrate_logs_to_internal
    .format(queue_tag, kill_event.is_set(), logs_queue.qsize() != 0))
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
```
Ben's suggestion is that we declare monitoring unsupported on mac for now
