### ISSUE TITLE
dfk.tasks[id] elimination

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#2014]
Since the introduction of `dfk.tasks` garbage collection (#1512), knowing a task ID is no longer enough to be able to get a task's record from the DFK. This has resulted in occasional bugs to do with assuming otherwise, and awkward logic vs checkpointing (itself buggy, #1996).

Probably a better way is to pass around python level references to task structures, and only use task ID values when leaving the DFK (for example, monitoring or log messages); any use of dfk/self.tasks[id] should be considered suspicious.

This then allows self.tasks records to be eliminated earlier, gives more confidence that a task record will be accessible when expected, and allows the Python garbage collector to deal with garbage collection of task records.

Potentially this could eliminate the need for self.tasks entirely, although that isn't my immediate goal.

One thing to be aware of is that previously code which only stored a task ID (which could disappear) might now be holding a python-level reference to a task record, and keeping that task record around longer than previously. I don't think this is an issue, though.

At time of writing, I've had a few patches being tested in the `desc` release for a while.

This issue should document progress on this.

**Comment by benclifford** [comment]
I think #2033 is a similar kind of problem but in HTEX task management, not  DFK task management.

**Comment by benclifford** [comment]
I've also seen this happen in CI, which I believe is related. This test isn't very good - it checks that checkpoint files are written out, but does not check that the relevant tasks are written. What happens I think is that the checkpoint call will race with the post-task-completion code: sometimes tasks will be wiped from the DFK by the post task completion, and no tasks will be checkpointed; sometimes the checkpoint code will get there first, meaning that there will be two attempts to wipe the task from the DFK (once in checkpointing, and once in task completion code).

The use of checkpointing when it is supposed to be disabled is invalid for this test, though, so really this test should be rewritten to test something better.

```
parsl/tests/test_checkpointing/test_python_checkpoint_1.py F
=================================== FAILURES ===================================
________________________ test_initial_checkpoint_write _________________________
n = 2
    @pytest.mark.local
    def test_initial_checkpoint_write(n=2):
        """1. Launch a few apps and write the checkpoint once a few have completed
        """
        parsl.load(config)
        results = launch_n_random(n)

>       cpt_dir = parsl.dfk().checkpoint()
parsl/tests/test_checkpointing/test_python_checkpoint_1.py:34:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
parsl/dataflow/dflow.py:1201: in checkpoint
    self.wipe_task(task_id)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <parsl.dataflow.dflow.DataFlowKernel object at 0x7f239df591c0>
task_id = 1
    def wipe_task(self, task_id):
        """ Remove task with task_id from the internal tasks table
        """
        if self.config.garbage_collect:
>           del self.tasks[task_id]
E           KeyError: 1
parsl/dataflow/dflow.py:518: KeyError
```

**Comment by benclifford** [comment]
I've seen this in one run of apparently unrelated PR #2051 that looks related.

```
ERROR    concurrent.futures:_base.py:326 exception calling callback for <Future at 0x7f612c08b898 state=finished raised Exception>
Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/home/travis/build/Parsl/parsl/parsl/dataflow/dflow.py", line 278, in handle_exec_update
    task_record = self.tasks[task_id]
KeyError: 0
```

in a failing test:
```
2320            result = connection.execute("SELECT COUNT(*) FROM workflow")
2321            (c, ) = result.first()
2322 >           assert c == 1
2323 E           assert 0 == 1
2324
2325 parsl/tests/test_monitoring/test_fuzz_zmq.py:86: AssertionError
```

**Comment by benclifford** [comment]
There are still a few references to self.tasks[] in dflow.py which are a bit more awkward to remove - keeping this issue open to track progress there.

**Comment by benclifford** [comment]
I've prototyped a change in checkpointing behaviour to remove the use of self.tasks[] in the checkpointing code. This allows `wipe_task` to be called only in one place, rather than a slightly awkward deferral mechanism when checkpointing is enabled. This leaves just one use of the self.tasks[] dictionary at all - a helper function to wait for all currently outstanding tasks.

I'm not sure how much that function is used, but if we're prepared to sacrifice that, I think we would be in a position to get rid of self.tasks[] entirely.
