### ISSUE TITLE
Occasional exceptions in monitoring at shutdown (due to threading?)

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#2041]
When parsl 1.1.0 shuts down with monitoring enabled, sometimes this happens. It looks like something to do with threading.

```
2021-04-28 16:32:28 parsl.monitoring.monitoring:407 [INFO]  Terminating Monitoring Hub
2021-04-28 16:32:28 parsl.monitoring.monitoring:425 [INFO]  Waiting for Hub to receive all messages and terminate
Exception during reset or similar
Traceback (most recent call last):
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/parsl/monitoring/db_manager.py", line 607, in _update
    self.db.update(table=table, columns=columns, messages=messages)
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/parsl/monitoring/db_manager.py", line 80, in update
    self.session.bulk_update_mappings(mapper, mappings)
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2939, in bulk_update_mappings
    self._bulk_save_mappings(
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2956, in _bulk_save_mappings
    transaction = self.begin(subtransactions=True)
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 957, in begin
    self.transaction = self.transaction._begin(nested=nested)
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 317, in _begin
    self._assert_active()
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 282, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 558, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 46912496695232 and this is thread id 46912610756352.
Exception closing connection <sqlite3.Connection object at 0x2aaab1c94030>
Traceback (most recent call last):
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/parsl/monitoring/db_manager.py", line 607, in _update
    self.db.update(table=table, columns=columns, messages=messages)
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/parsl/monitoring/db_manager.py", line 80, in update
    self.session.bulk_update_mappings(mapper, mappings)
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2939, in bulk_update_mappings
    self._bulk_save_mappings(
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2956, in _bulk_save_mappings
    transaction = self.begin(subtransactions=True)
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 957, in begin
    self.transaction = self.transaction._begin(nested=nested)
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 317, in _begin
    self._assert_active()
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 282, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 558, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 46912496695232 and this is thread id 46912610756352.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 270, in _close_connection
    self._dialect.do_close(connection)
  File "/global/homes/d/descdm/.conda/envs/parsl-202103-WQ/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 564, in do_close
    dbapi_connection.close()

```

**To Reproduce**
This seems to happen occasionally in some runs. I haven't seen any pattern to cause it to happen.

**Expected behavior**
clean shutdown

**Environment**
cori nersc

**Comment by ZhuozhaoLi** [comment]
This is odd. The sqlite object is never used in another thread. A quick google search pointed me to https://github.com/ESWZY/telegram-news/issues/8
