### ISSUE TITLE
"Affinity does not work if there are more workers than cores" seems to cause hang

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#2072]
**Describe the bug**
I'm running parsl `--config local` tests in a docker container with a single CPU allocated to that container via `docker run --cpuset-cpus=0`

The `parsl/tests/sites/test_affinity.py` test hangs. When I dig into the htex worker logs I find this error. This error should be properly propagated to the submit side in some way rather than resulting in a hang.

```
2021-05-17 13:04:35.266 worker_log:505 Rank:1 [INFO]  Worker 1 started
2021-05-17 13:04:35.266 worker_log:507 Rank:1 [DEBUG]  Debug logging enabled
2021-05-17 13:04:35.266 worker_log:31 Rank:1 [ERROR]  Exceptional ending for worker on thread MainThread
Traceback (most recent call last):
  File "/home/benc/parsl/src/parsl/parsl/process_loggers.py", line 27, in wrapped
    r = func(*args, **kwargs)
  File "/home/benc/parsl/src/parsl/parsl/executors/high_throughput/process_worker_pool.py", line 514, in worker
    assert cores_per_worker > 0, "Affinity does not work if there are more workers than cores"
AssertionError: Affinity does not work if there are more workers than cores
```

**To Reproduce**
Run the above test in a docker container with --cpuset-cpus=0 set, on a machine that has more than 1 core.

**Expected behavior**
The error should propagate to the submit side and the test should fail (more generally - the workflow user should be presented with this error rather than a hang)

**Environment**
python 3.9.2, parsl master bf83c06af78ac0e4243fa2b6686d3b99110cf01c

**Comment by benclifford** [comment]
@yadudoc and I had some discussion offline about the block error handling for the cases where the process worker pool starts, but then fails deeper into startup.

I think our talk was more in the context of misconfigured networking (eg. `process_worker_pool` start but cannot make a network connection), but I realise now this #2072 misconfiguration is also exactly that failure case.
