### ISSUE TITLE
multiple condor jobs on same system interfere with each other

### ISSUE THREAD

**Issue by beckermr** [Parsl/parsl#2160]
**Describe the bug**
If I run two condor jobs at once on the same system, I get the following error

```
==> runinfo/043/parsl.log <==
2021-12-05 08:59:43.043 parsl.dataflow.flow_control:114 [ERROR]  Flow control callback threw an exception - logging and proceeding anyway
Traceback (most recent call last):
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/flow_control.py", line 112, in make_callback
    self.callback(tasks=self._event_buffer, kind=kind)
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 102, in poll
    self._update_state()
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 109, in _update_state
    item.poll(now)
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 44, in poll
    self._status = self._executor.status()
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/executors/status_handling.py", line 73, in status
    status = self._make_status_dict(block_ids, self._provider.status(job_ids))
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/providers/condor/condor.py", line 166, in status
    self._status()
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/providers/condor/condor.py", line 150, in _status
    self.resources[job_id]['status'] = JobStatus(state)
KeyError: '69288.0'

==> runinfo/042/parsl.log <==
2021-12-05 08:59:45.521 parsl.dataflow.strategy:210 [DEBUG]  Executor HighThroughputExecutor has 200 active tasks, 0/200 running/pending blocks, and 0 connected workers
```

It appears that one job is seeing the pilot blocks of the other

**To Reproduce**
Run two condor jobs. You may need to kill one or the other and restart them.

**Expected behavior**

**Environment**
 - OS: linux
 - Python version: 3.7.12 
 - parsl version: 1.1.0

**Distributed Environment**
- Where are you running the Parsl script from ? Login node
- Where do you need the workers to run ? Condor

**Comment by beckermr** [comment]
The job with the errors does not proceed.

**Comment by benclifford** [comment]
When you say "two condor jobs" do you mean two entirely separate runs of parsl (i.e. two separate `parsl.load()` calls in two separate python processes) on the same computer?

**Comment by beckermr** [comment]
Yes exactly. I would have assumed that the pilot jobs know which instance of the various components upstream to talk to, but it appears that somehow one is trying to talk to another or something?

**Comment by benclifford** [comment]
They make unauthenticated network communication between different components so there is plenty of scope for wires getting crossed - can you paste your configuration here?

**Comment by beckermr** [comment]
Ahh got it. I guess one solution would be for each parsl invocation to get a unique ID and then components can ignore stuff from the wrong ID if it is carried around into all of the subsystems?

Here is my script:

```
import time
import sys
import parsl
from parsl.providers import CondorProvider
from parsl.config import Config
from parsl.executors import HighThroughputExecutor
from parsl.addresses import address_by_hostname, get_all_addresses

from concurrent.futures import as_completed

from parsl.configs.local_threads import config

START = time.time()

SCHED_OPTS = """
kill_sig        = SIGINT
+Experiment     = "astro"
Notification    = Never
Image_Size       =  1000000
"""
# GetEnv          = True

WORKER_INIT = """

source ~/.bashrc

export OMP_NUM_THREADS=1

if [[ -n $_CONDOR_SCRATCH_DIR ]]; then
    # the condor system creates a scratch directory for us,
    # and cleans up afterward
    tmpdir=$_CONDOR_SCRATCH_DIR
    export TMPDIR=$tmpdir
else
    # otherwise use the TMPDIR
    tmpdir='.'
    mkdir -p $tmpdir
fi

source activate bnl

echo `which python`
"""

WALLTIME = "48:00:00"

condor_config = Config(
    executors=[
        HighThroughputExecutor(
            worker_debug=True,
            max_workers=1,
            provider=CondorProvider(
                cores_per_slot=1,
                mem_per_slot=2,
                nodes_per_block=1,
                init_blocks=0,
                parallelism=1,
                max_blocks=10000,
                scheduler_options=SCHED_OPTS,
                worker_init=WORKER_INIT,
                walltime=WALLTIME,
                cmd_timeout=300,
            )
        )
    ],
)

parsl.load(condor_config)


@parsl.python_app
def app_double(x):
    import time
    time.sleep(30)    
    return 2*x


items = range(0, int(sys.argv[1]))

mapped_results = []
for i in items:
    x = app_double(i)
    mapped_results.append(x)


res = []
n_tot = len(mapped_results)
n_left = len(mapped_results)
start = time.time()
eta = -1
while n_left > 0:
    for i in range(len(mapped_results)):
        f = mapped_results[i]
        if n_left == 1:
            print("done?", f.done(), flush=True)
        try:
            f.result(timeout=10)
        except:
            pass
        if n_left == 1:
            print("done?", f.done(), flush=True)
        if f.done():
            res.append(f.result())
            n_left -= 1
            eta = (time.time() - start) / (n_tot - n_left) * n_left
            print("[%06ds] eta|done|left:" % (int(time.time() - START)), eta, n_tot - n_left, n_left, flush=True)
            mapped_results.pop(i)
            break
            
# for f in as_completed(mapped_results):
#    n_left -= 1

print("total:", sum(res), sum(2*x for x in range(0, int(sys.argv[1]))), flush=True)

print("done w/ loop:", time.time() - start, flush=True)

# total = app_sum(inputs=mapped_results)
# print("total:", total.result(), flush=True)
```

**Comment by beckermr** [comment]
I've noticed some odd behavior of the futures here as well where they are not marked as done via `f.done()` if you do not try and get the result first.

**Comment by benclifford** [comment]
I'm not clear from the first logs that you pasted how that shows that there are two runs interfering with each other: one is showing some stack trace that looks like some bug, and the other is showing that it has requested 200 blocks and is waiting for them to start up.

Can you attach the whole `runinfo/04[23]/` directories to this issue?

**Comment by beckermr** [comment]
Sure!

**Comment by beckermr** [comment]
I assumed since one of the runs couldn't find a given condor pilot job in its internals, that job must be from the other run. I might be wrong about that! 

For the sure the run with error doesn't start until I forcibly remove all condor jobs from the system. After that it starts up normally.


[043.tar.gz](https://github.com/Parsl/parsl/files/7656062/043.tar.gz)
[042.tar.gz](https://github.com/Parsl/parsl/files/7656063/042.tar.gz)

**Comment by beckermr** [comment]
Here's an example with 4 parsl runs all looking for the same condor pilot job:

```
==> runinfo/044/parsl.log <==
2021-12-05 09:29:54.131 parsl.dataflow.flow_control:114 [ERROR]  Flow control callback threw an exception - logging and proceeding anyway
Traceback (most recent call last):
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/flow_control.py", line 112, in make_callback
    self.callback(tasks=self._event_buffer, kind=kind)
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 102, in poll
    self._update_state()
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 109, in _update_state
    item.poll(now)
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 44, in poll
    self._status = self._executor.status()
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/executors/status_handling.py", line 73, in status
    status = self._make_status_dict(block_ids, self._provider.status(job_ids))
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/providers/condor/condor.py", line 166, in status
    self._status()
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/providers/condor/condor.py", line 150, in _status
    self.resources[job_id]['status'] = JobStatus(state)
KeyError: '69674.0'

==> runinfo/045/parsl.log <==
2021-12-05 09:29:55.883 parsl.dataflow.flow_control:114 [ERROR]  Flow control callback threw an exception - logging and proceeding anyway
Traceback (most recent call last):
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/flow_control.py", line 112, in make_callback
    self.callback(tasks=self._event_buffer, kind=kind)
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 102, in poll
    self._update_state()
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 109, in _update_state
    item.poll(now)
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 44, in poll
    self._status = self._executor.status()
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/executors/status_handling.py", line 73, in status
    status = self._make_status_dict(block_ids, self._provider.status(job_ids))
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/providers/condor/condor.py", line 166, in status
    self._status()
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/providers/condor/condor.py", line 150, in _status
    self.resources[job_id]['status'] = JobStatus(state)
KeyError: '69674.0'

==> runinfo/046/parsl.log <==
2021-12-05 09:29:55.892 parsl.dataflow.flow_control:114 [ERROR]  Flow control callback threw an exception - logging and proceeding anyway
Traceback (most recent call last):
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/flow_control.py", line 112, in make_callback
    self.callback(tasks=self._event_buffer, kind=kind)
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 102, in poll
    self._update_state()
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 109, in _update_state
    item.poll(now)
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 44, in poll
    self._status = self._executor.status()
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/executors/status_handling.py", line 73, in status
    status = self._make_status_dict(block_ids, self._provider.status(job_ids))
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/providers/condor/condor.py", line 166, in status
    self._status()
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/providers/condor/condor.py", line 150, in _status
    self.resources[job_id]['status'] = JobStatus(state)
KeyError: '69674.0'

==> runinfo/047/parsl.log <==
2021-12-05 09:29:56.210 parsl.dataflow.flow_control:114 [ERROR]  Flow control callback threw an exception - logging and proceeding anyway
Traceback (most recent call last):
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/flow_control.py", line 112, in make_callback
    self.callback(tasks=self._event_buffer, kind=kind)
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 102, in poll
    self._update_state()
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 109, in _update_state
    item.poll(now)
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/dataflow/task_status_poller.py", line 44, in poll
    self._status = self._executor.status()
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/executors/status_handling.py", line 73, in status
    status = self._make_status_dict(block_ids, self._provider.status(job_ids))
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/providers/condor/condor.py", line 166, in status
    self._status()
  File "/gpfs02/astro/workarea/beckermr/miniconda3/lib/python3.7/site-packages/parsl/providers/condor/condor.py", line 150, in _status
    self.resources[job_id]['status'] = JobStatus(state)
KeyError: '69674.0'
```

**Comment by beckermr** [comment]
It appears to be completed?

```
$ condor_q 69674.0


-- Schedd: astro0101.rcf.bnl.gov : <130.199.48.120:9618?... @ 12/05/21 09:31:03
 ID       OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD
69674.0   beckermr       12/5  09:12   0+00:00:36 C  0   49.0 bash parsl.parsl.condor.1638713573.3207335.script

Total for query: 1 jobs; 1 completed, 0 removed, 0 idle, 0 running, 0 held, 0 suspended 
Total for all users: 14 jobs; 14 completed, 0 removed, 0 idle, 0 running, 0 held, 0 suspended


```

**Comment by benclifford** [comment]
OK, so run 042 is launching a bunch of condor jobs - including `69385.0`.

Run 043 polls condor for status - but it is supposed to ask only about its own jobs. It looks like `condor_q` is reporting back the status of `69385.0`, which was launched by 042. That `condor_q` command is supposed to be formed to only ask about jobs that 043 has launched.

That behaviour makes me think that the parsl code might break (in your case) if you have any other condor jobs in the system (eg a long sleep 600s or something like that) rather than it being specifically parsl interfering with itself - that might be interesting to test.

The specific code that forms the condor_q command that seems to be returning too much is here:https://github.com/Parsl/parsl/blob/d5922e92dc78527621b8a26e00370eeb143d6ac6/parsl/providers/condor/condor.py#L136

**Comment by benclifford** [comment]
> Here's an example with 4 parsl runs all looking for the same condor pilot job:

They *aren't* looking for that job - but they're getting the status back from `condor_q` somehow anyway. That's what's causing the problem.

**Comment by beckermr** [comment]
Awesome! Thank you for the quick debugging! 

I think I know how to fix it. I'll try my hand at a PR later today.

**Comment by beckermr** [comment]
OK. PR is up. Hopefully we can merge it soon!
