### ISSUE TITLE
Race condition in task checkpointing

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#234]
With `config["globals"]["checkpointMode"] = "task_exit"`, the DFK attempts to checkpoint every task at task completion. However in the case of fast apps without dependencies, the task returns before the AppFuture is created. This results in a race condition between the checkpoint method and the task update.

If the checkpoint method is called first we get :
```
Traceback (most recent call last):
  File "test_regression_233.py", line 38, in <module>
    test_checkpoint_availability()
  File "test_regression_233.py", line 27, in test_checkpoint_availability
    original = run_checkpointed([])
  File "test_regression_233.py", line 18, in run_checkpointed
    x = cached_rand(i)
  File "/home/yadu/src/parsl/parsl/app/app_factory.py", line 76, in __call__
    return app_obj(*args, **kwargs)
  File "/home/yadu/src/parsl/parsl/app/python_app.py", line 46, in __call__
    **kwargs)
  File "/home/yadu/src/parsl/parsl/dataflow/dflow.py", line 499, in submit
    task_id, func, *new_args, **kwargs)
  File "/home/yadu/src/parsl/parsl/dataflow/dflow.py", line 322, in launch_task
    exec_fu.add_done_callback(partial(self.handle_update, task_id))
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 376, in add_done_callback
    fn(self)
  File "/home/yadu/src/parsl/parsl/dataflow/dflow.py", line 218, in handle_update
    self.checkpoint(tasks=[task_id])
  File "/home/yadu/src/parsl/parsl/dataflow/dflow.py", line 617, in checkpoint
    if self.tasks[task_id]['app_fu'].done() and \
AttributeError: 'NoneType' object has no attribute 'done'
```

**Comment by benclifford** [comment]
I also see this error - but in my case, as far as I can tell, it is from a bash app that is slow-ish (a 5 second sleep) - with no dependencies.

**Comment by yadudoc** [comment]
This might be a different bug. I'm able to run 1s python apps with no issue.

**Comment by yadudoc** [comment]
@benclifford Can you test with this branch please ?

**Comment by benclifford** [comment]
It looks like my exceptions weren't appearing against master, but against my hacked dev version: I don't get exceptions on master or with your #237 PR...
