### ISSUE TITLE
MacOS Big Sur OSError [Errno 6] with HighThroughputExecutor

### ISSUE THREAD

**Issue by Oddant1** [Parsl/parsl#2417]
**Describe the bug**
When attempting to use a HighThroughputExecutor on macOS Big Sur I'm getting a long string of `OSError: [Errno 6] Device not configured`  for every network device on my system. They all look like this

```
ERROR    parsl.addresses:addresses.py:113 Ignoring failure to fetch address from interface lo0
Traceback (most recent call last):
  File "/Users/caporasolab/miniconda3/envs/q2-dev/lib/python3.8/site-packages/parsl/addresses.py", line 111, in get_all_addresses
    s_addresses.add(address_by_interface(interface))
  File "/Users/caporasolab/miniconda3/envs/q2-dev/lib/python3.8/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/Users/caporasolab/miniconda3/envs/q2-dev/lib/python3.8/site-packages/parsl/addresses.py", line 93, in address_by_interface
    return socket.inet_ntoa(fcntl.ioctl(
OSError: [Errno 6] Device not configured
```
This culminates in the following traceback.
```
Traceback (most recent call last):
  File "/Users/caporasolab/miniconda3/envs/q2-dev/lib/python3.8/site-packages/parsl/dataflow/dflow.py", line 286, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
  File "/Users/caporasolab/miniconda3/envs/q2-dev/lib/python3.8/site-packages/parsl/dataflow/dflow.py", line 469, in _unwrap_remote_exception_wrapper
    result = future.result()
  File "/Users/caporasolab/miniconda3/envs/q2-dev/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/Users/caporasolab/miniconda3/envs/q2-dev/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
Exception: [No error message received]
```
I am unable to reproduce this issue on Linux. I dug through the source for addresses.py which pointed me [here](https://stackoverflow.com/questions/24196932/how-can-i-get-the-ip-address-of-eth0-in-python#24196955). I tried both method 1 and method 2 (the one parsl is using) independent of parsl. Method 1 worked and method 2 produced the exact same error.

**To Reproduce**
1. Setup Parsl 1.2.0 on macOS Big Sur with Python 3.8.13. This has happened on macOS 11.5.2 and 11.6.8
2. Create and load the following config

```
PARSL_CONFIG.parsl_config = Config(
            executors=[
                HighThroughputExecutor(
                    label='default',
                    max_workers=6,
                    worker_logdir_root=os.getcwd(),

                    provider=AdHocProvider(
                        # Command to be run before starting a worker, such as:
                        # 'module load Anaconda; source activate parsl_env'.
                        worker_init='',
                        channels=[parsl.channels.LocalChannel(
                            script_dir=os.getcwd())]
                    )
                )
            ],
            #  AdHoc Clusters should not be setup with scaling strategy.
            strategy=None,
        )
```

a very basic HighThroughputExecutor

3. Run a Python app on the executor
4. Failure

**Expected behavior**
The python_app works

**Environment**
 - OS: macOS Big Sur
 - Python3.8.13
 - Parsl 1.2.0

**Distributed Environment**
- Kicking things off on a MacMini
- Running the workers on the same MacMini

**Comment by Oddant1** [comment]
The issue appears to have been resolved by switching from an AdHocProvider to a LocalProvider. The AdHocProvider with the local channel worked fine on Linux, but not on Mac.
