### ISSUE TITLE
WorkQueueExecutor.set_bad_state_and_fail_all fails when some tasks have already completed

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#2473]
**Describe the bug**

`BlockProviderExecutor.set_bad_state_and_fail_all` contains code to fail all tasks:

```
        for task in self._tasks:
            self._tasks[task].set_exception(BadStateException(self, self._executor_exception))
```

However, with the Work Queue Executor, if some tasks have already completed (see issue #2207 for when this might happen), then `set_exception` will raise an exception when called on the tasks that are already completed.

```
1668693198.706212 2022-11-17 13:53:18 MainProcess-54349 FlowControl-Thread-139792904353536 parsl.dataflow.flow_control:100 make_callback ERROR: Flow control callback threw an exception - logging and proceeding anyway
Traceback (most recent call last):
  File "/home/benc/parsl/src/parsl/parsl/dataflow/flow_control.py", line 98, in make_callback
    self.callback(tasks=self._event_buffer)
  File "/home/benc/parsl/src/parsl/parsl/dataflow/task_status_poller.py", line 111, in poll
    self._error_handler.run(self._poll_items)
  File "/home/benc/parsl/src/parsl/parsl/dataflow/job_error_handler.py", line 14, in run
    self._check_irrecoverable_executor(es)
  File "/home/benc/parsl/src/parsl/parsl/dataflow/job_error_handler.py", line 19, in _check_irrecoverable_executor
    es.executor.handle_errors(self, es.status)
  File "/home/benc/parsl/src/parsl/parsl/executors/status_handling.py", line 147, in handle_errors
    error_handler.simple_error_handler(self, status, init_blocks)
  File "/home/benc/parsl/src/parsl/parsl/dataflow/job_error_handler.py", line 25, in simple_error_handler
    executor.set_bad_state_and_fail_all(self.get_error(status))
  File "/home/benc/parsl/src/parsl/parsl/executors/status_handling.py", line 124, in set_bad_state_and_fail_all
    self._tasks[task].set_exception(BadStateException(self, self._executor_exception))
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 540, in set_exception
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
```

This leads to subsequent tasks not having an exception set.

**To Reproduce**
parsl `master` branch 34fe75fd27f7f0989e944c12930500bf90351733

Run this code, then when the code is "waiting for that worker lost", `killall -KILL work_queue_worker`.
Observe that 

```
from parsl.tests.configs.workqueue_blocks import config

import parsl

parsl.load(config)

@parsl.python_app
def fast():
  pass

@parsl.python_app
def long():
  import time
  while True:
    time.sleep(3600)



print("running one task to completion")
fast().result()

print("one task run to completion")

while True:
    print("now submit one that I expect to fail with worker lost")
    future = long()

    print("waiting for that worker lost")
    assert future.exception() is not None

print("done")
```

The following log message will appear (as should happen)

```set_bad_state_and_fail_all ERROR: Setting bad state due to exception```

but then the above `concurrent.futures._base.InvalidStateError` will be logged, and the workflow will not terminate.

This does not happen with the HighThroughputExecutor, because HTEX removes completed tasks from self.tasks.

A fix for this bug might be for the Work Queue Executor to also remove completed tasks from self.tasks.

**Expected behavior**
The test workflow should not hang.

The test workflow should probably return an exception from every invocation of future = long().exception() - so it should be seen to noisily loop infinitely, rather than hang.

In practice in a real workflow (with a non-infinite number of tasks) that should result in clean workflow ending via exceptions.

**Environment**
my laptop

**Comment by benclifford** [comment]
HTEX also seems to call _set_bad_state_and_fail multiple times, but this results in a different weird behaviour: that the stack track for the failing exception gets long and longer (as if it's being nested repeatedly due to how it is generated?)
