### ISSUE TITLE
Missing six in project requirements

### ISSUE THREAD

**Issue by WardLT** [Parsl/parsl#2574]
**Describe the bug**
Parsl is missing "six" from it's project requirements

**To Reproduce**
Steps to reproduce the behavior, for e.g:
1. Install Parsl in a clean environment
2. Try to `import parsl`

**Expected behavior**
It imports

**Environment**
 - OS: ubuntu
 - Python version: 3.10
 - Parsl version: 2023.*

**Evidence**
```
(test) lward@bettik-linux:~/Work/ExaLearn/colmena$ pip install parsl
Collecting parsl
  Using cached parsl-2023.1.16-py3-none-any.whl (481 kB)
Collecting types-six
  Using cached types_six-1.16.21.4-py3-none-any.whl (14 kB)
Collecting types-requests
  Using cached types_requests-2.28.11.8-py3-none-any.whl (14 kB)
Collecting dill
  Using cached dill-0.3.6-py3-none-any.whl (110 kB)
Collecting psutil>=5.5.1
  Using cached psutil-5.9.4-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
Collecting pyzmq>=17.1.2
  Downloading pyzmq-25.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 7.3 MB/s eta 0:00:00
Collecting typeguard>=2.10
  Using cached typeguard-2.13.3-py3-none-any.whl (17 kB)
Collecting requests
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 12.2 MB/s eta 0:00:00
Collecting globus-sdk
  Using cached globus_sdk-3.15.1-py3-none-any.whl (206 kB)
Collecting tblib
  Using cached tblib-1.7.0-py2.py3-none-any.whl (12 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting types-paramiko
  Using cached types_paramiko-2.12.0.3-py3-none-any.whl (32 kB)
Collecting paramiko
  Downloading paramiko-3.0.0-py3-none-any.whl (210 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.8/210.8 kB 1.4 MB/s eta 0:00:00
Collecting setproctitle
  Using cached setproctitle-1.3.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (30 kB)
Collecting pyjwt[crypto]<3.0.0,>=2.0.0
  Using cached PyJWT-2.6.0-py3-none-any.whl (20 kB)
Collecting cryptography!=3.4.0,>=3.3.1
  Using cached cryptography-39.0.0-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
Requirement already satisfied: certifi>=2017.4.17 in /home/lward/miniconda3/envs/test/lib/python3.10/site-packages (from requests->parsl) (2022.12.7)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 9.2 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (198 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.8/198.8 kB 536.8 kB/s eta 0:00:00
Collecting pynacl>=1.5
  Using cached PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
Collecting bcrypt>=3.2
  Using cached bcrypt-4.0.1-cp36-abi3-manylinux_2_28_x86_64.whl (593 kB)
Collecting types-urllib3<1.27
  Using cached types_urllib3-1.26.25.4-py3-none-any.whl (14 kB)
Collecting cffi>=1.12
  Using cached cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Installing collected packages: types-urllib3, types-six, charset-normalizer, urllib3, typing-extensions, types-requests, typeguard, tblib, setproctitle, pyzmq, pyjwt, pycparser, psutil, idna, dill, bcrypt, requests, cffi, pynacl, cryptography, types-paramiko, paramiko, globus-sdk, parsl
Successfully installed bcrypt-4.0.1 cffi-1.15.1 charset-normalizer-3.0.1 cryptography-39.0.0 dill-0.3.6 globus-sdk-3.15.1 idna-3.4 paramiko-3.0.0 parsl-2023.1.16 psutil-5.9.4 pycparser-2.21 pyjwt-2.6.0 pynacl-1.5.0 pyzmq-25.0.0 requests-2.28.2 setproctitle-1.3.2 tblib-1.7.0 typeguard-2.13.3 types-paramiko-2.12.0.3 types-requests-2.28.11.8 types-six-1.16.21.4 types-urllib3-1.26.25.4 typing-extensions-4.4.0 urllib3-1.26.14
(test) lward@bettik-linux:~/Work/ExaLearn/colmena$ python
Python 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import parsl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lward/miniconda3/envs/test/lib/python3.10/site-packages/parsl/__init__.py", line 22, in <module>
    from parsl.app.app import bash_app, join_app, python_app
  File "/home/lward/miniconda3/envs/test/lib/python3.10/site-packages/parsl/app/app.py", line 12, in <module>
    from parsl.dataflow.dflow import DataFlowKernel
  File "/home/lward/miniconda3/envs/test/lib/python3.10/site-packages/parsl/dataflow/dflow.py", line 22, in <module>
    from parsl.app.errors import RemoteExceptionWrapper
  File "/home/lward/miniconda3/envs/test/lib/python3.10/site-packages/parsl/app/errors.py", line 8, in <module>
    from six import reraise
ModuleNotFoundError: No module named 'six'
>>> 
```

**Comment by benclifford** [comment]
It's right that we should require `six` explicitly.

It looks like previously it was provided as a transitive dependency via `paramiko`, but paramiko recently removed this, here: https://github.com/paramiko/paramiko/commit/39f458c834def3c217a3bd2eb62cc92032e20975

**Comment by benclifford** [comment]
In CI this does not show up, because test-requirements.txt transitively installs this via `pytest-xdist`.
