### ISSUE TITLE
SSHInteractiveLoginChannel directory model is broken

### ISSUE THREAD

**Issue by astro-friedel** [Parsl/parsl#2600]
When using the `SSHInteractiveLoginChannel` for running remote Parsl jobs I can get Parsl to make the ssh connection to the remote machine, but the task quickly dies on the submit side. The logs indicate that it cannot write the submit script. From what I can tell Parsl creates a directory called `submit_scripts` inside of `runinfo/000/`. But when Parsl goes to write the script it wants to put it in `local_submit_scripts` which does not exist. So it looks like there is a mismatch of which directory to use. As a work around I can create the directory in `dflow.py` near line 1011, after `provider.script_dir` is defined.

**To Reproduce**
The following setup will expose the issue:
``` python
import parsl
from parsl.executors import HighThroughputExecutor
from parsl.providers import SlurmProvider
from parsl.launchers import SrunLauncher
from parsl.addresses import address_by_hostname
from parsl.channels import SSHInteractiveLoginChannel
from parsl.config import Config
from parsl.app.app import python_app

my_executor = HighThroughputExecutor(label='My_htex',
                                      address=address_by_hostname(),
                                      max_workers=3,
                                      provider=SlurmProvider(partition='secondary',
                                                             channel=SSHInteractiveLoginChannel(
                                                                 hostname='xxxxxxxx',
                                                                 username='xxxxxxxx'
                                                                 ),
                                                             nodes_per_block=1,
                                                             cores_per_node=3,
                                                             walltime='00:30:00',
                                                             init_blocks=1,
                                                             launcher=SrunLauncher(overrides='--ntasks-per-node=3')
                                                             )
                                      )
myconfig = Config(executors=[my_executor])
parsl.load(myconfig)

@python_app
def test():
    print("hello")

task = test()
task.result()
```

**Expected behavior**
I would expect the task to complete normally.

**Environment**
 - OS: Ubuntu 22.04
 - Python 3.8.10
 - Parsl 1.3.0

**Distributed Environment**
- Where are you running the Parsl script from ? Laptop
- Where do you need the workers to run ? Compute nodes.

**Comment by KerneyJ** [comment]
I ran into a similar issue

my executor looks like this
```python
executor = HighThroughputExecutor(
            provider=LocalProvider(
                init_blocks=int(args.blocks),
                max_blocks=int(args.blocks),
                min_blocks=int(args.blocks),
                nodes_per_block=1,
                channel=SSHChannel(
                    hostname="xxxxxx",
                    username="xxxxxx",
                    key_filename="xxxxxx",
                    script_dir="xxxxxx",
                ),
            )
        )
```
Originally I did not provide a script_dir argument, and I would get the error
```python
parsl.executors.errors.BadStateException: Executor HighThroughputExecutor failed due to: 1. Failed to start block 0: ('xxxxxx/runinfo/779/local_submit_scripts/parsl.localprovider.1687727239.71123.sh', FileNotFoundError(2, 'No such file or directory'))
```
And the runinfo directory on the server machine would be contain a directory remote_submit_scripts, which was empty.
After providing a script_dir argument all of the scripts are spawned in that directory and I get a new error stating that Parsl could not find the executor process_worker_pool.py on the server machine. I copied a version of process_worker_pool onto the server and changed the launch_cmd string to point to the process_worker_pool.py that I copied over i.e.
```python
# parsl/executors/high_throughput/executor.py
self.launch_cmd = "process_worker_pool.py ..." # original
```
```python
# parsl/executors/high_throughput/executor.py
self.launch_cmd = "xxxxxx/process_worker_pool.py ..." # new
```
After that I have a new error
```python
        STDERR: Traceback (most recent call last):
  File "xxxxxx/process_worker_pool.py", line 688, in <module>
    os.makedirs(os.path.join(args.logdir, "block-{}".format(args.block_id), args.uid), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 7 more times]
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'yyyyyy'
```
where xxxxxx is a directory that exists on the server machine and yyyyyy is a directory that exist on the client machine. The  above snippet has to do with creating a log directory o the remote machine and after commenting out I get errors saying the symbol logger has not been defined when I comment out line that references logger I get some unrelated issue.

All that being said, what it seems like to me is that Parsl is assuming that the server machine and client machine have filesystems with the same namespace. Which explains Parsl is trying to create log files in directory yyyyyy(client directory).

**Comment by benclifford** [comment]
pleases see issue #3515 about removing channels from Parsl
