### ISSUE TITLE
KeyError raised when visualizing workflow graph with tasks in 'running_ended' state

### ISSUE THREAD

**Issue by mxk62** [Parsl/parsl#2681]
**Describe the bug**

Clicking "View workflow DAG -- colored by task states" on workflow summary page results in an "Internal Server Error" if there are tasks in `running_ended` state. When run in the debug mode, `parsl-visualize` tool shows that the error is caused by **KeyError** exception raised by `workflow_dag_plot()` function. See the traceback below for more details:

```
Traceback (most recent call last):
  File "/home/mxk/.conda/envs/devenv/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/mxk/.conda/envs/devenv/lib/python3.10/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/home/mxk/.conda/envs/devenv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mxk/.conda/envs/devenv/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mxk/.conda/envs/devenv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mxk/.conda/envs/devenv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/mxk/lsst/git/parsl/parsl/monitoring/visualization/views.py", line 146, in workflow_dag_details
    workflow_dag_plot=workflow_dag_plot(df_tasks, group_by_apps=group_by_apps))
  File "/home/mxk/lsst/git/parsl/parsl/monitoring/visualization/plots/default/workflow_plots.py", line 259, in workflow_dag_plot
    index, _ = groups_list[name]
KeyError: 'running_ended'
```

**To Reproduce**

1. Setup Parsl 2023.05.01 with Python 3.10 on a desktop PC.
2. Start a Parsl workflow using HTEX with the monitoring enabled.
3. Start the web dashboard using `parsl-visualize` tool.
4. Open the dashboard in a web browser and select the running workflow to get to the workflow summary page.
5. Click "View workflow DAG -- colored by task states". If, _and only if_, there are tasks in `running_ended` state you'll get the error described above.

**Expected behavior**

See the workflow graph with tasks/nodes colored according to the state they are in.

**Environment**
 - OS: Rocky Linux 8
 - Python version: 3.10
 - Parsl version: 2023.05.01

**Distributed Environment**
- Where are you running the Parsl script from ? A desktop PC.
- Where do you need the workers to run ? Same as Parsl script.

**Comment by benclifford** [comment]
I recreated this on my laptop by running the test suite and then deleting all of the `exec_done` task states - so that many tasks will have `running_ended` as their final state:

```
sqlite3 runinfo/monitoring.db "delete from status where task_status_name='exec_done';"
```

This pull request fixes it in my environment: https://github.com/Parsl/parsl/pull/2708
