### ISSUE TITLE
Cleanup not working properly

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#271]
For example, running on the `tests-#128` branch:
```
pytest parsl/tests --config parsl/tests/configs/local_ipp.py
========================================== 50 passed, 100 skipped in 425.61 seconds ==========================================
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/awoodard/ci/parsl/parsl/dataflow/dflow.py", line 575, in cleanup
    executor.scale_in(len(job_ids))
  File "/Users/awoodard/ci/parsl/parsl/executors/ipp.py", line 243, in scale_in
    r = self.execution_provider.cancel(to_kill, *args, **kwargs)
  File "/Users/awoodard/software/anaconda3/envs/parsl_py36/lib/python3.6/site-packages/libsubmit-0.3.2-py3.6.egg/libsubmit/providers/local/local.py", line 240, in cancel
ProcessLookupError: [Errno 3] No such process
```

**Comment by annawoodard** [comment]
Note that when this is solved, we should be able to re-enable testing the IPP config on Travis (if #272 is merged).

**Comment by benclifford** [comment]
If this is coming from a duplicate shutdown (which it might be?) then #287 might be relevant.

**Comment by annawoodard** [comment]
To clarify this, the `ProcessLookupError` may be a red herring. The main issue here that needs to be resolved is that running with IPP often leaves orphan processes.

**Comment by yadudoc** [comment]
Closing since this is an IP
