### ISSUE TITLE
Race condition in htex scale-in at shutdown on ctrl-C

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#2755]
**Describe the bug**
When hitting ctrl-C to end a workflow, the main process begins its exit procedure. At the same time (at least in my environment), the interchange also terminates due to this ctrl-C.

As part of the main workflow process exit, the scaling shutdown code tries to scale in all blocks, so as to not leave them behind after execution.

Unfortunately, the implementation of scale-in tries to ask the interchange which managers it has available, as a (possibly unnecessary in this particular situation) part of deciding which blocks to scale in. This is implemented as this call:

```
    managers = self.command_client.run("MANAGERS")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

which is implemented with a ZMQ rpc that, if the remote of the rpc (the now exited interchange) is not available, waits until the remote of the rpc (the never-to-come-online-again interchange) comes online.

This causes a hang, with blocks still allocated. Here's the relevant stacktrace when I further ctrl-C out of the hung run.

```
Traceback (most recent call last):
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 1129, in atexit_cleanup
    self.cleanup()
  File "/home/benc/parsl/src/parsl/parsl/process_loggers.py", line 27, in wrapped
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 1197, in cleanup
    block_ids = executor.scale_in(len(job_ids))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benc/parsl/src/parsl/parsl/executors/high_throughput/executor.py", line 662, in scale_in
    managers = self.connected_managers()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benc/parsl/src/parsl/parsl/executors/high_throughput/executor.py", line 534, in connected_managers
    managers = self.command_client.run("MANAGERS")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This is probably part of a broader hang when the interchange goes away at any time during execution.

**To Reproduce**

This hangs for me:

```import parsl
parsl.set_stream_logger()

executor = parsl.HighThroughputExecutor(address="127.0.0.1")

config = parsl.Config(executors=[executor])

parsl.load(config)

executor.interchange_proc.kill()

print("exiting")
```

**Expected behavior**
ctrl-C should let me shut down a workflow - crossref #2174 

**Environment**
my laptop, parsl `master` facecead095d156445721cba1db2a77cb1384eec

**Comment by benclifford** [comment]
This is probably also related to #2627 - where scaling in only happens for blocks where some part of the block has registered with the interchange: in #2627 the list of blocks is acquired from the interchange and is therefore incomplete; in this issue, the list of blocks is acquried-but-hangs from the interchange.
