### ISSUE TITLE
Engines not restarting

### ISSUE THREAD

**Issue by reidmcy** [Parsl/parsl#283]
The controller dies (sometimes) when the engines crash on S3.

Here is the last lines of the engine log:
```ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fe8409f32f0>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado-5.0.2-py3.5-linux-x86_64.egg/tornado/ioloop.py", line 759, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.5/dist-packages/tornado-5.0.2-py3.5-linux-x86_64.egg/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipyparallel/controller/scheduler.py", line 325, in <lambda>
    lambda : self.handle_stranded_tasks(uid),
  File "/usr/local/lib/python3.5/dist-packages/ipyparallel/controller/scheduler.py", line 335, in handle_stranded_tasks
    for msg_id in lost.keys():
RuntimeError: dictionary changed size during iteration
2018-05-18 05:45:54.257 [IPControllerApp] task::task 'f1deb1b6-b37031dc55e5e6b59d3d7e2b' finished on 2
```

While parsl continues to run without any more updates. The last result was an engine exception: `RESULTS ERROR: EngineError(Engine b'05d9696c-90ff4acfd19e998391dc666f' died while running task 'f1deb1b6-b37031dc55e5e6b59d3d7e2b')`

**Comment by yadudoc** [comment]
Hey @reidmcy Can you paste you parsl.log and controlller log into gist and add a link here ?

**Comment by reidmcy** [comment]
The `parsl.log` is [here](https://gist.github.com/reidmcy/9d7b8f689d636f6def78e46cb259f733)
And the `Remote_IPP.controller.err` is [here](https://gist.github.com/reidmcy/3579daeafe309d8a4dcf42d7c5ec3fb6)

It looks like this is related to a known issue in [ipyparallel](https://github.com/ipython/ipyparallel/issues/203), I did have 1025 jobs running

**Comment by reidmcy** [comment]
I've run the script again `IPP.controller` will not restart engines even with many fewer jobs running. Going through my logs it seems like all 6 engines failed as time progressed, all on memory intensive tasks (e.g. one was trying to examine all the commits in the Rust source code)

**Comment by benclifford** [comment]
Closing, because this is about now-removed IPP executor
