### ISSUE TITLE
Parsl import error on Windows

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Parsl/parsl#2895]
**Describe the bug**
Parsl yields a `ValueError` upon importing on Windows.

```python
>>> import parsl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\asros\miniconda3\envs\parsl\lib\site-packages\parsl\__init__.py", line 22, in <module>
    from parsl.app.app import bash_app, join_app, python_app
  File "C:\Users\asros\miniconda3\envs\parsl\lib\site-packages\parsl\app\app.py", line 12, in <module>
    from parsl.dataflow.dflow import DataFlowKernel
  File "C:\Users\asros\miniconda3\envs\parsl\lib\site-packages\parsl\dataflow\dflow.py", line 26, in <module>
    from parsl.config import Config
  File "C:\Users\asros\miniconda3\envs\parsl\lib\site-packages\parsl\config.py", line 8, in <module>
    from parsl.executors.base import ParslExecutor
  File "C:\Users\asros\miniconda3\envs\parsl\lib\site-packages\parsl\executors\__init__.py", line 3, in <module>
    from parsl.executors.high_throughput.executor import HighThroughputExecutor
  File "C:\Users\asros\miniconda3\envs\parsl\lib\site-packages\parsl\executors\high_throughput\executor.py", line 20, in <module>
    from parsl.executors.high_throughput import interchange
  File "C:\Users\asros\miniconda3\envs\parsl\lib\site-packages\parsl\executors\high_throughput\interchange.py", line 24, in <module>
    from parsl.monitoring.message_type import MessageType
  File "C:\Users\asros\miniconda3\envs\parsl\lib\site-packages\parsl\monitoring\__init__.py", line 1, in <module>
    from parsl.monitoring.monitoring import MonitoringHub
  File "C:\Users\asros\miniconda3\envs\parsl\lib\site-packages\parsl\monitoring\monitoring.py", line 11, in <module>
    import parsl.monitoring.remote
  File "C:\Users\asros\miniconda3\envs\parsl\lib\site-packages\parsl\monitoring\remote.py", line 7, in <module>
    from parsl.multiprocessing import ForkProcess
  File "C:\Users\asros\miniconda3\envs\parsl\lib\site-packages\parsl\multiprocessing.py", line 15, in <module>
    ForkProcess: Type = multiprocessing.get_context('fork').Process
  File "C:\Users\asros\miniconda3\envs\parsl\lib\multiprocessing\context.py", line 243, in get_context
    return super().get_context(method)
  File "C:\Users\asros\miniconda3\envs\parsl\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'
```

**To Reproduce**
In a clean Python 3.10 miniconda environment, I ran `pip install parsl`. I then opened a Python console and ran `import parsl`.

**Expected behavior**
Parsl imports.

**Environment**
 - OS: Windows
 - Python version: 3.10.13
 - Parsl version: 2023.9.18

**Distributed Environment**
- Where are you running the Parsl script from ? Windows (local).
- Where do you need the workers to run ? N/A

**Comment by Andrew-S-Rosen** [comment]
Closed as duplicate of https://github.com/Parsl/parsl/issues/1878. Probably worth adding something to the docs or a classifier to `setup.py` though.
