### ISSUE TITLE
JobStatus is missing relevant stdout/err summary in SlurmProvider

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#3058]
**Describe the bug**

The `JobStatus` object reported by the provider on a `provider.status` call should be reporting information relevant to the submit scipts failure for better debugging. While the `LocalProvider` does this appropriately most cluster providers do not.

The SlurmProvider reports no stdout/stderr path when a job reaches a terminal state, and this means that the `stdout_summary` and `stderr_summary` is not filled in leading to poor exception messages., for eg:

```
ERROR    parsl.executors.status_handling:status_handling.py:141 Setting bad state due to exception
parsl.jobs.errors.TooManyJobFailuresError: Error 1:

INFO     parsl.dataflow.dflow:dflow.py:305 Task 0 try 0 failed with exception of type BadStateException
ERROR    parsl.dataflow.dflow:dflow.py:351 Task 0 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home1/02551/yadunand/parsl/parsl/dataflow/dflow.py", line 302, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/02551/yadunand/parsl/parsl/dataflow/dflow.py", line 570, in _unwrap_remote_exception_wrapper
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/home1/02551/yadunand/anaconda3/envs/parsl_py311/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home1/02551/yadunand/anaconda3/envs/parsl_py311/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
parsl.executors.errors.BadStateException: Executor HTEX failed due to: Error 1:
```

The LocalProvider on the other hand reports much more useful error messages, like this:
```
1707244405.623917 2024-02-06 12:33:25 MainProcess-90952 JobStatusPoller-Timer-Thread-140483421832336-13085667328 parsl.executors.status_handling:141 set_bad_state_and_fail_all ERROR: Setting bad state due to exception
parsl.jobs.errors.TooManyJobFailuresError: Error 1:
    EXIT CODE: 0
    STDERR:
CommandNotFoundError: Your shell has not been properly configured to use 'conda deactivate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


/tmp/test_htex/001/submit_scripts/parsl.HTEX.block-0.1707244400.5608902.sh: line 1: which: No such file or directory
```

**Expected behavior**

All Providers should be reporting the `stdout` and `stderr` from the submit scripts as part of the exception when a job fails.

**Comment by benclifford** [comment]
crossref #2949 as a similar-looking providers-losing-error-flow issue
