### ISSUE TITLE
local channel execute wait raises exception at scale during interpreter shutdown

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#3103]
**Describe the bug**

Related to previous bug #3102, I am seeing this at shutdown and noting here for future investigation - probably related to recent switch to Python 3.12.2+

```
Exception ignored in atexit callback: <bound method DataFlowKernel.atexit_cleanup of <parsl.dataflow.dflow.DataFlowKernel object at 0x7fd487cb4f50>>
Traceback (most recent call last):
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 1146, in atexit_cleanup
    self.cleanup()
  File "/home/benc/parsl/src/parsl/parsl/process_loggers.py", line 27, in wrapped
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 1218, in cleanup
    block_ids = executor.scale_in(len(job_ids))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benc/parsl/src/parsl/parsl/executors/high_throughput/executor.py", line 740, in scale_in
    r = self.provider.cancel(to_kill)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benc/parsl/src/parsl/parsl/providers/local/local.py", line 271, in cancel
    retcode, stdout, stderr = self.channel.execute_wait(cmd, self.cmd_timeout)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benc/parsl/src/parsl/parsl/channels/local/local.py", line 58, in execute_wait
    proc = subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1883, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
RuntimeError: preexec_fn not supported at interpreter shutdown
```

**Comment by benclifford** [comment]
pleases see issue #3515 about removing channels from Parsl
