### ISSUE TITLE
HTEX is slow to report broken config

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#3235]
**Describe the bug**

When I run a basic config on my laptop that uses the `SlurmProvider` incorrectly, Parsl detects the failure to find `sbatch` but tries about ~10 times and fails, before finally the periodic pollers kick in and detect that the executor has reached a bad state.

Here's my test script:
```
from parsl.providers import SlurmProvider
from parsl.executors import HighThroughputExecutor
from parsl import Config
from parsl import python_app
import parsl


config = Config(
    executors=[
        HighThroughputExecutor(
            label="Fake_broken_provider",
            provider=SlurmProvider(
                "debug",
                init_blocks=0,
            ),
        )
    ],
)
parsl.load(config)

@python_app
def double(x):
    return x * 2

future = double(5)
future.result()
```

Here's the output:
```
Traceback (most recent call last):
  File "/private/tmp/test.py", line 28, in <module>
    future.result()
  File "/Users/yadu/opt/anaconda3/envs/parsl_py3.9/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/Users/yadu/opt/anaconda3/envs/parsl_py3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/yadu/opt/anaconda3/envs/parsl_py3.9/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 302, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
  File "/Users/yadu/opt/anaconda3/envs/parsl_py3.9/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 570, in _unwrap_remote_exception_wrapper
    result = future.result()
  File "/Users/yadu/opt/anaconda3/envs/parsl_py3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/yadu/opt/anaconda3/envs/parsl_py3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
parsl.executors.errors.BadStateException: Executor Fake_broken_provider failed due to: Error 1:
	Failed to start block 0: Cannot launch job parsl.Fake_broken_provider.block-0.1710183543.7008908: Could not read job ID from submit command standard output; recode=127, stdout=, stderr=/bin/sh: sbatch: command not found

Error 2:
	Failed to start block 1: Cannot launch job parsl.Fake_broken_provider.block-1.1710183548.744912: Could not read job ID from submit command standard output; recode=127, stdout=, stderr=/bin/sh: sbatch: command not found

Error 3:
	Failed to start block 2: Cannot launch job parsl.Fake_broken_provider.block-2.1710183553.780223: Could not read job ID from submit command standard output; recode=127, stdout=, stderr=/bin/sh: sbatch: command not found

Error 4:
	Failed to start block 3: Cannot launch job parsl.Fake_broken_provider.block-3.1710183558.811934: Could not read job ID from submit command standard output; recode=127, stdout=, stderr=/bin/sh: sbatch: command not found

Error 5:
	Failed to start block 4: Cannot launch job parsl.Fake_broken_provider.block-4.1710183563.869496: Could not read job ID from submit command standard output; recode=127, stdout=, stderr=/bin/sh: sbatch: command not found

Error 6:
	Failed to start block 5: Cannot launch job parsl.Fake_broken_provider.block-5.1710183568.9372978: Could not read job ID from submit command standard output; recode=127, stdout=, stderr=/bin/sh: sbatch: command not found

Error 7:
	Failed to start block 6: Cannot launch job parsl.Fake_broken_provider.block-6.1710183574.0103118: Could not read job ID from submit command standard output; recode=127, stdout=, stderr=/bin/sh: sbatch: command not found

Error 8:
	Failed to start block 7: Cannot launch job parsl.Fake_broken_provider.block-7.1710183579.05152: Could not read job ID from submit command standard output; recode=127, stdout=, stderr=/bin/sh: sbatch: command not found

Error 9:
	Failed to start block 8: Cannot launch job parsl.Fake_broken_provider.block-8.1710183584.102874: Could not read job ID from submit command standard output; recode=127, stdout=, stderr=/bin/sh: sbatch: command not found

Error 10:
	Failed to start block 9: Cannot launch job parsl.Fake_broken_provider.block-9.1710183589.1441731: Could not read job ID from submit command standard output; recode=127, stdout=, stderr=/bin/sh: sbatch: command not found

Error 11:
	Failed to start block 10: Cannot launch job parsl.Fake_broken_provider.block-10.1710183594.2138948: Could not read job ID from submit command standard output; recode=127, stdout=, stderr=/bin/sh: sbatch: command not found

Error 12:
	Failed to start block 11: Cannot launch job parsl.Fake_broken_provider.block-11.1710183599.2518022: Could not read job ID from submit command standard output; recode=127, stdout=, stderr=/bin/sh: sbatch: command not found
```

**To Reproduce**
Steps to reproduce the behavior, for e.g:
1. Get latest parsl installed
2. Run the test script pasted above

**Expected behavior**
I expect the executor to fail with the `BadStateException` or similar after the first couple of jobs fails at submit.

**Distributed Environment**
- Laptop/NA.

**Comment by yadudoc** [comment]
Here's some additional info on this from my efforts to diagnose this. Automatic scaling is triggered by the `JobStatusPoller` which calls the `PollItem`. The `PollItem` oddly caches the the state of batch jobs and updates based on `Provider.status_polling_interval (default 60s)`, which leads to strategy being unaware of failed jobs until this status_polling_interval has passed.

**Comment by benclifford** [comment]
I made a patch for some other behaviour and realised that it might fix this problem too - Yadu tried it and it seems to. So I'll make a PR and post a crossref here later.
