### ISSUE TITLE
Fix transient `SystemExit` error with IPP config

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#330]
Running `pytest --config configs/local_ipp.py`, I see this intermittently:
```
Traceback (most recent call last):
  File "/Users/awoodard/ci/parsl/parsl/dataflow/dflow.py", line 191, in handle_update
    res = future.result()
  File "/Users/awoodard/software/anaconda3/envs/parsl_py36/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/Users/awoodard/software/anaconda3/envs/parsl_py36/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/Users/awoodard/software/anaconda3/envs/parsl_py36/lib/python3.6/site-packages/ipyparallel/client/asyncresult.py", line 224, in _resolve_result
    raise r
ipyparallel.error.RemoteError: SystemExit(-1)
```
We need to figure out what is causing this. Note as a stop-gap measure, CI is currently running `pytest --config local` instead of `pytest --config basic`, which would include the `local_ipp.py` config. We should consider this issue fixed when we can switch travis back to running `pytest --config basic`.

**Comment by benclifford** [comment]
How intermittent (on a percentage-of-runs scale) do you see this?

**Comment by yadudoc** [comment]
Closing. Not an issue anymore.
