### ISSUE TITLE
workqueue atexit cleanup raises an error with Python 3.12 when actually cleaning up

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#3334]
**Describe the bug**

If Work Queue has no been cleaned up by the time this test process exits, for example due to some exception during development:
```
$ pytest parsl/tests/ --config parsl/tests/configs/workqueue_ex.py 
```

then this stack trace appears:

```
Traceback (most recent call last):
  File "/home/benc/parsl/src/parsl/parsl/executors/workqueue/executor.py", line 317, in atexit_cleanup
    self.shutdown()
  File "/home/benc/parsl/src/parsl/parsl/executors/workqueue/executor.py", line 733, in shutdown
    self.provider.cancel(kill_ids)
  File "/home/benc/parsl/src/parsl/parsl/providers/local/local.py", line 271, in cancel
    retcode, stdout, stderr = self.channel.execute_wait(cmd, self.cmd_timeout)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benc/parsl/src/parsl/parsl/channels/local/local.py", line 58, in execute_wait
    proc = subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1883, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
RuntimeError: preexec_fn not supported at interpreter shutdown
```

Parsl removed atexit handling because of this sort of thing in PR #3165; but PR #3269 added this back in for Work Queue and Task Vine with the claim that "These handlers never spawn new threads or processes" - which looks like it is incorrect.

I think there are more circumstances where this would appear beyond running Pytest against broken local changes, but I have not dug into creating a reproduction case.

**Comment by benclifford** [comment]
cc @tphung3

**Comment by tphung3** [comment]
It looks like the providers fork some cleanup processes when cancelling blocks. Working on it..

**Comment by tphung3** [comment]
More than half of the providers use `self.execute_wait` to remove jobs, which spawns a new process running a shell cmd. Since it seems unavoidable, `atexit` handlers should be removed.

**Comment by tphung3** [comment]
On a related note, does parsl dfk work with the `with` context now? I see `__enter__` and `__exit__` methods for the dfk @benclifford.

**Comment by benclifford** [comment]
@tphung3 yeah, `with` context management was introduced in #3260 basically as an attempt to salvage this shutdown behaviour, but requiring a little more user engagement. Here's an example from the test suite:

```
    with parsl.load(config=config) as dfk:
        assert isinstance(dfk, DataFlowKernel)

        bash_future = foo(1, stdout=tmpd_cwd / 'foo.stdout')
        assert bash_future.result() == 0

        with open(tmpd_cwd / 'foo.stdout', 'r') as f:
            assert f.read() == "2\n"
```

On the positive side, `__exit__` gets more exception information than `atexit` handlers do, and I hope that can lead to some more interesting optional "wait for all tasks unless there's an exception, in which case don't wait for all tasks" shutdown behaviour, to address a common usability problem.
