### ISSUE TITLE
Provide more info for AppFailure with bash_apps + IPP

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#359]
This is not very helpful:

```
2018-06-27 11:07:58 parsl.dataflow.dflow:163 [ERROR]  Task 0 failed
Traceback (most recent call last):
  File "/home/annawoodard/parsl/parsl/dataflow/dflow.py", line 158, in handle_update
    res = future.result()
  File "/home/annawoodard/.conda/envs/parsl_py36/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/annawoodard/.conda/envs/parsl_py36/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/annawoodard/.conda/envs/parsl_py36/lib/python3.6/site-packages/ipyparallel-6.2.1-py3.6.egg/ipyparallel/client/asyncresult.py", line 226, in _resolve_result
    raise r
ipyparallel.error.RemoteError: AppFailure()    return self.__get_result()

  File "/home/annawoodard/.conda/envs/parsl_py36/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
ERROR:parsl.dataflow.dflow:Task 0 failed
Traceback (most recent call last):
  File "/home/annawoodard/parsl/parsl/dataflow/dflow.py", line 158, in handle_update
    res = future.result()
  File "/home/annawoodard/.conda/envs/parsl_py36/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/annawoodard/.conda/envs/parsl_py36/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/annawoodard/.conda/envs/parsl_py36/lib/python3.6/site-packages/ipyparallel-6.2.1-py3.6.egg/ipyparallel/client/asyncresult.py", line 226, in _resolve_result
    raise r
ipyparallel.error.RemoteError: AppFailure()
2018-06-27 11:07:58 parsl.dataflow.dflow:180 [INFO]  Task 0 failed after 0 retry attempts
INFO:parsl.dataflow.dflow:Task 0 failed after 0 retry attempts
    raise self._exception
  File "/home/annawoodard/parsl/parsl/dataflow/dflow.py", line 158, in handle_update
    res = future.result()
  File "/home/annawoodard/.conda/envs/parsl_py36/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/annawoodard/.conda/envs/parsl_py36/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/annawoodard/.conda/envs/parsl_py36/lib/python3.6/site-packages/ipyparallel-6.2.1-py3.6.egg/ipyparallel/client/asyncresult.py", line 226, in _resolve_result
    raise r
ipyparallel.error.RemoteError: AppFailure()
```

**Comment by annawoodard** [comment]
Oops, this was duplicated with #433.
