### ISSUE TITLE
stage_in tasks assume a global DFK

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#381]
To recreate: the below code works when `myfile` is set to a local file; but fails when an `https` URL is used.

The http staging code is run through a parsl `@app` which is not passed a DFK and instead assumes the presence of a globally defined DFK.

The stack trace I get is pasted below.

```
#!/usr/bin/env python3

import parsl
from parsl import File
from parsl import DataFlowKernel
from parsl.config import *
from parsl.app.app import bash_app

parsl.set_stream_logger()

c = Config(executors=[ThreadPoolExecutor()])

dfk = DataFlowKernel(config = c)

@bash_app(data_flow_kernel = dfk)
def foo(inputs=[]):
  return ("ls ; echo {} ; [ -f {} ] ".format(inputs[0], inputs[0]))


myfile = File("https://i.kinja-img.com/gawker-media/image/upload/s--Y-cQAB3F--/c_fill,f_auto,fl_progressive,g_center,h_358,q_80,w_636/uxjoxumsdokcy5fh67t6.jpg")
# myfile = 'tmp.txt'

future = foo(inputs=[myfile])

print("RESULT: {}".format(future.result()))
```

```
Traceback (most recent call last):
  File "./c.py", line 23, in <module>
    future = foo(inputs=[myfile])
  File "/home/benc/parsl/src/parsl/parsl/app/app_factory.py", line 76, in __call__
    return app_obj(*args, **kwargs)
  File "/home/benc/parsl/src/parsl/parsl/app/bash_app.py", line 150, in __call__
    **self.kwargs)
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 552, in submit
    self._add_input_deps(executor, args, kwargs)
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 384, in _add_input_deps
    inputs[idx] = f.stage_in(executor)
  File "/home/benc/parsl/src/parsl/parsl/data_provider/files.py", line 90, in stage_in
    return self.dman.stage_in(self, executor)
  File "/home/benc/parsl/src/parsl/parsl/data_provider/data_manager.py", line 132, in stage_in
    app_fut = stage_in_app(working_dir, outputs=[file])
  File "/home/benc/parsl/src/parsl/parsl/app/app_factory.py", line 76, in __call__
    return app_obj(*args, **kwargs)
  File "/home/benc/parsl/src/parsl/parsl/app/python_app.py", line 44, in __call__
    self.data_flow_kernel = DataFlowKernelLoader.dfk()
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 906, in dfk
    raise RuntimeError('Must first load config')
```

**Comment by yadudoc** [comment]
This code bit is slightly broken 
```

c = Config(executors=[ThreadPoolExecutor()])
#dfk = DataFlowKernel(config = c)
parsl.load(c) # This is the new style.

**Comment by benclifford** [comment]
cross reference #412
