### ISSUE TITLE
GlobusScheme config example problems

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#413]
`userguide/data.rst` contains an example config using GlobusScheme, very similar to `parsl/tests/configs/local_threads_globus.py`.

- [ ] the `data.rst` version refers to `parsl.data_provider` instead of `parsl.data_manager` as a module to import from

- [ ] when I load either (with adjustments for previous point, or to add `user_data`), I get:

```
$ python c1.py
Traceback (most recent call last):
  File "c1.py", line 12, in <module>
    local_path="/home/user"
  File "/home/benc/parsl/src/parsl/parsl/executors/ipp.py", line 89, in __init__
    if len(self.storage_access) > 1:
TypeError: object of type 'GlobusScheme' has no len()
```

It's unclear to me which type(s) the `storage_access` field is expected to contain: sometimes it is checked for None, sometimes it is assigned a list, and sometimes it's assigned GlobusScheme directly.

**Comment by benclifford** [comment]
I suspect the correct answer is that storage_access should always be a list, containing zero or more values of any type - and the config example should be supplying a single-element list with a GlobusScheme in it.
