### ISSUE TITLE
IPyparallel failure when submitting several apps in parallel threads

### ISSUE THREAD

**Issue by EiffL** [Parsl/parsl#451]
I'm having an issue when starting several apps roughly at the same time, within different python threads, with the `IPyParallelExecutor/SlurmProvider`. I get this kind of exceptions:
```
Traceback (most recent call last):
  File "/global/homes/f/flanusse/.local/lib/python3.6/site-packages/cwlparsl/command_line_tool.py", line 195, in _parsl_execute
    name=self.name)
  File "/global/homes/f/flanusse/.local/lib/python3.6/site-packages/cwlparsl/command_line_tool.py", line 89, in _job_popen
    proc = run_process(job_dir, job_script, stdout=f"{job_dir}/{name}.out", stderr=f"{job_dir}/{name}.err")
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/lib/python3.6/site-packages/parsl/app/app_factory.py", line 76, in __call__
    return app_obj(*args, **kwargs)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/lib/python3.6/site-packages/parsl/app/bash_app.py", line 150, in __call__
    **self.kwargs)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/lib/python3.6/site-packages/parsl/dataflow/dflow.py", line 581, in submit
    task_id, func, *new_args, **kwargs)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/lib/python3.6/site-packages/parsl/dataflow/dflow.py", line 353, in launch_task
    exec_fu = executor.submit(executable, *args, **kwargs)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/lib/python3.6/site-packages/parsl/executors/ipp.py", line 228, in submit
    return self.lb_view.apply_async(*args, **kwargs)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/lib/python3.6/site-packages/ipyparallel/client/view.py", line 220, in apply_async
    return self._really_apply(f, args, kwargs, block=False)
  File "<decorator-gen-137>", line 2, in _really_apply
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/lib/python3.6/site-packages/ipyparallel/client/view.py", line 49, in sync_results
    return f(self, *args, **kwargs)
  File "<decorator-gen-136>", line 2, in _really_apply
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/lib/python3.6/site-packages/ipyparallel/client/view.py", line 37, in save_ids
    ret = f(self, *args, **kwargs)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/lib/python3.6/site-packages/ipyparallel/client/view.py", line 1042, in _really_apply
    metadata=metadata)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/lib/python3.6/site-packages/ipyparallel/client/client.py", line 1418, in send_apply_request
    item_threshold=self.session.item_threshold,
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/lib/python3.6/site-packages/ipyparallel/serialize/serialize.py", line 179, in pack_apply_message
    serialize_object(arg, buffer_threshold, item_threshold) for arg in args))
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/lib/python3.6/site-packages/ipyparallel/serialize/serialize.py", line 179, in <genexpr>
    serialize_object(arg, buffer_threshold, item_threshold) for arg in args))
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/lib/python3.6/site-packages/ipyparallel/serialize/serialize.py", line 122, in serialize_object
    cobj = can(obj)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/lib/python3.6/site-packages/ipyparallel/serialize/canning.py", line 398, in can
    _import_mapping(can_map, _original_can_map)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/lib/python3.6/site-packages/ipyparallel/serialize/canning.py", line 368, in _import_mapping
    mapping[cls] = mapping.pop(key)
KeyError: 'numpy.ndarray'
```
I have looked at the source code of ipyparallel but couldn't figure out exactly why this happens. If I had to  guess I would say ipyparallel has some cache it uses for object serialization, and when different threads are accessing it at the same time, things get ugly, but that's a wild guess.

Here is the configuration I'm using: 
```
slurm_config = Config(
    executors=[
        IPyParallelExecutor(
            label='ipp_slurm',
            provider=SlurmProvider(
                'debug',
                nodes_per_block=1,
                tasks_per_node=64,
                init_blocks=1,
                max_blocks=1,
                overrides="#SBATCH --constraint=haswell"
            )
        )
    ]
)
```

Interestingly enough, if I add a thread lock surrounding the call to the parsl_app, everything woks fine.

**Comment by annawoodard** [comment]
Thanks for the report, EiffL! Would it be possible to provide an example script which reproduces the problem? That would speed up our investigation.

**Comment by EiffL** [comment]
hum... Sorry Anna, I would have provided an example if it were easy, but it's not from a standalone script, this is happening deep inside a tool I'm building around parsl. I would take me a while to build a mwe from scratch...

**Comment by yadudoc** [comment]
@EiffL I've not has a chance to confirm this behavior, but `mapping[cls] = mapping.pop(key)` is probably not a thread safe operation. If multiple threads try to pop the same key, you might get a KeyError.
Locking as you've done is the obvious solution. Do you have an performance or concerns from locking ? I wonder if you assume to have many short running (<1s) tasks that might be impacted by not being able to launch in parallel ?

**Comment by yadudoc** [comment]
Okay great, so locking on your side addresses this problem. In Parsl, we've been working under the assumption that the calling side is single threaded and that all the parallelism is expressed in the execution side. Thanks for bringing this issue to our attention.
