### ISSUE TITLE
PROBLEM: not the correct partition, error message is misleading

### ISSUE THREAD

**Issue by sdustrud** [Parsl/parsl#458]
from libsubmit.channels import SSHChannel
from libsubmit.providers import SlurmProvider
from libsubmit.launchers import SrunLauncher

from parsl.config import Config
from parsl.executors.ipp import IPyParallelExecutor
from parsl.executors.ipp_controller import Controller

parsl.set_stream_logger()

config = Config(
    executors=[
        IPyParallelExecutor(
            label='monsoon',
            provider=SlurmProvider(
                'wrong-partition',
#                launcher=SrunLauncher(),
                overrides='source activate parsl-test',
                walltime="00:05:00",
                init_blocks=1,
                max_blocks=1,
                nodes_per_block=2,
                tasks_per_node=1,
            ),
#            controller=Controller(public_ip=''),
        )

    ],
)
parsl.clear()
parsl.load(config)

2018-08-10 07:44:20 parsl.config:66 [DEBUG]  Checkpoint period only has an effect with checkpoint_mode='periodic'
2018-08-10 07:44:20 parsl.dataflow.dflow:73 [DEBUG]  Starting DataFlowKernel with config
Config(
    app_cache=True, 
    checkpoint_files=None, 
    checkpoint_mode=None, 
    checkpoint_period='00:30:00', 
    data_management_max_threads=10, 
    db_logger_config=None, 
    executors=[IPyParallelExecutor(
        container_image=None, 
        controller=Controller(
            interfaces=None, 
            ipython_dir='/scratch/snd73/parsl/hackathon/runinfo/007', 
            log=True, 
            mode='auto', 
            port=None, 
            port_range=None, 
            profile='monsoon', 
            public_ip=None, 
            reuse=False
        ), 
        engine_debug_level=None, 
        engine_dir='.', 
        engine_file='~/.ipython/profile_default/security/ipcontroller-engine.json', 
        label='monsoon', 
        managed=True, 
        provider=SlurmProvider(
            'westmere',
            channel=LocalChannel(
                envs={}, 
                script_dir='/scratch/snd73/parsl/hackathon/.scripts', 
                userhome='/scratch/snd73/parsl/hackathon'
            ), 
            cmd_timeout=10, 
            init_blocks=1, 
            label='slurm', 
            launcher=<libsubmit.launchers.launchers.SrunLauncher object at 0x7fba11d693c8>, 
            max_blocks=1, 
            min_blocks=0, 
            nodes_per_block=2, 
            overrides='source activate parsl-test', 
            parallelism=1, 
            script_dir='parsl_scripts', 
            tasks_per_node=1, 
            walltime=6
        ), 
        storage_access=[], 
        working_dir=None
    )], 
    lazy_errors=True, 
    retries=0, 
    run_dir='runinfo', 
    strategy='simple', 
    usage_tracking=True
)
2018-08-10 07:44:20 parsl.dataflow.rundirs:36 [DEBUG]  Parsl run initializing in rundir:runinfo/008
2018-08-10 07:44:20 parsl.dataflow.dflow:78 [INFO]  Parsl version: 0.6.1
2018-08-10 07:44:20 parsl.dataflow.dflow:79 [INFO]  Libsubmit version: 0.5.0
2018-08-10 07:44:20 parsl.dataflow.usage_tracking.usage:126 [DEBUG]  Tracking status: True
2018-08-10 07:44:20 parsl.dataflow.usage_tracking.usage:127 [DEBUG]  Testing mode   : False
2018-08-10 07:44:20 parsl.dataflow.dflow:95 [INFO]  Run id is: /home/snd73/.conda/envs/parsl-test/lib/python3.5/site-packages/parsl/dataflow/dflow.py-44
2018-08-10 07:44:20 parsl.dataflow.memoization:52 [INFO]  App caching initialized
2018-08-10 07:44:20 parsl.executors.ipp_controller:83 [DEBUG]  Starting ipcontroller with 'ipcontroller --ipython-dir=/scratch/snd73/parsl/hackathon/runinfo/008 --ip=* --profile=monsoon   '
2018-08-10 07:44:21 parsl.executors.ipp:105 [DEBUG]  Waiting for /scratch/snd73/parsl/hackathon/runinfo/008/profile_monsoon/security/ipcontroller-client.json
2018-08-10 07:44:21 parsl.executors.ipp:122 [DEBUG]  Starting IPyParallelExecutor with provider:
SlurmProvider(
    'westmere',
    channel=LocalChannel(
        envs={}, 
        script_dir='/scratch/snd73/parsl/hackathon/.scripts', 
        userhome='/scratch/snd73/parsl/hackathon'
    ), 
    cmd_timeout=10, 
    init_blocks=1, 
    label='slurm', 
    launcher=<libsubmit.launchers.launchers.SrunLauncher object at 0x7fba11d693c8>, 
    max_blocks=1, 
    min_blocks=0, 
    nodes_per_block=2, 
    overrides='source activate parsl-test', 
    parallelism=1, 
    script_dir='parsl_scripts', 
    tasks_per_node=1, 
    walltime=6
)
2018-08-10 07:44:23 parsl.executors.ipp:127 [DEBUG]  Launched block: 0:None
2018-08-10 07:44:23 parsl.executors.ipp:134 [ERROR]  Scaling out failed: Executor slurm failed due to Attempts to provision nodes via provider has failed

Submission of command to scale_out failed

---------------------------------------------------------------------------
ScalingFailed                             Traceback (most recent call last)
<ipython-input-3-d6508f842944> in <module>()
     29 )
     30 parsl.clear()
---> 31 parsl.load(config)

~/.conda/envs/parsl-test/lib/python3.5/site-packages/parsl/dataflow/dflow.py in load(cls, config)
    896         if cls._dfk is not None:
    897             raise RuntimeError('Config has already been loaded')
--> 898         cls._dfk = DataFlowKernel(config)
    899 
    900         return cls._dfk

~/.conda/envs/parsl-test/lib/python3.5/site-packages/parsl/dataflow/dflow.py in __init__(self, config)
    119         for executor in self.executors.values():
    120             executor.run_dir = self.run_dir  # FIXME we should have a real interface for this
--> 121             executor.start()
    122 
    123         if self.checkpoint_mode == "periodic":

~/.conda/envs/parsl-test/lib/python3.5/site-packages/parsl/executors/ipp.py in start(self)
    133                 except Exception as e:
    134                     logger.error("Scaling out failed: %s" % e)
--> 135                     raise e
    136 
    137         else:

~/.conda/envs/parsl-test/lib/python3.5/site-packages/parsl/executors/ipp.py in start(self)
    128                         if not engine:
    129                             raise(ScalingFailed(self.provider.label,
--> 130                                                 "Attempts to provision nodes via provider has failed"))
    131                         self.engines.extend([engine])
    132 

ScalingFailed: Executor slurm failed due to Attempts to provision nodes via provider has failed

**Comment by kylechard** [comment]
This will likely be improved with integrated libsubmit error logging.  Related to #387

**Comment by annawoodard** [comment]
It looks like the libsubmit merge has improved the situation (namely, by making sure the provider logging is enabled when the user enables parsl logging). 

Using the following test script with a bogus queue name:
```
from requests import get

import parsl
from parsl.config import Config
from parsl.app.app import python_app
from parsl.executors import HighThroughputExecutor
from parsl.providers.slurm.slurm import SlurmProvider
from parsl.launchers import SimpleLauncher

htex = Config(
    executors=[
        HighThroughputExecutor(
            label="midway_htex",
            worker_debug=True,
            cores_per_worker=1,
            public_ip=get('https://api.ipify.org').text,
            provider=SlurmProvider(
                'foobar',
                launcher=SimpleLauncher()
            ),
        )
    ],
    strategy=None,
)

parsl.set_stream_logger()
parsl.load(htex)

@python_app
def sleep(seconds):
    import time
    time.sleep(seconds)

tasks = [sleep(0) for _ in range(0, 10)]
for task in tasks:
    task.result()
```
the user will see the following in the parsl log:
```
2018-11-01 19:34:06 parsl.providers.slurm.slurm:157 [DEBUG]  Requesting one block with 1 nodes
2018-11-01 19:34:06 parsl.providers.slurm.slurm:173 [DEBUG]  Writing submit script
Submission of command to scale_out failed
2018-11-01 19:34:06 parsl.providers.slurm.slurm:188 [ERROR]  Retcode:1 STDOUT: STDERR:sbatch: error: invalid partition specified: foobar
sbatch: error: Batch job submission failed: Invalid partition name specified
2018-11-01 19:34:06 parsl.executors.high_throughput.executor:179 [DEBUG]  Launched block 0:None
2018-11-01 19:34:06 parsl.executors.high_throughput.executor:186 [ERROR]  Scaling out failed: ('slurm', 'Attempts to provision nodes via provider has failed')
Traceback (most recent call last):
  File "fixed.py", line 44, in <module>
    parsl.load(htex)
  File "/home/annawoodard/parsl/parsl/dataflow/dflow.py", line 957, in load
    cls._dfk = DataFlowKernel(config)
  File "/home/annawoodard/parsl/parsl/dataflow/dflow.py", line 171, in __init__
    executor.start()
  File "/home/annawoodard/parsl/parsl/executors/high_throughput/executor.py", line 187, in start
    raise e
  File "/home/annawoodard/parsl/parsl/executors/high_throughput/executor.py", line 182, in start
    "Attempts to provision nodes via provider has failed"))
parsl.executors.errors.ScalingFailed: ('slurm', 'Attempts to provision nodes via provider has failed')
```

Which does convey the critical "sbatch: error: Batch job submission failed: Invalid partition name specified" line. I'm closing for now, we can re-open if needed.
