### ISSUE TITLE
Error when IPP is not installed

### ISSUE THREAD

**Issue by kylechard** [Parsl/parsl#61]
It would be nice if Parsl could catch this error and relay something useful to the user. Like install IPP. 

Traceback (most recent call last):
  File "/home/chard/parsl-source/parsl/parsl/dataflow/start_controller.py", line 87, in __init__
    self.proc = subprocess.Popen(opts, stdout=stdout, stderr=stderr, preexec_fn=os.setsid)
  File "/home/chard/miniconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/chard/miniconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ipcontroller': 'ipcontroller'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simple-parsl.py", line 39, in <module>
    dfk = DataFlowKernel(config=ipp_config)
  File "/home/chard/parsl-source/parsl/parsl/dataflow/dflow.py", line 66, in __init__
    self.controller_proc = Controller(**self.config["controller"])
  File "/home/chard/parsl-source/parsl/parsl/dataflow/start_controller.py", line 91, in __init__
    raise ControllerErr(msg)
parsl.dataflow.error.ControllerErr: Controller init failed:Reason:IPPController failed to start: [Errno 2] No such file or directory: 'ipcontroller': 'ipcontroller'

**Comment by yadudoc** [comment]
I've added a clearer error message to catch this situation in the multisite branch. However, I'm a bit curious as to how you saw this message. In the DFK initialization stage we import ipyparallel, and your script should've exited far earlier if ipyparallel was not available from the pythonpath. So, I suspect that your env must've been thoroughly clobbered to have the right pythonpath but not have the PATH variable include the executables "ipcontroller", "ipengine". Please re-open if you think this issue is not resolved.
