### ISSUE TITLE
Network is unreachable exception from usage_tracking module

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#70]
When a parsl script is executed on a system without network connectivity, the usage_tracking module throws a Network is unreachable exception. This should be caught and silently handled.

======================================================================
ERROR: Failure: OSError ([Errno 101] Network is unreachable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/lib/python3.5/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python3.5/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python3.5/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/yadu/src/parsl/parsl/tests/test_data/test_file_apps.py", line 10, in <module>
    dfk = DataFlowKernel(executors=[workers])
  File "/home/yadu/src/parsl/parsl/dataflow/dflow.py", line 75, in __init__
    self.usage_tracker.send_message()
  File "/home/yadu/src/parsl/parsl/dataflow/usage_tracking/usage.py", line 159, in send_message
    x = self.send_UDP_message(message)
  File "/home/yadu/src/parsl/parsl/dataflow/usage_tracking/usage.py", line 137, in send_UDP_message
    x = sock.sendto(bytes(message, "utf-8"), (self.UDP_IP, self.UDP_PORT))
OSError: [Errno 101] Network is unreachable

----------------------------------------------------------------------

**Comment by yadudoc** [comment]
A reasonable error message is now presented to the user.
