### ISSUE TITLE
Exception BadStdFileStream in a bash-app does not get returned correctly due to subsequent exception

### ISSUE THREAD

**Issue by mjwilde** [Parsl/parsl#796]
For example, setting stdout= to a file name with an invalid directory path causes a chained exception similar to the following, instead of raising and returning an informative BadStdFileStream error as intended.

Traceback (most recent call last):
  File "/home/wilde/parslab/parsl_env/lib/python3.5/site-packages/parsl/dataflow/dflow.py", line 258, in handle_exec_update
    res.reraise()
  File "/home/wilde/parslab/parsl_env/lib/python3.5/site-packages/parsl/app/errors.py", line 149, in reraise
    reraise(dill.loads(self.e_type), dill.loads(self.e_value), self.e_traceback.as_traceback())
  File "/home/wilde/parslab/parsl_env/lib/python3.5/site-packages/dill/dill.py", line 299, in loads
    return load(file)
  File "/home/wilde/parslab/parsl_env/lib/python3.5/site-packages/dill/dill.py", line 288, in load
    obj = pik.load()
TypeError: __init__() missing 2 required positional arguments: 'outputs' and 'exception'

**Comment by benclifford** [comment]
crossref #785 #548

**Comment by benclifford** [comment]
should be fixed by PR #797
