### ISSUE TITLE
parsl hangs at shutdown if htex has been underutilised

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#818]
The below code produces the following shutdown hang. This is an isolation of a problem encountered by @villarrealas in DESC imsim production.

I think what's happening is that after a couple of minutes of idleness, part of htex is shutting down due to that idleness; but failing to properly remember that; later on, failure to kill that process (because it has gone already) is not dealt with well.

```
import time
import parsl
from parsl.configs.htex_local import config

parsl.load(config)

time.sleep(60)
print("1min")
time.sleep(60)
print("2min")
time.sleep(60)
print("3min")
time.sleep(60)
print("4min")
```

produces this output and then hangs:

```
1min
2min
3min
4min
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 778, in atexit_cleanup
    self.cleanup()
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 836, in cleanup
    executor.scale_in(len(job_ids))
  File "/home/benc/parsl/src/parsl/parsl/executors/high_throughput/executor.py", line 505, in scale_in
    r = self.provider.cancel(to_kill)
  File "/home/benc/parsl/src/parsl/parsl/providers/local/local.py", line 235, in cancel
    os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
ProcessLookupError: [Errno 3] No such process
```

**Comment by hategan** [comment]
I can't reproduce this. Is this still an issue for you?

**Comment by yadudoc** [comment]
I do not believe this is still an issue.
