### ISSUE TITLE
parsl workflow issue: AttributeError: 'ManagerLost' object has no attribute 'reraise'

### ISSUE THREAD

**Issue by TomGlanzman** [Parsl/parsl#851]
A parsl (v0.7.2) job at NERSC running on Cori-login (for top-level script) and Cori-knl for the (single node) batch work via the HighThroughputExecutor ran into the situation where the running SLURM job ran out of time.  There had been four tasks running in batch on the same node at the time.  The top-level script was silent, so I waited.  After a time, not knowing what was happening, I hit ctrl-c, which produced the following traceback:

```
Traceback (most recent call last):                                                                                              
  File "/global/u1/d/descdm/tomTest/parslTest3/BFworkflow.py", line 135, in <module>                                            
    print("rc = ",job.result())                                                                                                 
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_11/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/concurrent/futures/_base.py", line 432, in result                                                                                 
    return self.__get_result()                                                                                                  
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_11/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result                                                                           
    raise self._exception                                                                                                       
  File "/global/homes/d/descdm/.local/lib/python3.6/site-packages/parsl/dataflow/futures.py", line 126, in parent_callback      
    res = executor_fu.result()                                                                                                  
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_11/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/concurrent/futures/_base.py", line 425, in result                                                                                 
    return self.__get_result()                                                                                                  
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_11/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result                                                                           
    raise self._exception                                                                                                       
  File "/global/homes/d/descdm/.local/lib/python3.6/site-packages/parsl/dataflow/dflow.py", line 244, in handle_exec_update     
    res = future.result()                                                                                                       
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_11/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/concurrent/futures/_base.py", line 425, in result                                                                                 
    return self.__get_result()                                                                                                  
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_11/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result                                                                           
    raise self._exception                                                                                                       
  File "/global/homes/d/descdm/.local/lib/python3.6/site-packages/parsl/executors/high_throughput/executor.py", line 334, in _queue_management_worker                                                                                                           
    s.reraise()                                                                                                                 
AttributeError: 'ManagerLost' object has no attribute 'reraise' 
```

My expectation was that the workflow would grind to a halt after a batch timeout, which is why I thought the workflow script got stuck and hit ctrl-c.

Looking around in the various logs, it appears that Parsl decided to submit *four* new batch jobs in response to losing the first *one*.  This is surprising on two accounts.  First, I had not specified 'retry'.  Second, the Config was set up with:

```
            init_blocks=1,                                                                                                      
            max_blocks=1,                                                                                                       
            min_blocks=1,                                                                                                       
```

Being a newbie with parsl may explain my confusion, but am still wondering how one should abort a running workflow, and how to understand the mysterious submission of four new batch jobs?

**Comment by TomGlanzman** [comment]
Adding a tarball of the run directory for this issue.
[011.tar.gz](https://github.com/Parsl/parsl/files/3049129/011.tar.gz)

**Comment by TomGlanzman** [comment]
Update: Have run a new series of workflows and even when I allow the top-level script to complete without ctrl-c, I am still seeing this same problem, i.e.,

```
Traceback (most recent call last):
  File "/global/u1/d/descdm/tomTest/parslTest3/BFworkflow.py", line 169, in <module>
    print("rc = ",job.result())
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_11/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_11/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/global/homes/d/descdm/.local/lib/python3.6/site-packages/parsl/dataflow/futures.py", line 126, in parent_callback
    res = executor_fu.result()
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_11/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_11/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/global/homes/d/descdm/.local/lib/python3.6/site-packages/parsl/dataflow/dflow.py", line 244, in handle_exec_update
    res = future.result()
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_11/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_11/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/global/homes/d/descdm/.local/lib/python3.6/site-packages/parsl/executors/high_throughput/executor.py", line 334, in _queue_management_worker
    s.reraise()
AttributeError: 'ManagerLost' object has no attribute 'reraise'
```

Here is the config for the workflow:

```
parsl version =  0.7.2                             
2019-04-09 14:06:18.558035 : Parsl configuration setup complete
config =  Config(                                              
    app_cache=True,                                            
    checkpoint_files=None,                                     
    checkpoint_mode=None,                                      
    checkpoint_period=None,                                    
    data_management_max_threads=10,                            
    executors=[HighThroughputExecutor(                         
        address='cori10',                                      
        cores_per_worker='1',                                  
        heartbeat_period=30,                                   
        heartbeat_threshold=120,                               
        interchange_port_range=(55000, 56000),                 
        label='cori-1',                                        
        launch_cmd='process_worker_pool.py {debug} {max_workers} -c {cores_per_worker} --poll {poll_period} --task_url={task_url} --result_url={result_url} --logdir={logdir} --hb_period={heartbeat_period} --hb_threshold={heartbeat_threshold} ', 
        managed=True,                                                                                                                                                                                                                                
        max_workers=2,                                                                                                                                                                                                                               
        poll_period=10,                                                                                                                                                                                                                              
        provider=SlurmProvider(                                                                                                                                                                                                                      
            'regular',                                                                                                                                                                                                                               
            channel=LocalChannel(                                                                                                                                                                                                                    
                envs={},                                                                                                                                                                                                                             
                script_dir=None,                                                                                                                                                                                                                     
                userhome='/global/u1/d/descdm/tomTest/parslTest3'                                                                                                                                                                                    
            ),                                                                                                                                                                                                                                       
            cmd_timeout=90,                                                                                                                                                                                                                          
            exclusive=True,                                                                                                                                                                                                                          
            init_blocks=0,                                                                                                                                                                                                                           
            launcher=SingleNodeLauncher(),                                                                                                                                                                                                           
            max_blocks=1,                                                                                                                                                                                                                            
            min_blocks=1,                                                                                                                                                                                                                            
            move_files=True,                                                                                                                                                                                                                         
            nodes_per_block=1,                                                                                                                                                                                                                       
            parallelism=1,                                                                                                                                                                                                                           
            scheduler_options='#SBATCH --exclusive\n#SBATCH -L SCRATCH,projecta \n#SBATCH --constraint=knl',                                                                                                                                         
            walltime='02:00:00',                                                                                                                                                                                                                     
            worker_init='source /global/u1/d/descdm/tomTest/parslTest3/configTask.sh;export PATH=${PATH}:${HOME}/.local/bin;source /global/u1/d/descdm/tomTest/parslTest3/cvmfsSetup.sh;'                                                            
        ),                                                                                                                                                                                                                                           
        storage_access=[],                                                                                                                                                                                                                           
        suppress_failure=False,                                                                                                                                                                                                                      
        worker_debug=False,                                                                                                                                                                                                                          
        worker_port_range=(54000, 55000),                                                                                                                                                                                                            
        worker_ports=None,                                                                                                                                                                                                                           
        working_dir=None                                                                                                                                                                                                                             
    ), HighThroughputExecutor(                                                                                                                                                                                                                       
        address='cori10',                                                                                                                                                                                                                            
        cores_per_worker=2,                                                                                                                                                                                                                          
        heartbeat_period=30,                                                                                                                                                                                                                         
        heartbeat_threshold=120,                                                                                                                                                                                                                     
        interchange_port_range=(55000, 56000),                                                                                                                                                                                                       
        label='cori-2',                                                                                                                                                                                                                              
        launch_cmd='process_worker_pool.py {debug} {max_workers} -c {cores_per_worker} --poll {poll_period} --task_url={task_url} --result_url={result_url} --logdir={logdir} --hb_period={heartbeat_period} --hb_threshold={heartbeat_threshold} ', 
        managed=True,                                                                                                                                                                                                                                
        max_workers=2,                                                                                                                                                                                                                               
        poll_period=10,                                                                                                                                                                                                                              
        provider=SlurmProvider(                                                                                                                                                                                                                      
            'debug',                                                                                                                                                                                                                                 
            channel=LocalChannel(                                                                                                                                                                                                                    
                envs={},                                                                                                                                                                                                                             
                script_dir=None,                                                                                                                                                                                                                     
                userhome='/global/u1/d/descdm/tomTest/parslTest3'                                                                                                                                                                                    
            ),                                                                                                                                                                                                                                       
            cmd_timeout=90,                                                                                                                                                                                                                          
            exclusive=True,                                                                                                                                                                                                                          
            init_blocks=0,                                                                                                                                                                                                                           
            launcher=SingleNodeLauncher(),                                                                                                                                                                                                           
            max_blocks=1,                                                                                                                                                                                                                            
            min_blocks=1,                                                                                                                                                                                                                            
            move_files=True,                                                                                                                                                                                                                         
            nodes_per_block=1,                                                                                                                                                                                                                       
            parallelism=1,                                                                                                                                                                                                                           
            scheduler_options='#SBATCH --exclusive\n#SBATCH -L SCRATCH,projecta \n#SBATCH --constraint=haswell',                                                                                                                                     
            walltime='00:30:00',                                                                                                                                                                                                                     
            worker_init='source /global/u1/d/descdm/tomTest/parslTest3/configTask.sh;export PATH=${PATH}:${HOME}/.local/bin;source /global/u1/d/descdm/tomTest/parslTest3/cvmfsSetup.sh;'                                                            
        ),                                                                                                                                                                                                                                           
        storage_access=[],                                                                                                                                                                                                                           
        suppress_failure=False,                                                                                                                                                                                                                      
        worker_debug=False,                                                                                                                                                                                                                          
        worker_port_range=(54000, 55000),                                                                                                                                                                                                            
        worker_ports=None,                                                                                                                                                                                                                           
        working_dir=None                                                                                                                                                                                                                             
    )],                                                                                                                                                                                                                                              
    lazy_errors=True,                                                                                                                                                                                                                                
    monitoring=MonitoringHub(                                                                                                                                                                                                                        
        'cori10',                                                                                                                                                                                                                                    
        client_address='127.0.0.1',                                                                                                                                                                                                                  
        client_port_range=(55000, 56000),                                                                                                                                                                                                            
        hub_port=55055,                                                                                                                                                                                                                              
        hub_port_range=(55050, 56000),                                                                                                                                                                                                               
        logdir=None,                                                                                                                                                                                                                                 
        logging_endpoint='sqlite:///monitoring.db',                                                                                                                                                                                                  
        logging_level=20,                                                                                                                                                                                                                            
        resource_monitoring_enabled=True,                                                                                                                                                                                                            
        resource_monitoring_interval=60,                                                                                                                                                                                                             
        workflow_name=None,                                                                                                                                                                                                                          
        workflow_version=None                                                                                                                                                                                                                        
    ),                                                                                                                                                                                                                                               
    retries=0,                                                                                                                                                                                                                                       
    run_dir='runinfo',                                                                                                                                                                                                                               
    strategy='simple',                                                                                                                                                                                                                               
    usage_tracking=False                                                                                                                                                                                                                             
)      
```

**Comment by benclifford** [comment]
The `s.reraise` problem is that the result package that is passed between different parts of the High Throughput Executor isn't properly typed: some places the code sends an exception, but where the above `s.reraise()` problem occurs, that code is expecting the code to be a `RemoteExceptionWrapper`, not an exception.

If that gets fixed, there will be an underlying actual ManagerLost exception that is some underlying problem.

**Comment by benclifford** [comment]
@TomGlanzman can you try running your workflow against #856 ?  I am hoping that will give a different exception that more accurately reflects the underlying `ManagerLost` exception.

**Comment by TomGlanzman** [comment]
@benclifford I reran my workflow this morning.  As before, there are four tasks divided between two executors.  In an attempt to learn how Parsl deals with various situations, I manually killed two running user tasks (one each on the two active batch nodes).  Here is what happened.


1) The disposition of the four tasks is as follows:
   - KNL task killed
   - KNL task timed out (batch job ended prior to completion)
   - Haswell task killed
   - Haswell task completed successfully

2) the top-level workflow script never exited

3) the top-level workflow script did emit one traceback just before it went quiet:

Begin waiting for defined tasks to complete...
Process Process-3:
Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_11/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_11/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/global/homes/d/descdm/.local/lib/python3.6/site-packages/parsl/executors/high_throughput/interchange.py", line 490, in starter
    ic.start()
  File "/global/homes/d/descdm/.local/lib/python3.6/site-packages/parsl/executors/high_throughput/interchange.py", line 439, in start
    result_package = {'task_id': tid, 'exception': serialize_object(RemoteExceptionWrapper(e))}
TypeError: __init__() missing 2 required positional arguments: 'e_value' and 'traceback'

4) As before, there were more batch jobs generated than expected.  Here is a list of the jobs associated with this run of the workflow:

       JobID      User    JobName  Timelimit               Start                 End      State   NNodes        NodeList 
------------ --------- ---------- ---------- ------------------- ------------------- ---------- -------- --------------- 
20394247        descdm parsl.aut+   00:30:00 2019-04-11T07:51:42 2019-04-11T08:21:50    TIMEOUT        1        nid05946 
20394248        descdm parsl.aut+   00:30:00 2019-04-11T07:51:46 2019-04-11T08:21:51    TIMEOUT        1        nid02516 
20394250        descdm parsl.aut+   00:30:00 2019-04-11T07:49:38 2019-04-11T08:19:45    TIMEOUT        1        nid00699 
20394252        descdm parsl.aut+   00:30:00 2019-04-11T07:49:38 2019-04-11T08:19:45    TIMEOUT        1        nid00706 
20394688        descdm parsl.aut+   00:30:00 2019-04-11T08:24:00 2019-04-11T08:28:47  COMPLETED        1        nid05114 

5) I have retained all log files produced in the /runinfo/019 directory for this project

-----

My top-level script is still stuck and I will leave it that way in case you have any debugging suggestions.

  - Tom

**Comment by benclifford** [comment]
crossref #548 for the `TypeError: __init__() missing 2 required positional arguments: 'e_value' and 'traceback'` message

**Comment by TomGlanzman** [comment]
Adding one detail as an FYI.  As mentioned above, the top-level workflow script never existed.  Now, a couple of hours later, I find that the script is consuming a large amount of CPU time.  Here is a snippet from "top":

```
  PID USER      PR  NI    VIRT    RES    SHR S   %CPU  %MEM     TIME+ COMMAND
56536 descdm    20   0   23132   2128   1844 S  0.000 0.000   0:00.10                      `- sudosh
56809 descdm    20   0   33120   6060   2948 S  0.000 0.001   0:00.12                          `- bash
22158 descdm    20   0   12552   3768   2420 S  0.000 0.001   0:00.05                              `- bash
23628 descdm    20   0  967632  79440  16516 S  0.000 0.015   0:09.94                                  `- ZMQbg/13
23976 descdm    20   0  482460  59896   5512 S  0.797 0.011   1:45.89                                      `- ZMQbg/3
23979 descdm    20   0  345752  60396   5376 R 110.36 0.011 171:48.25                                      `- ZMQbg/1
23993 descdm    20   0       0      0      0 Z  0.000 0.000   0:50.28                                      `- ZMQbg/9
24007 descdm    20   0  833532  61240   5512 S  1.594 0.012   3:29.46                                      `- ZMQbg/15
```

**Comment by benclifford** [comment]
@TomGlanzman noted to me privately that #860 gives the better exception behaviour that I was expecting, and now gets `ManagerLost` parsl app failures reported as an exceptoin rather than a hang.

**Comment by TomGlanzman** [comment]
Thanks everyone, I think this issue can be closed.  Do I need to take any additional steps so that this update will get into the next release?  

I will open a new issue specifically regarding the max_blocks raised in passing above.

**Comment by benclifford** [comment]
PR #860 still needs to be merged to master. Once that happens, then it will end up in the next release.
