### ISSUE TITLE
Fix sqlite3 integrity error

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#920]
```
2019-05-03 23:57:27 parsl.executors.high_throughput.executor:469 [DEBUG]  [HOLD_BLOCK]: Sending hold to manager:01542a2da9d6
2019-05-03 23:57:27 parsl.executors.high_throughput.executor:437 [DEBUG]  Sent hold request to worker: 01542a2da9d6
Process Process-2:
Traceback (most recent call last):
  File "/home/users/industry/chicago-university/woodard/miniconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/users/industry/chicago-university/woodard/miniconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: task.task_time_submitted

The above exception was the direct cause of the following exception:
```

**Comment by ZhuozhaoLi** [comment]
I have never seen this error before. Do you have a way to reproduce it? It seems this happens after some managers were held?

**Comment by annawoodard** [comment]
I'm closing this, I think it might have been an issue with an old version of a DB. I'll re-open it with instructions to reproduce if I see it again.
